// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/common/v1/common.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。


export interface PlayerSummary {
  playerId?: string; // common.v1.PlayerSummary.player_id
  nickname?: string; // common.v1.PlayerSummary.nickname
  level?: number; // common.v1.PlayerSummary.level
}

