// <auto-generated>
// Code generated by protoc-gen-atlas-client (lang=csharp). DO NOT EDIT.
// source: api/battle/v1/battle_service.proto
// </auto-generated>
#nullable enable
// 序列化语义（protojson）：camelCase 字段名、int64/uint64 读字符串、bytes 为 base64、
// 枚举以枚举名（字符串）下发（未知名前向兼容）。

using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;
using Atlas.Client;
using Atlas.Serialization;
using Atlas.Game.Lockstep;
using Atlas.Google.Protobuf;

namespace Atlas.Battle.V1;

/// <summary>EdgeTransport 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class EdgeTransportConst
{
    public const string EDGETRANSPORTUNSPECIFIED = "EDGE_TRANSPORT_UNSPECIFIED";
    public const string EDGETRANSPORTWS = "EDGE_TRANSPORT_WS";
    public const string EDGETRANSPORTKCP = "EDGE_TRANSPORT_KCP";
    public const string EDGETRANSPORTUDP = "EDGE_TRANSPORT_UDP";
}

/// <summary>PlayerOutReason 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class PlayerOutReasonConst
{
    public const string PLAYEROUTREASONUNSPECIFIED = "PLAYER_OUT_REASON_UNSPECIFIED";
    public const string PLAYEROUTREASONOFFLINETIMEOUT = "PLAYER_OUT_REASON_OFFLINE_TIMEOUT";
}

/// <summary>JoinBattleReq DTO（protojson JSON 语义）。</summary>
public sealed class JoinBattleReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>JoinBattleReply DTO（protojson JSON 语义）。</summary>
public sealed class JoinBattleReply
{
    [JsonPropertyName("meta")]
    public SessionMeta? Meta { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("currentFrame")]
    public ulong? CurrentFrame { get; set; }

    [JsonPropertyName("snapshot")]
    public SnapshotMeta? Snapshot { get; set; }

}

/// <summary>FrameInputReq DTO（protojson JSON 语义）。</summary>
public sealed class FrameInputReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("input")]
    public LockstepInput? Input { get; set; }

}

/// <summary>FrameInputReply DTO（protojson JSON 语义）。</summary>
public sealed class FrameInputReply
{
}

/// <summary>SyncFramesReq DTO（protojson JSON 语义）。</summary>
public sealed class SyncFramesReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("lastSeenFrame")]
    public ulong? LastSeenFrame { get; set; }

}

/// <summary>SyncFramesReply DTO（protojson JSON 语义）。</summary>
public sealed class SyncFramesReply
{
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("currentFrame")]
    public ulong? CurrentFrame { get; set; }

    [JsonPropertyName("snapshot")]
    public SnapshotMeta? Snapshot { get; set; }

    [JsonPropertyName("missed")]
    public List<FrameInputs>? Missed { get; set; }

}

/// <summary>PingReq DTO（protojson JSON 语义）。</summary>
public sealed class PingReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>IssueEntryTicketReq DTO（protojson JSON 语义）。</summary>
public sealed class IssueEntryTicketReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>EdgeEndpoint DTO（protojson JSON 语义）。</summary>
public sealed class EdgeEndpoint
{
    [JsonPropertyName("transport")]
    public string? Transport { get; set; }

    [JsonPropertyName("address")]
    public string? Address { get; set; }

}

/// <summary>BattleTicketEntry DTO（protojson JSON 语义）。</summary>
public sealed class BattleTicketEntry
{
    [JsonPropertyName("playerId")]
    public string? PlayerId { get; set; }

    [JsonPropertyName("ticket")]
    public byte[]? Ticket { get; set; }

}

/// <summary>IssueEntryTicketReply DTO（protojson JSON 语义）。</summary>
public sealed class IssueEntryTicketReply
{
    [JsonPropertyName("endpoints")]
    public List<EdgeEndpoint>? Endpoints { get; set; }

    [JsonPropertyName("tickets")]
    public List<BattleTicketEntry>? Tickets { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("expiresAtUnixMs")]
    public long? ExpiresAtUnixMs { get; set; }

}

/// <summary>FrameBroadcast DTO（protojson JSON 语义）。</summary>
public sealed class FrameBroadcast
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("frame")]
    public LockstepFrame? Frame { get; set; }

}

/// <summary>BattleEndNotify DTO（protojson JSON 语义）。</summary>
public sealed class BattleEndNotify
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("winnerPlayerId")]
    public string? WinnerPlayerId { get; set; }

}

/// <summary>PlayerOutNotify DTO（protojson JSON 语义）。</summary>
public sealed class PlayerOutNotify
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("playerId")]
    public string? PlayerId { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

}

/// <summary>BattleService 的业务 op 客户端 stub：身份由会话承载，消息零身份字段；
/// 序列化经注入的 ISerializer，调用选项经 InvokeOptions 透传；
/// 与 gRPC 生成的 BattleServiceClient（连接级 client）错开命名。</summary>
public sealed class BattleService
{
    private readonly IAtlasInvoker _inv;
    private readonly ISerializer _ser;

    public BattleService(IAtlasInvoker inv, ISerializer ser) { _inv = inv; _ser = ser; }

    /// <summary>/battle.v1.BattleService/JoinBattle：请求-响应；业务拒绝返回业务错误（Reason 为主键）。</summary>
    public async Task<JoinBattleReply?> JoinBattleAsync(JoinBattleReq? req, InvokeOptions? options = null, CancellationToken cancellationToken = default)
    {
        var payload = _ser.Serialize(req ?? new JoinBattleReq());
        var data = await _inv.InvokeRawAsync("/battle.v1.BattleService/JoinBattle", payload, options, cancellationToken);
        return data.Length == 0 ? null : (JoinBattleReply)_ser.Deserialize(data, typeof(JoinBattleReply));
    }
    /// <summary>/battle.v1.BattleService/SendFrameInput：单向调用（returns Empty，无回执）。</summary>
    public async Task SendFrameInputAsync(FrameInputReq? req, InvokeOptions? options = null, CancellationToken cancellationToken = default)
    {
        var payload = _ser.Serialize(req ?? new FrameInputReq());
        await _inv.InvokeRawAsync("/battle.v1.BattleService/SendFrameInput", payload, options, cancellationToken);
    }
    /// <summary>/battle.v1.BattleService/SyncFrames：请求-响应；业务拒绝返回业务错误（Reason 为主键）。</summary>
    public async Task<SyncFramesReply?> SyncFramesAsync(SyncFramesReq? req, InvokeOptions? options = null, CancellationToken cancellationToken = default)
    {
        var payload = _ser.Serialize(req ?? new SyncFramesReq());
        var data = await _inv.InvokeRawAsync("/battle.v1.BattleService/SyncFrames", payload, options, cancellationToken);
        return data.Length == 0 ? null : (SyncFramesReply)_ser.Deserialize(data, typeof(SyncFramesReply));
    }
    /// <summary>/battle.v1.BattleService/Ping：单向调用（returns Empty，无回执）。</summary>
    public async Task PingAsync(PingReq? req, InvokeOptions? options = null, CancellationToken cancellationToken = default)
    {
        var payload = _ser.Serialize(req ?? new PingReq());
        await _inv.InvokeRawAsync("/battle.v1.BattleService/Ping", payload, options, cancellationToken);
    }
}

/// <summary>BattleServiceProtocolOps 是 BattleService 的会话 op 名（按 rpc 名索引）。</summary>
public static class BattleServiceProtocolOps
{
    public const string JoinBattle = "/battle.v1.BattleService/JoinBattle";
    public const string SendFrameInput = "/battle.v1.BattleService/SendFrameInput";
    public const string SyncFrames = "/battle.v1.BattleService/SyncFrames";
    public const string Ping = "/battle.v1.BattleService/Ping";
}
/// <summary>BattleServiceProtocolDescriptor 是 BattleService 的会话描述符提取器
/// （op 名见 BattleServiceProtocolOps；C# 不允许命名空间级方法，故收进静态类）。</summary>
public static class BattleServiceProtocolDescriptor
{
    /// <summary>BattleServiceToken 从会话消息里取 Token（无该字段返回零值）。</summary>
    public static string BattleServiceToken(object? msg) => msg switch
    {
        _ => "",
    };

    /// <summary>BattleServicePlayerID 从会话消息里取 PlayerID（无该字段返回零值）。</summary>
    public static string BattleServicePlayerID(object? msg) => msg switch
    {
        _ => "",
    };

    /// <summary>BattleServiceExpiresAt 从会话消息里取 ExpiresAt（无该字段返回零值）。</summary>
    public static long BattleServiceExpiresAt(object? msg) => msg switch
    {
        _ => 0,
    };

}

/// <summary>BattleServicePushOps 是 api/battle/v1/battle_service.proto 声明的服务端推送 op（客户端按 op 分发）。</summary>
public static class BattleServicePushOps
{
    public const string FrameBroadcast = "/battle.v1.FrameBroadcast";
    public const string BattleEndNotify = "/battle.v1.BattleEndNotify";
    public const string PlayerOutNotify = "/battle.v1.PlayerOutNotify";
}

