// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/matcher/v1/match_events.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。


export interface MatchStartedEvent {
  matchId?: string; // matcher.v1.MatchStartedEvent.match_id
  battleId?: string; // matcher.v1.MatchStartedEvent.battle_id
  playerIds?: string[]; // matcher.v1.MatchStartedEvent.player_ids
  battleEndpoint?: string; // matcher.v1.MatchStartedEvent.battle_endpoint
}

export interface MatchFailedEvent {
  matchId?: string; // matcher.v1.MatchFailedEvent.match_id
  playerIds?: string[]; // matcher.v1.MatchFailedEvent.player_ids
  reason?: MatchFailReason; // matcher.v1.MatchFailedEvent.reason
  ticketId?: string; // matcher.v1.MatchFailedEvent.ticket_id
}

export interface PartyRosterEvent {
  partyId?: string; // matcher.v1.PartyRosterEvent.party_id
  leaderId?: string; // matcher.v1.PartyRosterEvent.leader_id
  playerIds?: string[]; // matcher.v1.PartyRosterEvent.player_ids
  reason?: PartyRosterReason; // matcher.v1.PartyRosterEvent.reason
}

export type MatchFailReason = "MATCH_FAIL_REASON_UNSPECIFIED" | "MATCH_FAIL_REASON_TIMEOUT" | "MATCH_FAIL_REASON_CANCELLED" | "MATCH_FAIL_REASON_ACCEPTANCE_FAILED" | "MATCH_FAIL_REASON_PLACEMENT_FAILED" | "MATCH_FAIL_REASON_FAILED";

export type PartyRosterReason = "PARTY_ROSTER_REASON_UNSPECIFIED" | "PARTY_ROSTER_REASON_CREATED" | "PARTY_ROSTER_REASON_JOIN" | "PARTY_ROSTER_REASON_LEAVE" | "PARTY_ROSTER_REASON_DISSOLVE";

