// <auto-generated>
// Code generated by protoc-gen-atlas-client (lang=csharp). DO NOT EDIT.
// source: api/atlas/v1/route.proto
// </auto-generated>
#nullable enable
// 序列化语义（protojson）：camelCase 字段名、int64/uint64 读字符串、bytes 为 base64、
// 枚举以枚举名（字符串）下发（未知名前向兼容）。

using System.Text.Json.Serialization;

namespace Atlas.Route.V1;

/// <summary>Access 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class AccessConst
{
    public const string ACCESSUNSPECIFIED = "ACCESS_UNSPECIFIED";
    public const string ACCESSCLIENT = "ACCESS_CLIENT";
    public const string ACCESSINTERNAL = "ACCESS_INTERNAL";
}

/// <summary>UidSource 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class UidSourceConst
{
    public const string UIDSOURCEUNSPECIFIED = "UID_SOURCE_UNSPECIFIED";
    public const string UIDSOURCESESSION = "UID_SOURCE_SESSION";
    public const string UIDSOURCEFIELD = "UID_SOURCE_FIELD";
}

/// <summary>Idempotency 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class IdempotencyConst
{
    public const string IDEMPOTENCYUNSPECIFIED = "IDEMPOTENCY_UNSPECIFIED";
    public const string IDEMPOTENT = "IDEMPOTENT";
}

/// <summary>RateLimitScope 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class RateLimitScopeConst
{
    public const string RATELIMITSCOPEUNSPECIFIED = "RATE_LIMIT_SCOPE_UNSPECIFIED";
    public const string RATELIMITSCOPEPLAYER = "RATE_LIMIT_SCOPE_PLAYER";
    public const string RATELIMITSCOPEGLOBAL = "RATE_LIMIT_SCOPE_GLOBAL";
}

/// <summary>RouteRule DTO（protojson JSON 语义）。</summary>
public sealed class RouteRule
{
    [JsonPropertyName("actor")]
    public string? Actor { get; set; }

    [JsonPropertyName("access")]
    public string? Access { get; set; }

    [JsonPropertyName("uid")]
    public string? Uid { get; set; }

    [JsonPropertyName("uidField")]
    public string? UidField { get; set; }

    [JsonPropertyName("idempotency")]
    public string? Idempotency { get; set; }

    [JsonPropertyName("since")]
    public string? Since { get; set; }

    [JsonPropertyName("deprecated")]
    public string? Deprecated { get; set; }

    [JsonPropertyName("replacement")]
    public string? Replacement { get; set; }

    [JsonPropertyName("rateLimit")]
    public RateLimit? RateLimit { get; set; }

}

/// <summary>RouteOverride DTO（protojson JSON 语义）。</summary>
public sealed class RouteOverride
{
    [JsonPropertyName("access")]
    public string? Access { get; set; }

    [JsonPropertyName("uid")]
    public string? Uid { get; set; }

    [JsonPropertyName("uidField")]
    public string? UidField { get; set; }

    [JsonPropertyName("idempotency")]
    public string? Idempotency { get; set; }

    [JsonPropertyName("since")]
    public string? Since { get; set; }

    [JsonPropertyName("deprecated")]
    public string? Deprecated { get; set; }

    [JsonPropertyName("replacement")]
    public string? Replacement { get; set; }

    [JsonPropertyName("rateLimit")]
    public RateLimit? RateLimit { get; set; }

}

/// <summary>RateLimit DTO（protojson JSON 语义）。</summary>
public sealed class RateLimit
{
    [JsonPropertyName("qps")]
    public uint? Qps { get; set; }

    [JsonPropertyName("burst")]
    public uint? Burst { get; set; }

    [JsonPropertyName("scope")]
    public string? Scope { get; set; }

}

