// gateway 客户端协议（业务通道：tcp/ws 传输）：注册/登录/心跳与挤下线通知。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/gateway/v1/auth.proto

package gatewayv1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest 注册：账号不存在则创建玩家。
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// LoginRequest 登录：凭注册回执的玩家 ID 建立会话（注册与登录两段式，D8）。
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginReply 登录回执：token 用于战斗通道绑定与后续鉴权。
type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// HeartbeatRequest 心跳保活（携带令牌与玩家 ID，服务端续租路由 TTL）。
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *HeartbeatRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *HeartbeatRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// HeartbeatReply 心跳回执（携带服务端时间用于对时）。
type HeartbeatReply struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ts               int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	ServerTimeUnixMs uint64                 `protobuf:"varint,2,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatReply) Reset() {
	*x = HeartbeatReply{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatReply) ProtoMessage() {}

func (x *HeartbeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatReply.ProtoReflect.Descriptor instead.
func (*HeartbeatReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatReply) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *HeartbeatReply) GetServerTimeUnixMs() uint64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

// LogoutRequest 登出（清理会话与路由）。
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogoutRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{7}
}

// KickedNotify 服务端推送：被挤下线（旧连接断开前收到）。
type KickedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickedNotify) Reset() {
	*x = KickedNotify{}
	mi := &file_api_gateway_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickedNotify) ProtoMessage() {}

func (x *KickedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickedNotify.ProtoReflect.Descriptor instead.
func (*KickedNotify) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *KickedNotify) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_gateway_v1_auth_proto protoreflect.FileDescriptor

const file_api_gateway_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x19api/gateway/v1/auth.proto\x12\n" +
	"gateway.v1\x1a\x1aapi/common/v1/common.proto\"c\n" +
	"\x0fRegisterRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\",\n" +
	"\rRegisterReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"G\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"q\n" +
	"\n" +
	"LoginReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x120\n" +
	"\x06player\x18\x03 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"U\n" +
	"\x10HeartbeatRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"O\n" +
	"\x0eHeartbeatReply\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12-\n" +
	"\x13server_time_unix_ms\x18\x02 \x01(\x04R\x10serverTimeUnixMs\"B\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\"\r\n" +
	"\vLogoutReply\"&\n" +
	"\fKickedNotify\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason2\x91\x02\n" +
	"\vGatewayAuth\x12B\n" +
	"\bRegister\x12\x1b.gateway.v1.RegisterRequest\x1a\x19.gateway.v1.RegisterReply\x129\n" +
	"\x05Login\x12\x18.gateway.v1.LoginRequest\x1a\x16.gateway.v1.LoginReply\x12E\n" +
	"\tHeartbeat\x12\x1c.gateway.v1.HeartbeatRequest\x1a\x1a.gateway.v1.HeartbeatReply\x12<\n" +
	"\x06Logout\x12\x19.gateway.v1.LogoutRequest\x1a\x17.gateway.v1.LogoutReplyBAZ?github.com/huangyuCN/atlas-game-layout/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_auth_proto_rawDescOnce sync.Once
	file_api_gateway_v1_auth_proto_rawDescData []byte
)

func file_api_gateway_v1_auth_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_auth_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_auth_proto_rawDesc), len(file_api_gateway_v1_auth_proto_rawDesc)))
	})
	return file_api_gateway_v1_auth_proto_rawDescData
}

var file_api_gateway_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_gateway_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),  // 0: gateway.v1.RegisterRequest
	(*RegisterReply)(nil),    // 1: gateway.v1.RegisterReply
	(*LoginRequest)(nil),     // 2: gateway.v1.LoginRequest
	(*LoginReply)(nil),       // 3: gateway.v1.LoginReply
	(*HeartbeatRequest)(nil), // 4: gateway.v1.HeartbeatRequest
	(*HeartbeatReply)(nil),   // 5: gateway.v1.HeartbeatReply
	(*LogoutRequest)(nil),    // 6: gateway.v1.LogoutRequest
	(*LogoutReply)(nil),      // 7: gateway.v1.LogoutReply
	(*KickedNotify)(nil),     // 8: gateway.v1.KickedNotify
	(*v1.PlayerSummary)(nil), // 9: common.v1.PlayerSummary
}
var file_api_gateway_v1_auth_proto_depIdxs = []int32{
	9, // 0: gateway.v1.LoginReply.player:type_name -> common.v1.PlayerSummary
	0, // 1: gateway.v1.GatewayAuth.Register:input_type -> gateway.v1.RegisterRequest
	2, // 2: gateway.v1.GatewayAuth.Login:input_type -> gateway.v1.LoginRequest
	4, // 3: gateway.v1.GatewayAuth.Heartbeat:input_type -> gateway.v1.HeartbeatRequest
	6, // 4: gateway.v1.GatewayAuth.Logout:input_type -> gateway.v1.LogoutRequest
	1, // 5: gateway.v1.GatewayAuth.Register:output_type -> gateway.v1.RegisterReply
	3, // 6: gateway.v1.GatewayAuth.Login:output_type -> gateway.v1.LoginReply
	5, // 7: gateway.v1.GatewayAuth.Heartbeat:output_type -> gateway.v1.HeartbeatReply
	7, // 8: gateway.v1.GatewayAuth.Logout:output_type -> gateway.v1.LogoutReply
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_auth_proto_init() }
func file_api_gateway_v1_auth_proto_init() {
	if File_api_gateway_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_auth_proto_rawDesc), len(file_api_gateway_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_auth_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_auth_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_auth_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_auth_proto = out.File
	file_api_gateway_v1_auth_proto_goTypes = nil
	file_api_gateway_v1_auth_proto_depIdxs = nil
}
