// Code generated by protoc-gen-atlas-tcp. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-tcp v1.0.0
// - protoc             v5.26.1
// source: api/gateway/v1/battle.proto

package gatewayv1

import (
	lockstep "github.com/huangyuCN/atlas/api/lockstep"
)

import (
	"context"

	tcpt "github.com/huangyuCN/atlas/transport/tcp"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the atlas transport/tcp package it is being compiled against.
var _ = new(context.Context)

const _ = tcpt.SupportPackageIsVersion1

// Operation 常量定义 TCP 调用使用的完整方法名。
const OperationGatewayBattleJoinBattleTCP = "/gateway.v1.GatewayBattle/JoinBattle"
const OperationGatewayBattleSendFrameInputTCP = "/gateway.v1.GatewayBattle/SendFrameInput"
const OperationGatewayBattleSyncFramesTCP = "/gateway.v1.GatewayBattle/SyncFrames"

// GatewayBattleTCPClient 定义通过 TCP 调用服务的方法集合。
type GatewayBattleTCPClient interface {
	JoinBattle(ctx context.Context, req *JoinBattleRequest) (*JoinBattleReply, error)
	SendFrameInput(ctx context.Context, req *SendFrameInputRequest) (*SendFrameInputReply, error)
	SyncFrames(ctx context.Context, req *lockstep.SyncFrameRequest) (*lockstep.SyncFrameReply, error)
}

type gatewayBattleTCPClient struct {
	cc *tcpt.Client
}

// NewGatewayBattleTCPClient 创建 TCP 客户端。
func NewGatewayBattleTCPClient(cc *tcpt.Client) GatewayBattleTCPClient {
	return &gatewayBattleTCPClient{cc: cc}
}

func (c *gatewayBattleTCPClient) JoinBattle(ctx context.Context, in *JoinBattleRequest) (*JoinBattleReply, error) {
	var out JoinBattleReply
	if err := c.cc.Invoke(ctx, OperationGatewayBattleJoinBattleTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayBattleTCPClient) SendFrameInput(ctx context.Context, in *SendFrameInputRequest) (*SendFrameInputReply, error) {
	var out SendFrameInputReply
	if err := c.cc.Invoke(ctx, OperationGatewayBattleSendFrameInputTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayBattleTCPClient) SyncFrames(ctx context.Context, in *lockstep.SyncFrameRequest) (*lockstep.SyncFrameReply, error) {
	var out lockstep.SyncFrameReply
	if err := c.cc.Invoke(ctx, OperationGatewayBattleSyncFramesTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GatewayBattleTCPServer 定义需要由用户实现的服务端接口。
type GatewayBattleTCPServer interface {
	JoinBattle(context.Context, *JoinBattleRequest) (*JoinBattleReply, error)
	SendFrameInput(context.Context, *SendFrameInputRequest) (*SendFrameInputReply, error)
	// SyncFrames SyncFrames 补帧：断线重连后按帧区间拉取缺失帧（复用 lockstep 协议）。
	SyncFrames(context.Context, *lockstep.SyncFrameRequest) (*lockstep.SyncFrameReply, error)
}

// RegisterGatewayBattleTCPServer 在给定 TCP Server 上注册服务实现。
func RegisterGatewayBattleTCPServer(s *tcpt.Server, srv GatewayBattleTCPServer) error {
	if err := s.Subscribe(OperationGatewayBattleJoinBattleTCP, _GatewayBattle_JoinBattle0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayBattleSendFrameInputTCP, _GatewayBattle_SendFrameInput0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayBattleSyncFramesTCP, _GatewayBattle_SyncFrames0_TCP_Handler(srv)); err != nil {
		return err
	}
	return nil
}

func _GatewayBattle_JoinBattle0_TCP_Handler(srv GatewayBattleTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(JoinBattleRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.JoinBattle(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayBattle_SendFrameInput0_TCP_Handler(srv GatewayBattleTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(SendFrameInputRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.SendFrameInput(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayBattle_SyncFrames0_TCP_Handler(srv GatewayBattleTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(lockstep.SyncFrameRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.SyncFrames(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}
