// gateway 战斗通道协议（kcp/udp/ws 传输）：
// 加入战斗与帧输入上行；帧广播/战斗结束为服务端推送消息。
// 帧数据复用 Atlas api/lockstep 的 LockstepInput/LockstepFrame。
//
// 协议边界约定（客户端 op 统一住 api/gateway/v1，与 player_client.proto 一致）：
//   - 客户端 op 定义在 GatewayXxx 服务（携带 token 鉴权位）；
//   - battle 引擎内部契约与管理面在 api/battle/v1（被本文件单向引用）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/gateway/v1/battle_client.proto

package gatewayv1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/battle/v1"
	lockstep "github.com/huangyuCN/atlas/api/lockstep"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JoinBattleRequest 加入战斗（战斗通道 token 绑定后调用）。
type JoinBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // 登录令牌（快速绑定，无需二次登录）
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` // 玩家 ID
	BattleId      string                 `protobuf:"bytes,3,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"` // 战斗 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBattleRequest) Reset() {
	*x = JoinBattleRequest{}
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBattleRequest) ProtoMessage() {}

func (x *JoinBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBattleRequest.ProtoReflect.Descriptor instead.
func (*JoinBattleRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_battle_client_proto_rawDescGZIP(), []int{0}
}

func (x *JoinBattleRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinBattleRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinBattleRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// SendFrameInputRequest 帧输入上行（客户端 → gateway → battle）。
// 玩家身份以连接会话绑定为准（忽略客户端自报，防伪造）。
type SendFrameInputRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Input         *lockstep.LockstepInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrameInputRequest) Reset() {
	*x = SendFrameInputRequest{}
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrameInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrameInputRequest) ProtoMessage() {}

func (x *SendFrameInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrameInputRequest.ProtoReflect.Descriptor instead.
func (*SendFrameInputRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_battle_client_proto_rawDescGZIP(), []int{1}
}

func (x *SendFrameInputRequest) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *SendFrameInputRequest) GetInput() *lockstep.LockstepInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type SendFrameInputReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFrameInputReply) Reset() {
	*x = SendFrameInputReply{}
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFrameInputReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFrameInputReply) ProtoMessage() {}

func (x *SendFrameInputReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFrameInputReply.ProtoReflect.Descriptor instead.
func (*SendFrameInputReply) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_battle_client_proto_rawDescGZIP(), []int{2}
}

// FrameBroadcast 服务端推送：帧广播下行。
type FrameBroadcast struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BattleId      string                  `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	Frame         *lockstep.LockstepFrame `protobuf:"bytes,2,opt,name=frame,proto3" json:"frame,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameBroadcast) Reset() {
	*x = FrameBroadcast{}
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameBroadcast) ProtoMessage() {}

func (x *FrameBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameBroadcast.ProtoReflect.Descriptor instead.
func (*FrameBroadcast) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_battle_client_proto_rawDescGZIP(), []int{3}
}

func (x *FrameBroadcast) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *FrameBroadcast) GetFrame() *lockstep.LockstepFrame {
	if x != nil {
		return x.Frame
	}
	return nil
}

// BattleEndNotify 服务端推送：战斗结束通知。
type BattleEndNotify struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BattleId       string                 `protobuf:"bytes,1,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	WinnerPlayerId string                 `protobuf:"bytes,2,opt,name=winner_player_id,json=winnerPlayerId,proto3" json:"winner_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BattleEndNotify) Reset() {
	*x = BattleEndNotify{}
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEndNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEndNotify) ProtoMessage() {}

func (x *BattleEndNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_v1_battle_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEndNotify.ProtoReflect.Descriptor instead.
func (*BattleEndNotify) Descriptor() ([]byte, []int) {
	return file_api_gateway_v1_battle_client_proto_rawDescGZIP(), []int{4}
}

func (x *BattleEndNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *BattleEndNotify) GetWinnerPlayerId() string {
	if x != nil {
		return x.WinnerPlayerId
	}
	return ""
}

var File_api_gateway_v1_battle_client_proto protoreflect.FileDescriptor

const file_api_gateway_v1_battle_client_proto_rawDesc = "" +
	"\n" +
	"\"api/gateway/v1/battle_client.proto\x12\n" +
	"gateway.v1\x1a\x1bapi/lockstep/lockstep.proto\x1a\x1aapi/battle/v1/battle.proto\"c\n" +
	"\x11JoinBattleRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1b\n" +
	"\tbattle_id\x18\x03 \x01(\tR\bbattleId\"n\n" +
	"\x15SendFrameInputRequest\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05input\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepInputR\x05input\"\x15\n" +
	"\x13SendFrameInputReply\"g\n" +
	"\x0eFrameBroadcast\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x128\n" +
	"\x05frame\x18\x02 \x01(\v2\".atlas.game.lockstep.LockstepFrameR\x05frame\"X\n" +
	"\x0fBattleEndNotify\x12\x1b\n" +
	"\tbattle_id\x18\x01 \x01(\tR\bbattleId\x12(\n" +
	"\x10winner_player_id\x18\x02 \x01(\tR\x0ewinnerPlayerId2\x88\x02\n" +
	"\rGatewayBattle\x12G\n" +
	"\n" +
	"JoinBattle\x12\x1d.gateway.v1.JoinBattleRequest\x1a\x1a.battle.v1.JoinBattleReply\x12T\n" +
	"\x0eSendFrameInput\x12!.gateway.v1.SendFrameInputRequest\x1a\x1f.gateway.v1.SendFrameInputReply\x12X\n" +
	"\n" +
	"SyncFrames\x12%.atlas.game.lockstep.SyncFrameRequest\x1a#.atlas.game.lockstep.SyncFrameReplyBAZ?github.com/huangyuCN/atlas-game-layout/api/gateway/v1;gatewayv1b\x06proto3"

var (
	file_api_gateway_v1_battle_client_proto_rawDescOnce sync.Once
	file_api_gateway_v1_battle_client_proto_rawDescData []byte
)

func file_api_gateway_v1_battle_client_proto_rawDescGZIP() []byte {
	file_api_gateway_v1_battle_client_proto_rawDescOnce.Do(func() {
		file_api_gateway_v1_battle_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_v1_battle_client_proto_rawDesc), len(file_api_gateway_v1_battle_client_proto_rawDesc)))
	})
	return file_api_gateway_v1_battle_client_proto_rawDescData
}

var file_api_gateway_v1_battle_client_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_gateway_v1_battle_client_proto_goTypes = []any{
	(*JoinBattleRequest)(nil),         // 0: gateway.v1.JoinBattleRequest
	(*SendFrameInputRequest)(nil),     // 1: gateway.v1.SendFrameInputRequest
	(*SendFrameInputReply)(nil),       // 2: gateway.v1.SendFrameInputReply
	(*FrameBroadcast)(nil),            // 3: gateway.v1.FrameBroadcast
	(*BattleEndNotify)(nil),           // 4: gateway.v1.BattleEndNotify
	(*lockstep.LockstepInput)(nil),    // 5: atlas.game.lockstep.LockstepInput
	(*lockstep.LockstepFrame)(nil),    // 6: atlas.game.lockstep.LockstepFrame
	(*lockstep.SyncFrameRequest)(nil), // 7: atlas.game.lockstep.SyncFrameRequest
	(*v1.JoinBattleReply)(nil),        // 8: battle.v1.JoinBattleReply
	(*lockstep.SyncFrameReply)(nil),   // 9: atlas.game.lockstep.SyncFrameReply
}
var file_api_gateway_v1_battle_client_proto_depIdxs = []int32{
	5, // 0: gateway.v1.SendFrameInputRequest.input:type_name -> atlas.game.lockstep.LockstepInput
	6, // 1: gateway.v1.FrameBroadcast.frame:type_name -> atlas.game.lockstep.LockstepFrame
	0, // 2: gateway.v1.GatewayBattle.JoinBattle:input_type -> gateway.v1.JoinBattleRequest
	1, // 3: gateway.v1.GatewayBattle.SendFrameInput:input_type -> gateway.v1.SendFrameInputRequest
	7, // 4: gateway.v1.GatewayBattle.SyncFrames:input_type -> atlas.game.lockstep.SyncFrameRequest
	8, // 5: gateway.v1.GatewayBattle.JoinBattle:output_type -> battle.v1.JoinBattleReply
	2, // 6: gateway.v1.GatewayBattle.SendFrameInput:output_type -> gateway.v1.SendFrameInputReply
	9, // 7: gateway.v1.GatewayBattle.SyncFrames:output_type -> atlas.game.lockstep.SyncFrameReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_battle_client_proto_init() }
func file_api_gateway_v1_battle_client_proto_init() {
	if File_api_gateway_v1_battle_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_battle_client_proto_rawDesc), len(file_api_gateway_v1_battle_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_battle_client_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_battle_client_proto_depIdxs,
		MessageInfos:      file_api_gateway_v1_battle_client_proto_msgTypes,
	}.Build()
	File_api_gateway_v1_battle_client_proto = out.File
	file_api_gateway_v1_battle_client_proto_goTypes = nil
	file_api_gateway_v1_battle_client_proto_depIdxs = nil
}
