// Code generated by protoc-gen-atlas-tcp. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-tcp v1.0.0
// - protoc             v5.26.1
// source: api/gateway/v1/player_client.proto

package gatewayv1

import (
	"context"

	tcpt "github.com/huangyuCN/atlas/transport/tcp"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the atlas transport/tcp package it is being compiled against.
var _ = new(context.Context)

const _ = tcpt.SupportPackageIsVersion1

// Operation 常量定义 TCP 调用使用的完整方法名。
const OperationGatewayPlayerGetPlayerDataTCP = "/gateway.v1.GatewayPlayer/GetPlayerData"
const OperationGatewayPlayerHeartbeatTCP = "/gateway.v1.GatewayPlayer/Heartbeat"
const OperationGatewayPlayerLoginTCP = "/gateway.v1.GatewayPlayer/Login"
const OperationGatewayPlayerLogoutTCP = "/gateway.v1.GatewayPlayer/Logout"
const OperationGatewayPlayerRegisterTCP = "/gateway.v1.GatewayPlayer/Register"

// GatewayPlayerTCPClient 定义通过 TCP 调用服务的方法集合。
type GatewayPlayerTCPClient interface {
	GetPlayerData(ctx context.Context, req *PlayerDataRequest) (*PlayerDataReply, error)
	Heartbeat(ctx context.Context, req *HeartbeatRequest) (*HeartbeatReply, error)
	Login(ctx context.Context, req *LoginRequest) (*LoginReply, error)
	Logout(ctx context.Context, req *LogoutRequest) (*LogoutReply, error)
	Register(ctx context.Context, req *RegisterRequest) (*RegisterReply, error)
}

type gatewayPlayerTCPClient struct {
	cc *tcpt.Client
}

// NewGatewayPlayerTCPClient 创建 TCP 客户端。
func NewGatewayPlayerTCPClient(cc *tcpt.Client) GatewayPlayerTCPClient {
	return &gatewayPlayerTCPClient{cc: cc}
}

func (c *gatewayPlayerTCPClient) GetPlayerData(ctx context.Context, in *PlayerDataRequest) (*PlayerDataReply, error) {
	var out PlayerDataReply
	if err := c.cc.Invoke(ctx, OperationGatewayPlayerGetPlayerDataTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayPlayerTCPClient) Heartbeat(ctx context.Context, in *HeartbeatRequest) (*HeartbeatReply, error) {
	var out HeartbeatReply
	if err := c.cc.Invoke(ctx, OperationGatewayPlayerHeartbeatTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayPlayerTCPClient) Login(ctx context.Context, in *LoginRequest) (*LoginReply, error) {
	var out LoginReply
	if err := c.cc.Invoke(ctx, OperationGatewayPlayerLoginTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayPlayerTCPClient) Logout(ctx context.Context, in *LogoutRequest) (*LogoutReply, error) {
	var out LogoutReply
	if err := c.cc.Invoke(ctx, OperationGatewayPlayerLogoutTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *gatewayPlayerTCPClient) Register(ctx context.Context, in *RegisterRequest) (*RegisterReply, error) {
	var out RegisterReply
	if err := c.cc.Invoke(ctx, OperationGatewayPlayerRegisterTCP, in, &out); err != nil {
		return nil, err
	}
	return &out, nil
}

// GatewayPlayerTCPServer 定义需要由用户实现的服务端接口。
type GatewayPlayerTCPServer interface {
	GetPlayerData(context.Context, *PlayerDataRequest) (*PlayerDataReply, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatReply, error)
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	Logout(context.Context, *LogoutRequest) (*LogoutReply, error)
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
}

// RegisterGatewayPlayerTCPServer 在给定 TCP Server 上注册服务实现。
func RegisterGatewayPlayerTCPServer(s *tcpt.Server, srv GatewayPlayerTCPServer) error {
	if err := s.Subscribe(OperationGatewayPlayerRegisterTCP, _GatewayPlayer_Register0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayPlayerLoginTCP, _GatewayPlayer_Login0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayPlayerHeartbeatTCP, _GatewayPlayer_Heartbeat0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayPlayerLogoutTCP, _GatewayPlayer_Logout0_TCP_Handler(srv)); err != nil {
		return err
	}
	if err := s.Subscribe(OperationGatewayPlayerGetPlayerDataTCP, _GatewayPlayer_GetPlayerData0_TCP_Handler(srv)); err != nil {
		return err
	}
	return nil
}

func _GatewayPlayer_Register0_TCP_Handler(srv GatewayPlayerTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(RegisterRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.Register(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayPlayer_Login0_TCP_Handler(srv GatewayPlayerTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(LoginRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.Login(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayPlayer_Heartbeat0_TCP_Handler(srv GatewayPlayerTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(HeartbeatRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.Heartbeat(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayPlayer_Logout0_TCP_Handler(srv GatewayPlayerTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(LogoutRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.Logout(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}

func _GatewayPlayer_GetPlayerData0_TCP_Handler(srv GatewayPlayerTCPServer) tcpt.MsgHandler {
	return func(ctx context.Context, dec tcpt.Decoder, enc tcpt.Encoder) ([]byte, error) {
		in := new(PlayerDataRequest)
		if err := dec(in); err != nil {
			return nil, err
		}
		out, err := srv.GetPlayerData(ctx, in)
		if err != nil {
			return nil, err
		}
		if out == nil {
			return nil, nil
		}
		return enc(out)
	}
}
