// <auto-generated>
// Code generated by protoc-gen-atlas-client (lang=csharp). DO NOT EDIT.
// source: api/matcher/v1/match_events.proto
// </auto-generated>
#nullable enable
// 序列化语义（protojson）：camelCase 字段名、int64/uint64 读字符串、bytes 为 base64、
// 枚举以枚举名（字符串）下发（未知名前向兼容）。

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Atlas.Client;

namespace Atlas.Matcher.V1;

/// <summary>MatchFailReason 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class MatchFailReasonConst
{
    public const string MATCHFAILREASONUNSPECIFIED = "MATCH_FAIL_REASON_UNSPECIFIED";
    public const string MATCHFAILREASONTIMEOUT = "MATCH_FAIL_REASON_TIMEOUT";
    public const string MATCHFAILREASONCANCELLED = "MATCH_FAIL_REASON_CANCELLED";
    public const string MATCHFAILREASONACCEPTANCEFAILED = "MATCH_FAIL_REASON_ACCEPTANCE_FAILED";
    public const string MATCHFAILREASONPLACEMENTFAILED = "MATCH_FAIL_REASON_PLACEMENT_FAILED";
    public const string MATCHFAILREASONFAILED = "MATCH_FAIL_REASON_FAILED";
}

/// <summary>PartyRosterReason 的枚举名常量（protojson 以枚举名下发；未知值前向兼容）。</summary>
public static class PartyRosterReasonConst
{
    public const string PARTYROSTERREASONUNSPECIFIED = "PARTY_ROSTER_REASON_UNSPECIFIED";
    public const string PARTYROSTERREASONCREATED = "PARTY_ROSTER_REASON_CREATED";
    public const string PARTYROSTERREASONJOIN = "PARTY_ROSTER_REASON_JOIN";
    public const string PARTYROSTERREASONLEAVE = "PARTY_ROSTER_REASON_LEAVE";
    public const string PARTYROSTERREASONDISSOLVE = "PARTY_ROSTER_REASON_DISSOLVE";
}

/// <summary>MatchStartedEvent DTO（protojson JSON 语义）。</summary>
public sealed class MatchStartedEvent
{
    [JsonPropertyName("matchId")]
    public string? MatchId { get; set; }

    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("playerIds")]
    public List<string>? PlayerIds { get; set; }

    [JsonPropertyName("battleEndpoint")]
    public string? BattleEndpoint { get; set; }

}

/// <summary>MatchFailedEvent DTO（protojson JSON 语义）。</summary>
public sealed class MatchFailedEvent
{
    [JsonPropertyName("matchId")]
    public string? MatchId { get; set; }

    [JsonPropertyName("playerIds")]
    public List<string>? PlayerIds { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

    [JsonPropertyName("ticketId")]
    public string? TicketId { get; set; }

}

/// <summary>PartyRosterEvent DTO（protojson JSON 语义）。</summary>
public sealed class PartyRosterEvent
{
    [JsonPropertyName("partyId")]
    public string? PartyId { get; set; }

    [JsonPropertyName("leaderId")]
    public string? LeaderId { get; set; }

    [JsonPropertyName("playerIds")]
    public List<string>? PlayerIds { get; set; }

    [JsonPropertyName("reason")]
    public string? Reason { get; set; }

}

