// 公共配置：日志（级别/格式，装配见 pkg/log）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: protobuf/configs/log.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_protobuf_configs_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Log) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_protobuf_configs_log_proto protoreflect.FileDescriptor

const file_protobuf_configs_log_proto_rawDesc = "" +
	"\n" +
	"\x1aprotobuf/configs/log.proto\x12\ratlas.configs\"3\n" +
	"\x03Log\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06formatBAZ?github.com/huangyuCN/atlas-game-layout/protobuf/configs;configsb\x06proto3"

var (
	file_protobuf_configs_log_proto_rawDescOnce sync.Once
	file_protobuf_configs_log_proto_rawDescData []byte
)

func file_protobuf_configs_log_proto_rawDescGZIP() []byte {
	file_protobuf_configs_log_proto_rawDescOnce.Do(func() {
		file_protobuf_configs_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_configs_log_proto_rawDesc), len(file_protobuf_configs_log_proto_rawDesc)))
	})
	return file_protobuf_configs_log_proto_rawDescData
}

var file_protobuf_configs_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_configs_log_proto_goTypes = []any{
	(*Log)(nil), // 0: atlas.configs.Log
}
var file_protobuf_configs_log_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_configs_log_proto_init() }
func file_protobuf_configs_log_proto_init() {
	if File_protobuf_configs_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_configs_log_proto_rawDesc), len(file_protobuf_configs_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_configs_log_proto_goTypes,
		DependencyIndexes: file_protobuf_configs_log_proto_depIdxs,
		MessageInfos:      file_protobuf_configs_log_proto_msgTypes,
	}.Build()
	File_protobuf_configs_log_proto = out.File
	file_protobuf_configs_log_proto_goTypes = nil
	file_protobuf_configs_log_proto_depIdxs = nil
}
