// 公共配置：可观测性（链路追踪 OTLP 导出端点 + 指标暴露）。
// 空端点 = 不注册 exporter（noop，零开销）；配置后服务侧 span 经 OTLP gRPC
// 导出到 Tempo/Jaeger 等后端，Grafana 面板查询链路；
// 指标经 Prometheus 文本端点暴露，由 Prometheus 抓取、Grafana 面板查询。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: protobuf/configs/observability.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Observability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// otlp 是 OTLP gRPC 导出端点（host:port，如 127.0.0.1:4317）；空 = 不导出。
	Otlp string `protobuf:"bytes,1,opt,name=otlp,proto3" json:"otlp,omitempty"`
	// metrics 是指标暴露配置；不配置 = 不暴露任何端点（noop，零开销）。
	Metrics       *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_protobuf_configs_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_observability_proto_rawDescGZIP(), []int{0}
}

func (x *Observability) GetOtlp() string {
	if x != nil {
		return x.Otlp
	}
	return ""
}

func (x *Observability) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Metrics 是指标暴露配置。
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prometheus 是 Prometheus 抓取端点监听地址（host:port，如 0.0.0.0:9150）；
	// 空 = 不暴露（采集器退化为 noop）。
	Prometheus    string `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_protobuf_configs_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_observability_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetPrometheus() string {
	if x != nil {
		return x.Prometheus
	}
	return ""
}

var File_protobuf_configs_observability_proto protoreflect.FileDescriptor

const file_protobuf_configs_observability_proto_rawDesc = "" +
	"\n" +
	"$protobuf/configs/observability.proto\x12\ratlas.configs\"U\n" +
	"\rObservability\x12\x12\n" +
	"\x04otlp\x18\x01 \x01(\tR\x04otlp\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.atlas.configs.MetricsR\ametrics\")\n" +
	"\aMetrics\x12\x1e\n" +
	"\n" +
	"prometheus\x18\x01 \x01(\tR\n" +
	"prometheusBAZ?github.com/huangyuCN/atlas-game-layout/protobuf/configs;configsb\x06proto3"

var (
	file_protobuf_configs_observability_proto_rawDescOnce sync.Once
	file_protobuf_configs_observability_proto_rawDescData []byte
)

func file_protobuf_configs_observability_proto_rawDescGZIP() []byte {
	file_protobuf_configs_observability_proto_rawDescOnce.Do(func() {
		file_protobuf_configs_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_configs_observability_proto_rawDesc), len(file_protobuf_configs_observability_proto_rawDesc)))
	})
	return file_protobuf_configs_observability_proto_rawDescData
}

var file_protobuf_configs_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_configs_observability_proto_goTypes = []any{
	(*Observability)(nil), // 0: atlas.configs.Observability
	(*Metrics)(nil),       // 1: atlas.configs.Metrics
}
var file_protobuf_configs_observability_proto_depIdxs = []int32{
	1, // 0: atlas.configs.Observability.metrics:type_name -> atlas.configs.Metrics
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_configs_observability_proto_init() }
func file_protobuf_configs_observability_proto_init() {
	if File_protobuf_configs_observability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_configs_observability_proto_rawDesc), len(file_protobuf_configs_observability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_configs_observability_proto_goTypes,
		DependencyIndexes: file_protobuf_configs_observability_proto_depIdxs,
		MessageInfos:      file_protobuf_configs_observability_proto_msgTypes,
	}.Build()
	File_protobuf_configs_observability_proto = out.File
	file_protobuf_configs_observability_proto_goTypes = nil
	file_protobuf_configs_observability_proto_depIdxs = nil
}
