// 公共配置：可观测性（链路追踪 OTLP 导出 + 指标暴露）。
// 空端点 = 不注册 exporter（noop，零开销）；配置后服务侧 span 经 OTLP 导出到
// Tempo/Jaeger 等后端（gRPC 或 HTTP，由端点 scheme 决定），Grafana 面板查询链路；
// 指标经 Prometheus 文本端点暴露，由 Prometheus 抓取、Grafana 面板查询。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: protobuf/configs/observability.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TraceSampler 是链路采样器种类。
type TraceSampler int32

const (
	// TRACE_SAMPLER_PARENT_BASED_RATIO 跟随上游采样决策，根 span 按 sample_ratio 抽取（默认）。
	TraceSampler_TRACE_SAMPLER_PARENT_BASED_RATIO TraceSampler = 0
	// TRACE_SAMPLER_ALWAYS_ON 全量采集。
	TraceSampler_TRACE_SAMPLER_ALWAYS_ON TraceSampler = 1
	// TRACE_SAMPLER_ALWAYS_OFF 全量丢弃。
	TraceSampler_TRACE_SAMPLER_ALWAYS_OFF TraceSampler = 2
)

// Enum value maps for TraceSampler.
var (
	TraceSampler_name = map[int32]string{
		0: "TRACE_SAMPLER_PARENT_BASED_RATIO",
		1: "TRACE_SAMPLER_ALWAYS_ON",
		2: "TRACE_SAMPLER_ALWAYS_OFF",
	}
	TraceSampler_value = map[string]int32{
		"TRACE_SAMPLER_PARENT_BASED_RATIO": 0,
		"TRACE_SAMPLER_ALWAYS_ON":          1,
		"TRACE_SAMPLER_ALWAYS_OFF":         2,
	}
)

func (x TraceSampler) Enum() *TraceSampler {
	p := new(TraceSampler)
	*p = x
	return p
}

func (x TraceSampler) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceSampler) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_configs_observability_proto_enumTypes[0].Descriptor()
}

func (TraceSampler) Type() protoreflect.EnumType {
	return &file_protobuf_configs_observability_proto_enumTypes[0]
}

func (x TraceSampler) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceSampler.Descriptor instead.
func (TraceSampler) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_configs_observability_proto_rawDescGZIP(), []int{0}
}

type Observability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// otlp 是 OTLP 导出端点，必须带 scheme：
	// grpc://（明文 gRPC）/ grpcs://（TLS gRPC）/ http://（OTLP/HTTP 明文）/ https://（OTLP/HTTP+TLS）；
	// http(s) 不带 path 时使用导出器默认路径 /v1/traces。空 = 不导出。
	Otlp string `protobuf:"bytes,1,opt,name=otlp,proto3" json:"otlp,omitempty"`
	// metrics 是指标暴露配置；不配置 = 不暴露任何端点（noop，零开销）。
	Metrics *Metrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	// sampler 是采样器；不配置 = 跟随父级、根 span 按 sample_ratio 抽取。
	Sampler TraceSampler `protobuf:"varint,3,opt,name=sampler,proto3,enum=atlas.configs.TraceSampler" json:"sampler,omitempty"`
	// sample_ratio 是采样率（0..1，缺省 1.0）；仅 PARENT_BASED_RATIO 使用。
	SampleRatio   *float64 `protobuf:"fixed64,4,opt,name=sample_ratio,json=sampleRatio,proto3,oneof" json:"sample_ratio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_protobuf_configs_observability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_observability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_observability_proto_rawDescGZIP(), []int{0}
}

func (x *Observability) GetOtlp() string {
	if x != nil {
		return x.Otlp
	}
	return ""
}

func (x *Observability) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Observability) GetSampler() TraceSampler {
	if x != nil {
		return x.Sampler
	}
	return TraceSampler_TRACE_SAMPLER_PARENT_BASED_RATIO
}

func (x *Observability) GetSampleRatio() float64 {
	if x != nil && x.SampleRatio != nil {
		return *x.SampleRatio
	}
	return 0
}

// Metrics 是指标暴露配置。
type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prometheus 是 Prometheus 抓取端点监听地址（host:port，如 0.0.0.0:9150）；
	// 空 = 不暴露（采集器退化为 noop）。
	Prometheus    string `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_protobuf_configs_observability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_observability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_observability_proto_rawDescGZIP(), []int{1}
}

func (x *Metrics) GetPrometheus() string {
	if x != nil {
		return x.Prometheus
	}
	return ""
}

var File_protobuf_configs_observability_proto protoreflect.FileDescriptor

const file_protobuf_configs_observability_proto_rawDesc = "" +
	"\n" +
	"$protobuf/configs/observability.proto\x12\ratlas.configs\"\xc5\x01\n" +
	"\rObservability\x12\x12\n" +
	"\x04otlp\x18\x01 \x01(\tR\x04otlp\x120\n" +
	"\ametrics\x18\x02 \x01(\v2\x16.atlas.configs.MetricsR\ametrics\x125\n" +
	"\asampler\x18\x03 \x01(\x0e2\x1b.atlas.configs.TraceSamplerR\asampler\x12&\n" +
	"\fsample_ratio\x18\x04 \x01(\x01H\x00R\vsampleRatio\x88\x01\x01B\x0f\n" +
	"\r_sample_ratio\")\n" +
	"\aMetrics\x12\x1e\n" +
	"\n" +
	"prometheus\x18\x01 \x01(\tR\n" +
	"prometheus*o\n" +
	"\fTraceSampler\x12$\n" +
	" TRACE_SAMPLER_PARENT_BASED_RATIO\x10\x00\x12\x1b\n" +
	"\x17TRACE_SAMPLER_ALWAYS_ON\x10\x01\x12\x1c\n" +
	"\x18TRACE_SAMPLER_ALWAYS_OFF\x10\x02BAZ?github.com/huangyuCN/atlas-game-layout/protobuf/configs;configsb\x06proto3"

var (
	file_protobuf_configs_observability_proto_rawDescOnce sync.Once
	file_protobuf_configs_observability_proto_rawDescData []byte
)

func file_protobuf_configs_observability_proto_rawDescGZIP() []byte {
	file_protobuf_configs_observability_proto_rawDescOnce.Do(func() {
		file_protobuf_configs_observability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_configs_observability_proto_rawDesc), len(file_protobuf_configs_observability_proto_rawDesc)))
	})
	return file_protobuf_configs_observability_proto_rawDescData
}

var file_protobuf_configs_observability_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_configs_observability_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_configs_observability_proto_goTypes = []any{
	(TraceSampler)(0),     // 0: atlas.configs.TraceSampler
	(*Observability)(nil), // 1: atlas.configs.Observability
	(*Metrics)(nil),       // 2: atlas.configs.Metrics
}
var file_protobuf_configs_observability_proto_depIdxs = []int32{
	2, // 0: atlas.configs.Observability.metrics:type_name -> atlas.configs.Metrics
	0, // 1: atlas.configs.Observability.sampler:type_name -> atlas.configs.TraceSampler
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_configs_observability_proto_init() }
func file_protobuf_configs_observability_proto_init() {
	if File_protobuf_configs_observability_proto != nil {
		return
	}
	file_protobuf_configs_observability_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_configs_observability_proto_rawDesc), len(file_protobuf_configs_observability_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_configs_observability_proto_goTypes,
		DependencyIndexes: file_protobuf_configs_observability_proto_depIdxs,
		EnumInfos:         file_protobuf_configs_observability_proto_enumTypes,
		MessageInfos:      file_protobuf_configs_observability_proto_msgTypes,
	}.Build()
	File_protobuf_configs_observability_proto = out.File
	file_protobuf_configs_observability_proto_goTypes = nil
	file_protobuf_configs_observability_proto_depIdxs = nil
}
