// 公共配置：服务运行时身份（服务名/实例/版本/环境/命名空间）。
//
// 缺省约定（唯一规则）见 docs/config.md：name 与 namespace 是必需参数——缺失即装配失败
// （namespace 走 R9 严格模式，无任何兜底）；id/version/env 为空 = 回填缺省，
// 其中 env **仅作链路与指标标签**，不参与任何前缀派生。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: protobuf/configs/runtime.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MinClientVersionMode 是客户端版本门槛的执行模式（协议演进用：客户端是长生命周期二进制，
// 删改 op 前必须能协商与废弃，见统一设计 v2 的 M1）。
type MinClientVersionMode int32

const (
	// MIN_CLIENT_VERSION_MODE_OFF 关闭校验（缺省）：不读客户端版本，不拒绝。
	MinClientVersionMode_MIN_CLIENT_VERSION_MODE_OFF MinClientVersionMode = 0
	// MIN_CLIENT_VERSION_MODE_NEGOTIATE 只协商：记录并暴露客户端版本，不拒绝（灰度期观察用）。
	MinClientVersionMode_MIN_CLIENT_VERSION_MODE_NEGOTIATE MinClientVersionMode = 1
	// MIN_CLIENT_VERSION_MODE_ENFORCE 强制：低于 min_client_version 的客户端登录被拒（带明确 reason）。
	MinClientVersionMode_MIN_CLIENT_VERSION_MODE_ENFORCE MinClientVersionMode = 2
)

// Enum value maps for MinClientVersionMode.
var (
	MinClientVersionMode_name = map[int32]string{
		0: "MIN_CLIENT_VERSION_MODE_OFF",
		1: "MIN_CLIENT_VERSION_MODE_NEGOTIATE",
		2: "MIN_CLIENT_VERSION_MODE_ENFORCE",
	}
	MinClientVersionMode_value = map[string]int32{
		"MIN_CLIENT_VERSION_MODE_OFF":       0,
		"MIN_CLIENT_VERSION_MODE_NEGOTIATE": 1,
		"MIN_CLIENT_VERSION_MODE_ENFORCE":   2,
	}
)

func (x MinClientVersionMode) Enum() *MinClientVersionMode {
	p := new(MinClientVersionMode)
	*p = x
	return p
}

func (x MinClientVersionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MinClientVersionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_configs_runtime_proto_enumTypes[0].Descriptor()
}

func (MinClientVersionMode) Type() protoreflect.EnumType {
	return &file_protobuf_configs_runtime_proto_enumTypes[0]
}

func (x MinClientVersionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MinClientVersionMode.Descriptor instead.
func (MinClientVersionMode) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_configs_runtime_proto_rawDescGZIP(), []int{0}
}

type Runtime struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id      string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Version string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Env     string                 `protobuf:"bytes,4,opt,name=env,proto3" json:"env,omitempty"`
	// namespace 是**唯一命名空间字段**：注册中心键前缀 /atlas/services/<ns>、actor subject 前缀
	// atlas_actor.<ns>、业务 topic 前缀 atlas.<ns>、redis 键前缀 atlas:<ns>:、etcd 目录 /atlas/actors/<ns>
	// 五面全部由它派生（框架唯一派生点 atlas/namespace.Derive，本仓不再自行拼任何前缀）。
	// **必须显式配置，缺失即启动失败**（严格模式 R9：不回落 env、不回落 default、不静默归一）；
	// 取值限 [A-Za-z0-9_-]，非法字符同样启动失败。env 仅作链路与指标标签，不参与任何前缀派生。
	// 缺省约定与五面派生表见 docs/config.md。
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// min_client_version 是允许登录的最低客户端版本（semver，如 1.4.0）；空 = 不设门槛。
	// 仅当 min_client_version_mode = ENFORCE 时才会据此拒绝低于该版本的客户端登录。
	MinClientVersion string `protobuf:"bytes,6,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version,omitempty"`
	// min_client_version_mode 是客户端版本门槛的执行模式（缺省 OFF）：灰度期用 NEGOTIATE 只记录不拒绝。
	MinClientVersionMode MinClientVersionMode `protobuf:"varint,7,opt,name=min_client_version_mode,json=minClientVersionMode,proto3,enum=atlas.configs.MinClientVersionMode" json:"min_client_version_mode,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_protobuf_configs_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *Runtime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Runtime) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Runtime) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Runtime) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *Runtime) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Runtime) GetMinClientVersion() string {
	if x != nil {
		return x.MinClientVersion
	}
	return ""
}

func (x *Runtime) GetMinClientVersionMode() MinClientVersionMode {
	if x != nil {
		return x.MinClientVersionMode
	}
	return MinClientVersionMode_MIN_CLIENT_VERSION_MODE_OFF
}

var File_protobuf_configs_runtime_proto protoreflect.FileDescriptor

const file_protobuf_configs_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1eprotobuf/configs/runtime.proto\x12\ratlas.configs\"\x81\x02\n" +
	"\aRuntime\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x10\n" +
	"\x03env\x18\x04 \x01(\tR\x03env\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12,\n" +
	"\x12min_client_version\x18\x06 \x01(\tR\x10minClientVersion\x12Z\n" +
	"\x17min_client_version_mode\x18\a \x01(\x0e2#.atlas.configs.MinClientVersionModeR\x14minClientVersionMode*\x83\x01\n" +
	"\x14MinClientVersionMode\x12\x1f\n" +
	"\x1bMIN_CLIENT_VERSION_MODE_OFF\x10\x00\x12%\n" +
	"!MIN_CLIENT_VERSION_MODE_NEGOTIATE\x10\x01\x12#\n" +
	"\x1fMIN_CLIENT_VERSION_MODE_ENFORCE\x10\x02BAZ?github.com/huangyuCN/atlas-game-layout/protobuf/configs;configsb\x06proto3"

var (
	file_protobuf_configs_runtime_proto_rawDescOnce sync.Once
	file_protobuf_configs_runtime_proto_rawDescData []byte
)

func file_protobuf_configs_runtime_proto_rawDescGZIP() []byte {
	file_protobuf_configs_runtime_proto_rawDescOnce.Do(func() {
		file_protobuf_configs_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_configs_runtime_proto_rawDesc), len(file_protobuf_configs_runtime_proto_rawDesc)))
	})
	return file_protobuf_configs_runtime_proto_rawDescData
}

var file_protobuf_configs_runtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_configs_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_configs_runtime_proto_goTypes = []any{
	(MinClientVersionMode)(0), // 0: atlas.configs.MinClientVersionMode
	(*Runtime)(nil),           // 1: atlas.configs.Runtime
}
var file_protobuf_configs_runtime_proto_depIdxs = []int32{
	0, // 0: atlas.configs.Runtime.min_client_version_mode:type_name -> atlas.configs.MinClientVersionMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_configs_runtime_proto_init() }
func file_protobuf_configs_runtime_proto_init() {
	if File_protobuf_configs_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_configs_runtime_proto_rawDesc), len(file_protobuf_configs_runtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_configs_runtime_proto_goTypes,
		DependencyIndexes: file_protobuf_configs_runtime_proto_depIdxs,
		EnumInfos:         file_protobuf_configs_runtime_proto_enumTypes,
		MessageInfos:      file_protobuf_configs_runtime_proto_msgTypes,
	}.Build()
	File_protobuf_configs_runtime_proto = out.File
	file_protobuf_configs_runtime_proto_goTypes = nil
	file_protobuf_configs_runtime_proto_depIdxs = nil
}
