// 公共配置：传输层启动参数（gRPC 服务间调用、HTTP 健康/管理）。
//
// 空值约定：字符串为空、数值为 0、optional 字段未设置，一律表示「交给底层默认值，不覆盖」——
// 避免「不配就变行为」与「配了等于没配」。时长字段统一为字符串（time.ParseDuration，如 30s/1m），
// 解析失败在启动期直接报错。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.26.1
// source: protobuf/configs/server.proto

package configs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Network 是监听网络类型（语义有限值，故用枚举而非散落字符串）。
type Server_Network int32

const (
	// NETWORK_TCP 是 TCP（缺省，IPv4/IPv6 均可）。
	Server_NETWORK_TCP Server_Network = 0
	// NETWORK_TCP4 是仅 IPv4 的 TCP。
	Server_NETWORK_TCP4 Server_Network = 1
	// NETWORK_TCP6 是仅 IPv6 的 TCP。
	Server_NETWORK_TCP6 Server_Network = 2
	// NETWORK_UNIX 是 Unix 域套接字（addr 写套接字路径）。
	Server_NETWORK_UNIX Server_Network = 3
)

// Enum value maps for Server_Network.
var (
	Server_Network_name = map[int32]string{
		0: "NETWORK_TCP",
		1: "NETWORK_TCP4",
		2: "NETWORK_TCP6",
		3: "NETWORK_UNIX",
	}
	Server_Network_value = map[string]int32{
		"NETWORK_TCP":  0,
		"NETWORK_TCP4": 1,
		"NETWORK_TCP6": 2,
		"NETWORK_UNIX": 3,
	}
)

func (x Server_Network) Enum() *Server_Network {
	p := new(Server_Network)
	*p = x
	return p
}

func (x Server_Network) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Server_Network) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_configs_server_proto_enumTypes[0].Descriptor()
}

func (Server_Network) Type() protoreflect.EnumType {
	return &file_protobuf_configs_server_proto_enumTypes[0]
}

func (x Server_Network) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Server_Network.Descriptor instead.
func (Server_Network) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_configs_server_proto_rawDescGZIP(), []int{0, 0}
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Http          *Server_HTTP           `protobuf:"bytes,2,opt,name=http,proto3" json:"http,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_protobuf_configs_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_server_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetHttp() *Server_HTTP {
	if x != nil {
		return x.Http
	}
	return nil
}

// TLS 是传输层 TLS 配置（HTTP/gRPC 共用；enabled=false 时忽略其余字段）。
type Server_TLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// enabled 为 true 时启用 TLS。
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// cert_file 是服务端证书链路径（PEM）。
	CertFile string `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	// key_file 是服务端私钥路径（PEM）。
	KeyFile string `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
	// ca_file 是客户端 CA 证书路径（PEM）；client_auth=true 时用于校验客户端。
	CaFile string `protobuf:"bytes,4,opt,name=ca_file,json=caFile,proto3" json:"ca_file,omitempty"`
	// client_auth 为 true 时要求并校验客户端证书（mTLS）。
	ClientAuth    bool `protobuf:"varint,5,opt,name=client_auth,json=clientAuth,proto3" json:"client_auth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_TLS) Reset() {
	*x = Server_TLS{}
	mi := &file_protobuf_configs_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_TLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_TLS) ProtoMessage() {}

func (x *Server_TLS) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_TLS.ProtoReflect.Descriptor instead.
func (*Server_TLS) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_server_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Server_TLS) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Server_TLS) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *Server_TLS) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

func (x *Server_TLS) GetCaFile() string {
	if x != nil {
		return x.CaFile
	}
	return ""
}

func (x *Server_TLS) GetClientAuth() bool {
	if x != nil {
		return x.ClientAuth
	}
	return false
}

type Server_GRPC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network 是网络类型；未设置 = 底层默认 tcp。
	Network *Server_Network `protobuf:"varint,1,opt,name=network,proto3,enum=atlas.configs.Server_Network,oneof" json:"network,omitempty"`
	// addr 是监听地址 host:port；空 = 随机端口。
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// timeout 是单次 RPC 超时（如 1s）；空 = 底层默认。
	Timeout string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// stream_timeout 是流式 RPC 超时；空或 0 = 不限制。
	StreamTimeout string `protobuf:"bytes,4,opt,name=stream_timeout,json=streamTimeout,proto3" json:"stream_timeout,omitempty"`
	// max_recv_msg_size 是单条消息接收上限（字节）；0 = 底层默认。
	MaxRecvMsgSize int32 `protobuf:"varint,5,opt,name=max_recv_msg_size,json=maxRecvMsgSize,proto3" json:"max_recv_msg_size,omitempty"`
	// reflection 是否开启 gRPC reflection（底层默认关闭；仅调试/测试环境建议开启）。
	Reflection bool `protobuf:"varint,6,opt,name=reflection,proto3" json:"reflection,omitempty"`
	// metadata 是否注册 metadata 服务。
	Metadata bool `protobuf:"varint,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// admin 是否注册 admin 服务。
	Admin bool `protobuf:"varint,8,opt,name=admin,proto3" json:"admin,omitempty"`
	// tls 是 TLS 配置；不配 = 明文。
	Tls           *Server_TLS `protobuf:"bytes,9,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_protobuf_configs_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_server_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Server_GRPC) GetNetwork() Server_Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return Server_NETWORK_TCP
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Server_GRPC) GetStreamTimeout() string {
	if x != nil {
		return x.StreamTimeout
	}
	return ""
}

func (x *Server_GRPC) GetMaxRecvMsgSize() int32 {
	if x != nil {
		return x.MaxRecvMsgSize
	}
	return 0
}

func (x *Server_GRPC) GetReflection() bool {
	if x != nil {
		return x.Reflection
	}
	return false
}

func (x *Server_GRPC) GetMetadata() bool {
	if x != nil {
		return x.Metadata
	}
	return false
}

func (x *Server_GRPC) GetAdmin() bool {
	if x != nil {
		return x.Admin
	}
	return false
}

func (x *Server_GRPC) GetTls() *Server_TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

type Server_HTTP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// network 是网络类型；未设置 = 底层默认 tcp。
	Network *Server_Network `protobuf:"varint,1,opt,name=network,proto3,enum=atlas.configs.Server_Network,oneof" json:"network,omitempty"`
	// addr 是监听地址 host:port；空 = 随机端口。
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	// timeout 是单次请求 handler 的总执行时间（如 30s）；空 = 底层默认。
	Timeout string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// path_prefix 是路由前缀；空 = 无前缀。
	PathPrefix string `protobuf:"bytes,4,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// strict_slash 是否严格斜杠（底层默认 true）；未设置时保持底层默认。
	StrictSlash *bool `protobuf:"varint,5,opt,name=strict_slash,json=strictSlash,proto3,oneof" json:"strict_slash,omitempty"`
	// max_request_body 是请求体上限（字节）；0 = 底层默认。
	MaxRequestBody int64 `protobuf:"varint,6,opt,name=max_request_body,json=maxRequestBody,proto3" json:"max_request_body,omitempty"`
	// tls 是 TLS 配置；不配 = 明文。
	Tls           *Server_TLS `protobuf:"bytes,7,opt,name=tls,proto3" json:"tls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_HTTP) Reset() {
	*x = Server_HTTP{}
	mi := &file_protobuf_configs_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_HTTP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_HTTP) ProtoMessage() {}

func (x *Server_HTTP) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_configs_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_HTTP.ProtoReflect.Descriptor instead.
func (*Server_HTTP) Descriptor() ([]byte, []int) {
	return file_protobuf_configs_server_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Server_HTTP) GetNetwork() Server_Network {
	if x != nil && x.Network != nil {
		return *x.Network
	}
	return Server_NETWORK_TCP
}

func (x *Server_HTTP) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_HTTP) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *Server_HTTP) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *Server_HTTP) GetStrictSlash() bool {
	if x != nil && x.StrictSlash != nil {
		return *x.StrictSlash
	}
	return false
}

func (x *Server_HTTP) GetMaxRequestBody() int64 {
	if x != nil {
		return x.MaxRequestBody
	}
	return 0
}

func (x *Server_HTTP) GetTls() *Server_TLS {
	if x != nil {
		return x.Tls
	}
	return nil
}

var File_protobuf_configs_server_proto protoreflect.FileDescriptor

const file_protobuf_configs_server_proto_rawDesc = "" +
	"\n" +
	"\x1dprotobuf/configs/server.proto\x12\ratlas.configs\"\xd2\a\n" +
	"\x06Server\x12.\n" +
	"\x04grpc\x18\x01 \x01(\v2\x1a.atlas.configs.Server.GRPCR\x04grpc\x12.\n" +
	"\x04http\x18\x02 \x01(\v2\x1a.atlas.configs.Server.HTTPR\x04http\x1a\x91\x01\n" +
	"\x03TLS\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tcert_file\x18\x02 \x01(\tR\bcertFile\x12\x19\n" +
	"\bkey_file\x18\x03 \x01(\tR\akeyFile\x12\x17\n" +
	"\aca_file\x18\x04 \x01(\tR\x06caFile\x12\x1f\n" +
	"\vclient_auth\x18\x05 \x01(\bR\n" +
	"clientAuth\x1a\xcf\x02\n" +
	"\x04GRPC\x12<\n" +
	"\anetwork\x18\x01 \x01(\x0e2\x1d.atlas.configs.Server.NetworkH\x00R\anetwork\x88\x01\x01\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\x12%\n" +
	"\x0estream_timeout\x18\x04 \x01(\tR\rstreamTimeout\x12)\n" +
	"\x11max_recv_msg_size\x18\x05 \x01(\x05R\x0emaxRecvMsgSize\x12\x1e\n" +
	"\n" +
	"reflection\x18\x06 \x01(\bR\n" +
	"reflection\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\bR\bmetadata\x12\x14\n" +
	"\x05admin\x18\b \x01(\bR\x05admin\x12+\n" +
	"\x03tls\x18\t \x01(\v2\x19.atlas.configs.Server.TLSR\x03tlsB\n" +
	"\n" +
	"\b_network\x1a\xaf\x02\n" +
	"\x04HTTP\x12<\n" +
	"\anetwork\x18\x01 \x01(\x0e2\x1d.atlas.configs.Server.NetworkH\x00R\anetwork\x88\x01\x01\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\x12\x1f\n" +
	"\vpath_prefix\x18\x04 \x01(\tR\n" +
	"pathPrefix\x12&\n" +
	"\fstrict_slash\x18\x05 \x01(\bH\x01R\vstrictSlash\x88\x01\x01\x12(\n" +
	"\x10max_request_body\x18\x06 \x01(\x03R\x0emaxRequestBody\x12+\n" +
	"\x03tls\x18\a \x01(\v2\x19.atlas.configs.Server.TLSR\x03tlsB\n" +
	"\n" +
	"\b_networkB\x0f\n" +
	"\r_strict_slash\"P\n" +
	"\aNetwork\x12\x0f\n" +
	"\vNETWORK_TCP\x10\x00\x12\x10\n" +
	"\fNETWORK_TCP4\x10\x01\x12\x10\n" +
	"\fNETWORK_TCP6\x10\x02\x12\x10\n" +
	"\fNETWORK_UNIX\x10\x03BAZ?github.com/huangyuCN/atlas-game-layout/protobuf/configs;configsb\x06proto3"

var (
	file_protobuf_configs_server_proto_rawDescOnce sync.Once
	file_protobuf_configs_server_proto_rawDescData []byte
)

func file_protobuf_configs_server_proto_rawDescGZIP() []byte {
	file_protobuf_configs_server_proto_rawDescOnce.Do(func() {
		file_protobuf_configs_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_configs_server_proto_rawDesc), len(file_protobuf_configs_server_proto_rawDesc)))
	})
	return file_protobuf_configs_server_proto_rawDescData
}

var file_protobuf_configs_server_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_configs_server_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_configs_server_proto_goTypes = []any{
	(Server_Network)(0), // 0: atlas.configs.Server.Network
	(*Server)(nil),      // 1: atlas.configs.Server
	(*Server_TLS)(nil),  // 2: atlas.configs.Server.TLS
	(*Server_GRPC)(nil), // 3: atlas.configs.Server.GRPC
	(*Server_HTTP)(nil), // 4: atlas.configs.Server.HTTP
}
var file_protobuf_configs_server_proto_depIdxs = []int32{
	3, // 0: atlas.configs.Server.grpc:type_name -> atlas.configs.Server.GRPC
	4, // 1: atlas.configs.Server.http:type_name -> atlas.configs.Server.HTTP
	0, // 2: atlas.configs.Server.GRPC.network:type_name -> atlas.configs.Server.Network
	2, // 3: atlas.configs.Server.GRPC.tls:type_name -> atlas.configs.Server.TLS
	0, // 4: atlas.configs.Server.HTTP.network:type_name -> atlas.configs.Server.Network
	2, // 5: atlas.configs.Server.HTTP.tls:type_name -> atlas.configs.Server.TLS
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_configs_server_proto_init() }
func file_protobuf_configs_server_proto_init() {
	if File_protobuf_configs_server_proto != nil {
		return
	}
	file_protobuf_configs_server_proto_msgTypes[2].OneofWrappers = []any{}
	file_protobuf_configs_server_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_configs_server_proto_rawDesc), len(file_protobuf_configs_server_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_configs_server_proto_goTypes,
		DependencyIndexes: file_protobuf_configs_server_proto_depIdxs,
		EnumInfos:         file_protobuf_configs_server_proto_enumTypes,
		MessageInfos:      file_protobuf_configs_server_proto_msgTypes,
	}.Build()
	File_protobuf_configs_server_proto = out.File
	file_protobuf_configs_server_proto_goTypes = nil
	file_protobuf_configs_server_proto_depIdxs = nil
}
