// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/game/v1/player_service.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。

import type { PlayerSummary } from "../../common/v1/common_pb.js";
import type { MatchFailReason, PartyRosterReason } from "../../matcher/v1/match_events_pb.js";
import type { MatchState } from "../../matcher/v1/matcher_pb.js";
import type { BackpackItem } from "./player_pb.js";
import type { Invoker, InvokeOption } from '@huangyucn/atlas-sdk-ts';

export interface RegisterReq {
  account?: string; // game.v1.RegisterReq.account
  password?: string; // game.v1.RegisterReq.password
  nickname?: string; // game.v1.RegisterReq.nickname
}

export interface RegisterReply {
  playerId?: string; // game.v1.RegisterReply.player_id
  player?: PlayerSummary; // game.v1.RegisterReply.player
}

export interface LoginReq {
  playerId?: string; // game.v1.LoginReq.player_id
  password?: string; // game.v1.LoginReq.password
  token?: string; // game.v1.LoginReq.token
  gatewayInstance?: string; // game.v1.LoginReq.gateway_instance
}

export interface LoginReply {
  player?: PlayerSummary; // game.v1.LoginReply.player
}

export interface LogoutMsg {
  reason?: LogoutReason; // game.v1.LogoutMsg.reason
}

export interface GetPlayerDataReq {
}

export interface GetBackpackReq {
}

export interface PlayerDataReply {
  player?: PlayerSummary; // game.v1.PlayerDataReply.player
  items?: BackpackItem[]; // game.v1.PlayerDataReply.items
}

export interface BackpackReply {
  items?: BackpackItem[]; // game.v1.BackpackReply.items
}

export interface GrantItemReq {
  itemId?: number; // game.v1.GrantItemReq.item_id
  count?: number; // game.v1.GrantItemReq.count
  reason?: string; // game.v1.GrantItemReq.reason
}

export interface GetPlayerReq {
}

export interface PlayerReply {
  player?: PlayerSummary; // game.v1.PlayerReply.player
}

export interface EnterMatchQueueReq {
  ruleset?: string; // game.v1.EnterMatchQueueReq.ruleset
}

export interface EnterMatchQueueReply {
}

export interface CancelMatchReq {
}

export interface CancelMatchReply {
  canceled?: boolean; // game.v1.CancelMatchReply.canceled
}

export interface GetMatchStatusReq {
}

export interface MatchStatusReply {
  state?: MatchState; // game.v1.MatchStatusReply.state
  ticketId?: string; // game.v1.MatchStatusReply.ticket_id
  matchId?: string; // game.v1.MatchStatusReply.match_id
  battleId?: string; // game.v1.MatchStatusReply.battle_id
}

export interface CreatePartyReq {
}

export interface JoinPartyReq {
  partyId?: string; // game.v1.JoinPartyReq.party_id
}

export interface LeavePartyReq {
}

export interface GetPartyReq {
}

export interface PartyReply {
  partyId?: string; // game.v1.PartyReply.party_id
  leaderId?: string; // game.v1.PartyReply.leader_id
  members?: PlayerSummary[]; // game.v1.PartyReply.members
}

export interface QueuePartyReq {
  ruleset?: string; // game.v1.QueuePartyReq.ruleset
}

export interface PartyQueueReply {
  ticketId?: string; // game.v1.PartyQueueReply.ticket_id
}

export interface MatchStartedNotify {
  matchId?: string; // game.v1.MatchStartedNotify.match_id
  battleId?: string; // game.v1.MatchStartedNotify.battle_id
  playerIds?: string[]; // game.v1.MatchStartedNotify.player_ids
  endpoint?: string; // game.v1.MatchStartedNotify.endpoint
}

export interface MatchFailedNotify {
  ticketId?: string; // game.v1.MatchFailedNotify.ticket_id
  reason?: MatchFailReason; // game.v1.MatchFailedNotify.reason
}

export interface PartyRosterNotify {
  partyId?: string; // game.v1.PartyRosterNotify.party_id
  leaderId?: string; // game.v1.PartyRosterNotify.leader_id
  playerIds?: string[]; // game.v1.PartyRosterNotify.player_ids
  reason?: PartyRosterReason; // game.v1.PartyRosterNotify.reason
}

export type LogoutReason = "LOGOUT_REASON_UNSPECIFIED" | "LOGOUT_REASON_LOGOUT" | "LOGOUT_REASON_LOGGED_IN_ELSEWHERE" | "LOGOUT_REASON_SESSION_EXPIRED";

export class PlayerServiceOpClient {
  constructor(private readonly inv: Invoker) {}

  /** /game.v1.PlayerService/Register：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async register(req: RegisterReq | null, ...opts: InvokeOption[]): Promise<RegisterReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/Register', req ?? {}, ...opts);
    return out as RegisterReply;
  }
  /** /game.v1.PlayerService/GetPlayerData：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async getPlayerData(req: GetPlayerDataReq | null, ...opts: InvokeOption[]): Promise<PlayerDataReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/GetPlayerData', req ?? {}, ...opts);
    return out as PlayerDataReply;
  }
  /** /game.v1.PlayerService/GetBackpack：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async getBackpack(req: GetBackpackReq | null, ...opts: InvokeOption[]): Promise<BackpackReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/GetBackpack', req ?? {}, ...opts);
    return out as BackpackReply;
  }
  /** /game.v1.PlayerService/EnterMatchQueue：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async enterMatchQueue(req: EnterMatchQueueReq | null, ...opts: InvokeOption[]): Promise<EnterMatchQueueReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/EnterMatchQueue', req ?? {}, ...opts);
    return out as EnterMatchQueueReply;
  }
  /** /game.v1.PlayerService/CancelMatch：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async cancelMatch(req: CancelMatchReq | null, ...opts: InvokeOption[]): Promise<CancelMatchReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/CancelMatch', req ?? {}, ...opts);
    return out as CancelMatchReply;
  }
  /** /game.v1.PlayerService/GetMatchStatus：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async getMatchStatus(req: GetMatchStatusReq | null, ...opts: InvokeOption[]): Promise<MatchStatusReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/GetMatchStatus', req ?? {}, ...opts);
    return out as MatchStatusReply;
  }
  /** /game.v1.PlayerService/CreateParty：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async createParty(req: CreatePartyReq | null, ...opts: InvokeOption[]): Promise<PartyReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/CreateParty', req ?? {}, ...opts);
    return out as PartyReply;
  }
  /** /game.v1.PlayerService/JoinParty：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async joinParty(req: JoinPartyReq | null, ...opts: InvokeOption[]): Promise<PartyReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/JoinParty', req ?? {}, ...opts);
    return out as PartyReply;
  }
  /** /game.v1.PlayerService/LeaveParty：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async leaveParty(req: LeavePartyReq | null, ...opts: InvokeOption[]): Promise<PartyReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/LeaveParty', req ?? {}, ...opts);
    return out as PartyReply;
  }
  /** /game.v1.PlayerService/GetParty：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async getParty(req: GetPartyReq | null, ...opts: InvokeOption[]): Promise<PartyReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/GetParty', req ?? {}, ...opts);
    return out as PartyReply;
  }
  /** /game.v1.PlayerService/QueueParty：请求-响应；业务拒绝抛 BusinessError（Reason 为主键）。 */
  async queueParty(req: QueuePartyReq | null, ...opts: InvokeOption[]): Promise<PartyQueueReply> {
    const out = await this.inv.invoke('/game.v1.PlayerService/QueueParty', req ?? {}, ...opts);
    return out as PartyQueueReply;
  }
}

