runtime:
  name: battle
  id: battle-1
registry:
  etcd:
    endpoints:
      - 127.0.0.1:12379
server:
  grpc:
    addr: 0.0.0.0:9300
  http:
    addr: 0.0.0.0:9380
data:
  redis:
    addr: 127.0.0.1:16379
  nats:
    url: nats://127.0.0.1:14222
  mongo:
    uri: mongodb://127.0.0.1:27017
    database: battle
log:
  level: info
  format: text
