# battle 配置：帧同步战斗服务
name: battle
id: battle-1
grpc:
  addr: 0.0.0.0:9300
http:
  addr: 0.0.0.0:9380
etcd:
  endpoints:
    - 127.0.0.1:12379
mongo:
  uri: mongodb://127.0.0.1:27017
  database: battle
redis:
  addr: 127.0.0.1:16379
nats:
  url: nats://127.0.0.1:14222
log:
  level: info
