// matcher 服务协议：入队/取消（game 玩家 actor 经 grpc 调用）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/matcher/v1/matcher.proto

package matcherv1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueMatchRequest 入队：玩家属性快照 ticket（纯撮合，matcher 不查库）。
type QueueMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Ruleset       string                 `protobuf:"bytes,3,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMatchRequest) Reset() {
	*x = QueueMatchRequest{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMatchRequest) ProtoMessage() {}

func (x *QueueMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMatchRequest.ProtoReflect.Descriptor instead.
func (*QueueMatchRequest) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{0}
}

func (x *QueueMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *QueueMatchRequest) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *QueueMatchRequest) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

// QueueMatchReply 入队回执：ticket_id 用于取消/查询与事件关联。
type QueueMatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMatchReply) Reset() {
	*x = QueueMatchReply{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMatchReply) ProtoMessage() {}

func (x *QueueMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMatchReply.ProtoReflect.Descriptor instead.
func (*QueueMatchReply) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *QueueMatchReply) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

type CancelMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequest) Reset() {
	*x = CancelMatchRequest{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequest) ProtoMessage() {}

func (x *CancelMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequest) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{2}
}

func (x *CancelMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type CancelMatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canceled      bool                   `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchReply) Reset() {
	*x = CancelMatchReply{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReply) ProtoMessage() {}

func (x *CancelMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReply.ProtoReflect.Descriptor instead.
func (*CancelMatchReply) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{3}
}

func (x *CancelMatchReply) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

// QueryMatchRequest 查询玩家当前匹配状态。
type QueryMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMatchRequest) Reset() {
	*x = QueryMatchRequest{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMatchRequest) ProtoMessage() {}

func (x *QueryMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMatchRequest.ProtoReflect.Descriptor instead.
func (*QueryMatchRequest) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{4}
}

func (x *QueryMatchRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

// QueryMatchReply 匹配状态：waiting（排队中）/matched（已成局）/failed（失败）/none（无匹配）。
type QueryMatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryMatchReply) Reset() {
	*x = QueryMatchReply{}
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMatchReply) ProtoMessage() {}

func (x *QueryMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_matcher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMatchReply.ProtoReflect.Descriptor instead.
func (*QueryMatchReply) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_matcher_proto_rawDescGZIP(), []int{5}
}

func (x *QueryMatchReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *QueryMatchReply) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *QueryMatchReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

var File_api_matcher_v1_matcher_proto protoreflect.FileDescriptor

const file_api_matcher_v1_matcher_proto_rawDesc = "" +
	"\n" +
	"\x1capi/matcher/v1/matcher.proto\x12\n" +
	"matcher.v1\x1a\x1aapi/common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"|\n" +
	"\x11QueueMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x120\n" +
	"\x06player\x18\x02 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\x12\x18\n" +
	"\aruleset\x18\x03 \x01(\tR\aruleset\".\n" +
	"\x0fQueueMatchReply\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"1\n" +
	"\x12CancelMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\".\n" +
	"\x10CancelMatchReply\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\"0\n" +
	"\x11QueryMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"_\n" +
	"\x0fQueryMatchReply\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId2\xce\x02\n" +
	"\aMatcher\x12f\n" +
	"\n" +
	"QueueMatch\x12\x1d.matcher.v1.QueueMatchRequest\x1a\x1b.matcher.v1.QueueMatchReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/matcher/queue\x12j\n" +
	"\vCancelMatch\x12\x1e.matcher.v1.CancelMatchRequest\x1a\x1c.matcher.v1.CancelMatchReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/matcher/cancel\x12o\n" +
	"\n" +
	"QueryMatch\x12\x1d.matcher.v1.QueryMatchRequest\x1a\x1b.matcher.v1.QueryMatchReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/matcher/query/{player_id}BAZ?github.com/huangyuCN/atlas-game-layout/api/matcher/v1;matcherv1b\x06proto3"

var (
	file_api_matcher_v1_matcher_proto_rawDescOnce sync.Once
	file_api_matcher_v1_matcher_proto_rawDescData []byte
)

func file_api_matcher_v1_matcher_proto_rawDescGZIP() []byte {
	file_api_matcher_v1_matcher_proto_rawDescOnce.Do(func() {
		file_api_matcher_v1_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_matcher_v1_matcher_proto_rawDesc), len(file_api_matcher_v1_matcher_proto_rawDesc)))
	})
	return file_api_matcher_v1_matcher_proto_rawDescData
}

var file_api_matcher_v1_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_matcher_v1_matcher_proto_goTypes = []any{
	(*QueueMatchRequest)(nil),  // 0: matcher.v1.QueueMatchRequest
	(*QueueMatchReply)(nil),    // 1: matcher.v1.QueueMatchReply
	(*CancelMatchRequest)(nil), // 2: matcher.v1.CancelMatchRequest
	(*CancelMatchReply)(nil),   // 3: matcher.v1.CancelMatchReply
	(*QueryMatchRequest)(nil),  // 4: matcher.v1.QueryMatchRequest
	(*QueryMatchReply)(nil),    // 5: matcher.v1.QueryMatchReply
	(*v1.PlayerSummary)(nil),   // 6: common.v1.PlayerSummary
}
var file_api_matcher_v1_matcher_proto_depIdxs = []int32{
	6, // 0: matcher.v1.QueueMatchRequest.player:type_name -> common.v1.PlayerSummary
	0, // 1: matcher.v1.Matcher.QueueMatch:input_type -> matcher.v1.QueueMatchRequest
	2, // 2: matcher.v1.Matcher.CancelMatch:input_type -> matcher.v1.CancelMatchRequest
	4, // 3: matcher.v1.Matcher.QueryMatch:input_type -> matcher.v1.QueryMatchRequest
	1, // 4: matcher.v1.Matcher.QueueMatch:output_type -> matcher.v1.QueueMatchReply
	3, // 5: matcher.v1.Matcher.CancelMatch:output_type -> matcher.v1.CancelMatchReply
	5, // 6: matcher.v1.Matcher.QueryMatch:output_type -> matcher.v1.QueryMatchReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_matcher_v1_matcher_proto_init() }
func file_api_matcher_v1_matcher_proto_init() {
	if File_api_matcher_v1_matcher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_matcher_v1_matcher_proto_rawDesc), len(file_api_matcher_v1_matcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_matcher_v1_matcher_proto_goTypes,
		DependencyIndexes: file_api_matcher_v1_matcher_proto_depIdxs,
		MessageInfos:      file_api_matcher_v1_matcher_proto_msgTypes,
	}.Build()
	File_api_matcher_v1_matcher_proto = out.File
	file_api_matcher_v1_matcher_proto_goTypes = nil
	file_api_matcher_v1_matcher_proto_depIdxs = nil
}
