// 匹配事件（nats 事件总线消息，无 service）：
// 成局/失败事件由 matcher 发布，gateway（推送）与 game（状态回写）订阅。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/matcher/v1/match_events.proto

package matcherv1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/battle/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MatchFailReason 是匹配失败原因（客户端可读枚举，对齐状态机终态与处置来源）。
type MatchFailReason int32

const (
	MatchFailReason_MATCH_FAIL_REASON_UNSPECIFIED       MatchFailReason = 0
	MatchFailReason_MATCH_FAIL_REASON_TIMEOUT           MatchFailReason = 1 // 玩家请求/接受超时（匹配未成立）
	MatchFailReason_MATCH_FAIL_REASON_CANCELLED         MatchFailReason = 2 // 玩家主动取消
	MatchFailReason_MATCH_FAIL_REASON_ACCEPTANCE_FAILED MatchFailReason = 3 // 接受阶段失败
	MatchFailReason_MATCH_FAIL_REASON_PLACEMENT_FAILED  MatchFailReason = 4 // 对局实例分配失败
	MatchFailReason_MATCH_FAIL_REASON_FAILED            MatchFailReason = 5 // 其他失败
)

// Enum value maps for MatchFailReason.
var (
	MatchFailReason_name = map[int32]string{
		0: "MATCH_FAIL_REASON_UNSPECIFIED",
		1: "MATCH_FAIL_REASON_TIMEOUT",
		2: "MATCH_FAIL_REASON_CANCELLED",
		3: "MATCH_FAIL_REASON_ACCEPTANCE_FAILED",
		4: "MATCH_FAIL_REASON_PLACEMENT_FAILED",
		5: "MATCH_FAIL_REASON_FAILED",
	}
	MatchFailReason_value = map[string]int32{
		"MATCH_FAIL_REASON_UNSPECIFIED":       0,
		"MATCH_FAIL_REASON_TIMEOUT":           1,
		"MATCH_FAIL_REASON_CANCELLED":         2,
		"MATCH_FAIL_REASON_ACCEPTANCE_FAILED": 3,
		"MATCH_FAIL_REASON_PLACEMENT_FAILED":  4,
		"MATCH_FAIL_REASON_FAILED":            5,
	}
)

func (x MatchFailReason) Enum() *MatchFailReason {
	p := new(MatchFailReason)
	*p = x
	return p
}

func (x MatchFailReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchFailReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_matcher_v1_match_events_proto_enumTypes[0].Descriptor()
}

func (MatchFailReason) Type() protoreflect.EnumType {
	return &file_api_matcher_v1_match_events_proto_enumTypes[0]
}

func (x MatchFailReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchFailReason.Descriptor instead.
func (MatchFailReason) EnumDescriptor() ([]byte, []int) {
	return file_api_matcher_v1_match_events_proto_rawDescGZIP(), []int{0}
}

// PartyRosterReason 是队伍名册变更原因。
type PartyRosterReason int32

const (
	PartyRosterReason_PARTY_ROSTER_REASON_UNSPECIFIED PartyRosterReason = 0
	PartyRosterReason_PARTY_ROSTER_REASON_CREATED     PartyRosterReason = 1 // 建队
	PartyRosterReason_PARTY_ROSTER_REASON_JOIN        PartyRosterReason = 2 // 成员加入
	PartyRosterReason_PARTY_ROSTER_REASON_LEAVE       PartyRosterReason = 3 // 成员离开
	PartyRosterReason_PARTY_ROSTER_REASON_DISSOLVE    PartyRosterReason = 4 // 队伍解散（名册清空）
)

// Enum value maps for PartyRosterReason.
var (
	PartyRosterReason_name = map[int32]string{
		0: "PARTY_ROSTER_REASON_UNSPECIFIED",
		1: "PARTY_ROSTER_REASON_CREATED",
		2: "PARTY_ROSTER_REASON_JOIN",
		3: "PARTY_ROSTER_REASON_LEAVE",
		4: "PARTY_ROSTER_REASON_DISSOLVE",
	}
	PartyRosterReason_value = map[string]int32{
		"PARTY_ROSTER_REASON_UNSPECIFIED": 0,
		"PARTY_ROSTER_REASON_CREATED":     1,
		"PARTY_ROSTER_REASON_JOIN":        2,
		"PARTY_ROSTER_REASON_LEAVE":       3,
		"PARTY_ROSTER_REASON_DISSOLVE":    4,
	}
)

func (x PartyRosterReason) Enum() *PartyRosterReason {
	p := new(PartyRosterReason)
	*p = x
	return p
}

func (x PartyRosterReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartyRosterReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_matcher_v1_match_events_proto_enumTypes[1].Descriptor()
}

func (PartyRosterReason) Type() protoreflect.EnumType {
	return &file_api_matcher_v1_match_events_proto_enumTypes[1]
}

func (x PartyRosterReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartyRosterReason.Descriptor instead.
func (PartyRosterReason) EnumDescriptor() ([]byte, []int) {
	return file_api_matcher_v1_match_events_proto_rawDescGZIP(), []int{1}
}

// MatchStartedEvent 匹配成功（battle 已创建）。
type MatchStartedEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	MatchId   string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	BattleId  string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerIds []string               `protobuf:"bytes,3,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	// battle_tickets 是按人签发的入场票据名单（复用 battle 域的 BattleTicketEntry，
	// 不另定义同形消息）；消费方扇出通知时按人取自己那张填入 battle_ticket。
	BattleTickets []*v1.BattleTicketEntry `protobuf:"bytes,5,rep,name=battle_tickets,json=battleTickets,proto3" json:"battle_tickets,omitempty"`
	// battle_endpoints 是接入层「传输面 → 地址」列表（来源是 battle 配置 edge_endpoints，
	// matcher 只搬运；对所有人相同）。消费方按自身传输面取一个，缺该面即明确报错。
	BattleEndpoints []*v1.EdgeEndpoint `protobuf:"bytes,6,rep,name=battle_endpoints,json=battleEndpoints,proto3" json:"battle_endpoints,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchStartedEvent) Reset() {
	*x = MatchStartedEvent{}
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartedEvent) ProtoMessage() {}

func (x *MatchStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartedEvent.ProtoReflect.Descriptor instead.
func (*MatchStartedEvent) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_match_events_proto_rawDescGZIP(), []int{0}
}

func (x *MatchStartedEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchStartedEvent) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *MatchStartedEvent) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchStartedEvent) GetBattleTickets() []*v1.BattleTicketEntry {
	if x != nil {
		return x.BattleTickets
	}
	return nil
}

func (x *MatchStartedEvent) GetBattleEndpoints() []*v1.EdgeEndpoint {
	if x != nil {
		return x.BattleEndpoints
	}
	return nil
}

// MatchFailedEvent 匹配失败（超时/取消/异常）：单玩家 ticket 终态，
// 未成局故无对局 ID（match_id 留空）；ticket_id 是取消/查询/事件关联的键。
type MatchFailedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // 已成局的对局 ID（成局前失败为空）
	PlayerIds     []string               `protobuf:"bytes,2,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Reason        MatchFailReason        `protobuf:"varint,3,opt,name=reason,proto3,enum=matcher.v1.MatchFailReason" json:"reason,omitempty"`
	TicketId      string                 `protobuf:"bytes,4,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"` // 失败的票据 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFailedEvent) Reset() {
	*x = MatchFailedEvent{}
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFailedEvent) ProtoMessage() {}

func (x *MatchFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFailedEvent.ProtoReflect.Descriptor instead.
func (*MatchFailedEvent) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_match_events_proto_rawDescGZIP(), []int{1}
}

func (x *MatchFailedEvent) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchFailedEvent) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchFailedEvent) GetReason() MatchFailReason {
	if x != nil {
		return x.Reason
	}
	return MatchFailReason_MATCH_FAIL_REASON_UNSPECIFIED
}

func (x *MatchFailedEvent) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// PartyRosterEvent 队伍名册变更（建队/加入/离开/解散）：
// matcher 发布，gateway 向全队推送名册快照（PartyRosterNotify）。
type PartyRosterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,3,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Reason        PartyRosterReason      `protobuf:"varint,4,opt,name=reason,proto3,enum=matcher.v1.PartyRosterReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyRosterEvent) Reset() {
	*x = PartyRosterEvent{}
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyRosterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyRosterEvent) ProtoMessage() {}

func (x *PartyRosterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_matcher_v1_match_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyRosterEvent.ProtoReflect.Descriptor instead.
func (*PartyRosterEvent) Descriptor() ([]byte, []int) {
	return file_api_matcher_v1_match_events_proto_rawDescGZIP(), []int{2}
}

func (x *PartyRosterEvent) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyRosterEvent) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *PartyRosterEvent) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *PartyRosterEvent) GetReason() PartyRosterReason {
	if x != nil {
		return x.Reason
	}
	return PartyRosterReason_PARTY_ROSTER_REASON_UNSPECIFIED
}

var File_api_matcher_v1_match_events_proto protoreflect.FileDescriptor

const file_api_matcher_v1_match_events_proto_rawDesc = "" +
	"\n" +
	"!api/matcher/v1/match_events.proto\x12\n" +
	"matcher.v1\x1a\"api/battle/v1/battle_service.proto\"\xf9\x01\n" +
	"\x11MatchStartedEvent\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\tR\tplayerIds\x12C\n" +
	"\x0ebattle_tickets\x18\x05 \x03(\v2\x1c.battle.v1.BattleTicketEntryR\rbattleTickets\x12B\n" +
	"\x10battle_endpoints\x18\x06 \x03(\v2\x17.battle.v1.EdgeEndpointR\x0fbattleEndpointsJ\x04\b\x04\x10\x05\"\x9e\x01\n" +
	"\x10MatchFailedEvent\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\tR\tplayerIds\x123\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x1b.matcher.v1.MatchFailReasonR\x06reason\x12\x1b\n" +
	"\tticket_id\x18\x04 \x01(\tR\bticketId\"\xa0\x01\n" +
	"\x10PartyRosterEvent\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\tR\tplayerIds\x125\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1d.matcher.v1.PartyRosterReasonR\x06reason*\xe3\x01\n" +
	"\x0fMatchFailReason\x12!\n" +
	"\x1dMATCH_FAIL_REASON_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MATCH_FAIL_REASON_TIMEOUT\x10\x01\x12\x1f\n" +
	"\x1bMATCH_FAIL_REASON_CANCELLED\x10\x02\x12'\n" +
	"#MATCH_FAIL_REASON_ACCEPTANCE_FAILED\x10\x03\x12&\n" +
	"\"MATCH_FAIL_REASON_PLACEMENT_FAILED\x10\x04\x12\x1c\n" +
	"\x18MATCH_FAIL_REASON_FAILED\x10\x05*\xb8\x01\n" +
	"\x11PartyRosterReason\x12#\n" +
	"\x1fPARTY_ROSTER_REASON_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPARTY_ROSTER_REASON_CREATED\x10\x01\x12\x1c\n" +
	"\x18PARTY_ROSTER_REASON_JOIN\x10\x02\x12\x1d\n" +
	"\x19PARTY_ROSTER_REASON_LEAVE\x10\x03\x12 \n" +
	"\x1cPARTY_ROSTER_REASON_DISSOLVE\x10\x04BAZ?github.com/huangyuCN/atlas-game-layout/api/matcher/v1;matcherv1b\x06proto3"

var (
	file_api_matcher_v1_match_events_proto_rawDescOnce sync.Once
	file_api_matcher_v1_match_events_proto_rawDescData []byte
)

func file_api_matcher_v1_match_events_proto_rawDescGZIP() []byte {
	file_api_matcher_v1_match_events_proto_rawDescOnce.Do(func() {
		file_api_matcher_v1_match_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_matcher_v1_match_events_proto_rawDesc), len(file_api_matcher_v1_match_events_proto_rawDesc)))
	})
	return file_api_matcher_v1_match_events_proto_rawDescData
}

var file_api_matcher_v1_match_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_matcher_v1_match_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_matcher_v1_match_events_proto_goTypes = []any{
	(MatchFailReason)(0),         // 0: matcher.v1.MatchFailReason
	(PartyRosterReason)(0),       // 1: matcher.v1.PartyRosterReason
	(*MatchStartedEvent)(nil),    // 2: matcher.v1.MatchStartedEvent
	(*MatchFailedEvent)(nil),     // 3: matcher.v1.MatchFailedEvent
	(*PartyRosterEvent)(nil),     // 4: matcher.v1.PartyRosterEvent
	(*v1.BattleTicketEntry)(nil), // 5: battle.v1.BattleTicketEntry
	(*v1.EdgeEndpoint)(nil),      // 6: battle.v1.EdgeEndpoint
}
var file_api_matcher_v1_match_events_proto_depIdxs = []int32{
	5, // 0: matcher.v1.MatchStartedEvent.battle_tickets:type_name -> battle.v1.BattleTicketEntry
	6, // 1: matcher.v1.MatchStartedEvent.battle_endpoints:type_name -> battle.v1.EdgeEndpoint
	0, // 2: matcher.v1.MatchFailedEvent.reason:type_name -> matcher.v1.MatchFailReason
	1, // 3: matcher.v1.PartyRosterEvent.reason:type_name -> matcher.v1.PartyRosterReason
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_matcher_v1_match_events_proto_init() }
func file_api_matcher_v1_match_events_proto_init() {
	if File_api_matcher_v1_match_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_matcher_v1_match_events_proto_rawDesc), len(file_api_matcher_v1_match_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_matcher_v1_match_events_proto_goTypes,
		DependencyIndexes: file_api_matcher_v1_match_events_proto_depIdxs,
		EnumInfos:         file_api_matcher_v1_match_events_proto_enumTypes,
		MessageInfos:      file_api_matcher_v1_match_events_proto_msgTypes,
	}.Build()
	File_api_matcher_v1_match_events_proto = out.File
	file_api_matcher_v1_match_events_proto_goTypes = nil
	file_api_matcher_v1_match_events_proto_depIdxs = nil
}
