// matcher 服务协议：入队/取消/查询。
// 调用方为 game 玩家 actor（服务端内部链路）：PlayerActor 用聚合根权威数据
// 组装 PlayerSummary（客户端不参与属性上报，反作弊前提），
// gateway 经集群转发客户端请求到 PlayerActor。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: api/matcher/v1/matcher.proto

package matcherv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Matcher_QueueMatch_FullMethodName  = "/matcher.v1.Matcher/QueueMatch"
	Matcher_CancelMatch_FullMethodName = "/matcher.v1.Matcher/CancelMatch"
	Matcher_QueryMatch_FullMethodName  = "/matcher.v1.Matcher/QueryMatch"
)

// MatcherClient is the client API for Matcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Matcher 是撮合服务。
type MatcherClient interface {
	QueueMatch(ctx context.Context, in *QueueMatchRequest, opts ...grpc.CallOption) (*QueueMatchReply, error)
	CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchReply, error)
	QueryMatch(ctx context.Context, in *QueryMatchRequest, opts ...grpc.CallOption) (*QueryMatchReply, error)
}

type matcherClient struct {
	cc grpc.ClientConnInterface
}

func NewMatcherClient(cc grpc.ClientConnInterface) MatcherClient {
	return &matcherClient{cc}
}

func (c *matcherClient) QueueMatch(ctx context.Context, in *QueueMatchRequest, opts ...grpc.CallOption) (*QueueMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueMatchReply)
	err := c.cc.Invoke(ctx, Matcher_QueueMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherClient) CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMatchReply)
	err := c.cc.Invoke(ctx, Matcher_CancelMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matcherClient) QueryMatch(ctx context.Context, in *QueryMatchRequest, opts ...grpc.CallOption) (*QueryMatchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMatchReply)
	err := c.cc.Invoke(ctx, Matcher_QueryMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatcherServer is the server API for Matcher service.
// All implementations must embed UnimplementedMatcherServer
// for forward compatibility.
//
// Matcher 是撮合服务。
type MatcherServer interface {
	QueueMatch(context.Context, *QueueMatchRequest) (*QueueMatchReply, error)
	CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchReply, error)
	QueryMatch(context.Context, *QueryMatchRequest) (*QueryMatchReply, error)
	mustEmbedUnimplementedMatcherServer()
}

// UnimplementedMatcherServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatcherServer struct{}

func (UnimplementedMatcherServer) QueueMatch(context.Context, *QueueMatchRequest) (*QueueMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueueMatch not implemented")
}
func (UnimplementedMatcherServer) CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedMatcherServer) QueryMatch(context.Context, *QueryMatchRequest) (*QueryMatchReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryMatch not implemented")
}
func (UnimplementedMatcherServer) mustEmbedUnimplementedMatcherServer() {}
func (UnimplementedMatcherServer) testEmbeddedByValue()                 {}

// UnsafeMatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatcherServer will
// result in compilation errors.
type UnsafeMatcherServer interface {
	mustEmbedUnimplementedMatcherServer()
}

func RegisterMatcherServer(s grpc.ServiceRegistrar, srv MatcherServer) {
	// If the following call panics, it indicates UnimplementedMatcherServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Matcher_ServiceDesc, srv)
}

func _Matcher_QueueMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServer).QueueMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matcher_QueueMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServer).QueueMatch(ctx, req.(*QueueMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matcher_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matcher_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServer).CancelMatch(ctx, req.(*CancelMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Matcher_QueryMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatcherServer).QueryMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Matcher_QueryMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatcherServer).QueryMatch(ctx, req.(*QueryMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Matcher_ServiceDesc is the grpc.ServiceDesc for Matcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Matcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matcher.v1.Matcher",
	HandlerType: (*MatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueueMatch",
			Handler:    _Matcher_QueueMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _Matcher_CancelMatch_Handler,
		},
		{
			MethodName: "QueryMatch",
			Handler:    _Matcher_QueryMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/matcher/v1/matcher.proto",
}
