// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1

import (
	relay "github.com/huangyuCN/atlas/contrib/actor/relay"
	proto "google.golang.org/protobuf/proto"
)

// BattleServiceRouteTable 是 BattleService 的透传路由表（atlas.route.v1 注解生成）。
var BattleServiceRouteTable = relay.Table{
	"/battle.v1.BattleService/JoinBattle": {
		Operation:   "/battle.v1.BattleService/JoinBattle",
		Service:     "battle.v1.BattleService",
		Method:      "JoinBattle",
		Actor:       "battle",
		Access:      relay.AccessClient,
		UidSource:   relay.UidField,
		IsTell:      false,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(JoinBattleReq) },
		NewReply:    func() proto.Message { return new(JoinBattleReply) },
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*JoinBattleReq)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
	"/battle.v1.BattleService/SendFrameInput": {
		Operation:   "/battle.v1.BattleService/SendFrameInput",
		Service:     "battle.v1.BattleService",
		Method:      "SendFrameInput",
		Actor:       "battle",
		Access:      relay.AccessClient,
		UidSource:   relay.UidField,
		IsTell:      true,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(FrameInputReq) },
		NewReply:    nil, // returns Empty 即 Tell，无回执
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*FrameInputReq)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
	"/battle.v1.BattleService/SyncFrames": {
		Operation:   "/battle.v1.BattleService/SyncFrames",
		Service:     "battle.v1.BattleService",
		Method:      "SyncFrames",
		Actor:       "battle",
		Access:      relay.AccessClient,
		UidSource:   relay.UidField,
		IsTell:      false,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(SyncFramesReq) },
		NewReply:    func() proto.Message { return new(SyncFramesReply) },
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*SyncFramesReq)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
	"/battle.v1.BattleService/Create": {
		Operation:   "/battle.v1.BattleService/Create",
		Service:     "battle.v1.BattleService",
		Method:      "Create",
		Actor:       "battle",
		Access:      relay.AccessInternal,
		UidSource:   relay.UidField,
		IsTell:      false,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(CreateBattleRequest) },
		NewReply:    func() proto.Message { return new(CreateBattleReply) },
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*CreateBattleRequest)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
	"/battle.v1.BattleService/GetState": {
		Operation:   "/battle.v1.BattleService/GetState",
		Service:     "battle.v1.BattleService",
		Method:      "GetState",
		Actor:       "battle",
		Access:      relay.AccessInternal,
		UidSource:   relay.UidField,
		IsTell:      false,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(GetStateReq) },
		NewReply:    func() proto.Message { return new(GetStateReply) },
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*GetStateReq)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
	"/battle.v1.BattleService/IssueEntryTicket": {
		Operation:   "/battle.v1.BattleService/IssueEntryTicket",
		Service:     "battle.v1.BattleService",
		Method:      "IssueEntryTicket",
		Actor:       "battle",
		Access:      relay.AccessInternal,
		UidSource:   relay.UidField,
		IsTell:      false,
		Idempotency: relay.IdempotencyNone,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
		NewRequest:  func() proto.Message { return new(IssueEntryTicketReq) },
		NewReply:    func() proto.Message { return new(IssueEntryTicketReply) },
		UidOf: func(req any) (string, bool) {
			r, ok := req.(*IssueEntryTicketReq)
			if !ok {
				return "", false
			}
			return r.BattleId, r.BattleId != ""
		},
	},
}

// BattleServiceLifecycleTable 是 BattleService 的 op 生命周期表（含 INTERNAL op；供能力协商与废弃提示）。
var BattleServiceLifecycleTable = relay.LifecycleTable{
	"/battle.v1.BattleService/JoinBattle": {
		Operation:   "/battle.v1.BattleService/JoinBattle",
		Service:     "battle.v1.BattleService",
		Method:      "JoinBattle",
		Access:      relay.AccessClient,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
	"/battle.v1.BattleService/SendFrameInput": {
		Operation:   "/battle.v1.BattleService/SendFrameInput",
		Service:     "battle.v1.BattleService",
		Method:      "SendFrameInput",
		Access:      relay.AccessClient,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
	"/battle.v1.BattleService/SyncFrames": {
		Operation:   "/battle.v1.BattleService/SyncFrames",
		Service:     "battle.v1.BattleService",
		Method:      "SyncFrames",
		Access:      relay.AccessClient,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
	"/battle.v1.BattleService/Create": {
		Operation:   "/battle.v1.BattleService/Create",
		Service:     "battle.v1.BattleService",
		Method:      "Create",
		Access:      relay.AccessInternal,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
	"/battle.v1.BattleService/GetState": {
		Operation:   "/battle.v1.BattleService/GetState",
		Service:     "battle.v1.BattleService",
		Method:      "GetState",
		Access:      relay.AccessInternal,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
	"/battle.v1.BattleService/IssueEntryTicket": {
		Operation:   "/battle.v1.BattleService/IssueEntryTicket",
		Service:     "battle.v1.BattleService",
		Method:      "IssueEntryTicket",
		Access:      relay.AccessInternal,
		Since:       "",
		Deprecated:  "",
		Replacement: "",
	},
}
