// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/atlas/v1/route.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。


export interface RouteRule {
  actor?: string; // atlas.route.v1.RouteRule.actor
  access?: Access; // atlas.route.v1.RouteRule.access
  uid?: UidSource; // atlas.route.v1.RouteRule.uid
  uidField?: string; // atlas.route.v1.RouteRule.uid_field
  idempotency?: Idempotency; // atlas.route.v1.RouteRule.idempotency
  since?: string; // atlas.route.v1.RouteRule.since
  deprecated?: string; // atlas.route.v1.RouteRule.deprecated
  replacement?: string; // atlas.route.v1.RouteRule.replacement
  rateLimit?: RateLimit; // atlas.route.v1.RouteRule.rate_limit
}

export interface RouteOverride {
  access?: Access; // atlas.route.v1.RouteOverride.access
  uid?: UidSource; // atlas.route.v1.RouteOverride.uid
  uidField?: string; // atlas.route.v1.RouteOverride.uid_field
  idempotency?: Idempotency; // atlas.route.v1.RouteOverride.idempotency
  since?: string; // atlas.route.v1.RouteOverride.since
  deprecated?: string; // atlas.route.v1.RouteOverride.deprecated
  replacement?: string; // atlas.route.v1.RouteOverride.replacement
  rateLimit?: RateLimit; // atlas.route.v1.RouteOverride.rate_limit
}

export interface RateLimit {
  qps?: number; // atlas.route.v1.RateLimit.qps
  burst?: number; // atlas.route.v1.RateLimit.burst
  scope?: RateLimitScope; // atlas.route.v1.RateLimit.scope
}

export type Access = "ACCESS_UNSPECIFIED" | "ACCESS_CLIENT" | "ACCESS_INTERNAL";

export type UidSource = "UID_SOURCE_UNSPECIFIED" | "UID_SOURCE_SESSION" | "UID_SOURCE_FIELD";

export type Idempotency = "IDEMPOTENCY_UNSPECIFIED" | "IDEMPOTENT";

export type RateLimitScope = "RATE_LIMIT_SCOPE_UNSPECIFIED" | "RATE_LIMIT_SCOPE_PLAYER" | "RATE_LIMIT_SCOPE_GLOBAL";

