// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/lockstep/lockstep.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。

import type { Timestamp } from "../../google/protobuf/timestamp_pb.js";

export interface SessionMeta {
  sessionId?: string; // atlas.game.lockstep.SessionMeta.session_id
  maxPlayers?: number; // atlas.game.lockstep.SessionMeta.max_players
  maxSpectators?: number; // atlas.game.lockstep.SessionMeta.max_spectators
  tickMillis?: number; // atlas.game.lockstep.SessionMeta.tick_millis
  inputDelayFrames?: number; // atlas.game.lockstep.SessionMeta.input_delay_frames
  maxRollbackFrames?: number; // atlas.game.lockstep.SessionMeta.max_rollback_frames
  mode?: LockstepMode; // atlas.game.lockstep.SessionMeta.mode
}

export interface LockstepInput {
  frameId?: string // int64; // atlas.game.lockstep.LockstepInput.frame_id
  playerId?: string; // atlas.game.lockstep.LockstepInput.player_id
  payload?: string // base64; // atlas.game.lockstep.LockstepInput.payload
  predicted?: boolean; // atlas.game.lockstep.LockstepInput.predicted
  clientSendTimeUnixNano?: string // int64; // atlas.game.lockstep.LockstepInput.client_send_time_unix_nano
}

export interface FrameInputs {
  frameId?: string // int64; // atlas.game.lockstep.FrameInputs.frame_id
  inputs?: LockstepInput[]; // atlas.game.lockstep.FrameInputs.inputs
}

export interface SnapshotMeta {
  frameId?: string // int64; // atlas.game.lockstep.SnapshotMeta.frame_id
  stateHash?: string // base64; // atlas.game.lockstep.SnapshotMeta.state_hash
  sizeBytes?: string // int64; // atlas.game.lockstep.SnapshotMeta.size_bytes
  storageKey?: string; // atlas.game.lockstep.SnapshotMeta.storage_key
}

export interface LockstepFrame {
  frameId?: string // int64; // atlas.game.lockstep.LockstepFrame.frame_id
  inputs?: LockstepInput[]; // atlas.game.lockstep.LockstepFrame.inputs
  stateHash?: string // base64; // atlas.game.lockstep.LockstepFrame.state_hash
  serverTime?: Timestamp; // atlas.game.lockstep.LockstepFrame.server_time
  snapshot?: SnapshotMeta; // atlas.game.lockstep.LockstepFrame.snapshot
}

export interface CreateSessionRequest {
  meta?: SessionMeta; // atlas.game.lockstep.CreateSessionRequest.meta
}

export interface CreateSessionReply {
  meta?: SessionMeta; // atlas.game.lockstep.CreateSessionReply.meta
}

export interface DestroySessionRequest {
  sessionId?: string; // atlas.game.lockstep.DestroySessionRequest.session_id
}

export interface DestroySessionReply {
}

export interface JoinSessionRequest {
  sessionId?: string; // atlas.game.lockstep.JoinSessionRequest.session_id
  playerId?: string; // atlas.game.lockstep.JoinSessionRequest.player_id
}

export interface JoinSessionReply {
  meta?: SessionMeta; // atlas.game.lockstep.JoinSessionReply.meta
  currentFrame?: string // int64; // atlas.game.lockstep.JoinSessionReply.current_frame
  snapshot?: SnapshotMeta; // atlas.game.lockstep.JoinSessionReply.snapshot
}

export interface LeaveSessionRequest {
  sessionId?: string; // atlas.game.lockstep.LeaveSessionRequest.session_id
  playerId?: string; // atlas.game.lockstep.LeaveSessionRequest.player_id
}

export interface LeaveSessionReply {
}

export interface PushInputRequest {
  sessionId?: string; // atlas.game.lockstep.PushInputRequest.session_id
  input?: LockstepInput; // atlas.game.lockstep.PushInputRequest.input
}

export interface PushInputReply {
  acceptedFrameId?: string // int64; // atlas.game.lockstep.PushInputReply.accepted_frame_id
}

export interface SyncFrameRequest {
  sessionId?: string; // atlas.game.lockstep.SyncFrameRequest.session_id
  fromFrameId?: string // int64; // atlas.game.lockstep.SyncFrameRequest.from_frame_id
  limit?: number; // atlas.game.lockstep.SyncFrameRequest.limit
}

export interface SyncFrameReply {
  frames?: LockstepFrame[]; // atlas.game.lockstep.SyncFrameReply.frames
  confirmedFrameId?: string // int64; // atlas.game.lockstep.SyncFrameReply.confirmed_frame_id
}

export interface SpectateRequest {
  sessionId?: string; // atlas.game.lockstep.SpectateRequest.session_id
  fromFrameId?: string // int64; // atlas.game.lockstep.SpectateRequest.from_frame_id
}

export interface ReplayRequest {
  sessionId?: string; // atlas.game.lockstep.ReplayRequest.session_id
  fromFrameId?: string // int64; // atlas.game.lockstep.ReplayRequest.from_frame_id
  toFrameId?: string // int64; // atlas.game.lockstep.ReplayRequest.to_frame_id
}

export interface ReplayFrame {
  frame?: LockstepFrame; // atlas.game.lockstep.ReplayFrame.frame
}

export interface ScanInputsRequest {
  sessionId?: string; // atlas.game.lockstep.ScanInputsRequest.session_id
  playerId?: string; // atlas.game.lockstep.ScanInputsRequest.player_id
  fromFrameId?: string // int64; // atlas.game.lockstep.ScanInputsRequest.from_frame_id
  toFrameId?: string // int64; // atlas.game.lockstep.ScanInputsRequest.to_frame_id
  fromTimeUnixNano?: string // int64; // atlas.game.lockstep.ScanInputsRequest.from_time_unix_nano
  toTimeUnixNano?: string // int64; // atlas.game.lockstep.ScanInputsRequest.to_time_unix_nano
  maxRecords?: number; // atlas.game.lockstep.ScanInputsRequest.max_records
}

export interface InputRecord {
  sessionId?: string; // atlas.game.lockstep.InputRecord.session_id
  input?: LockstepInput; // atlas.game.lockstep.InputRecord.input
}

export interface ScanInputsReply {
  records?: InputRecord[]; // atlas.game.lockstep.ScanInputsReply.records
}

export type LockstepMode = "LOCKSTEP_MODE_UNSPECIFIED" | "LOCKSTEP_MODE_SERVER_AUTHORITATIVE" | "LOCKSTEP_MODE_P2P";

