// Code generated by protoc-gen-atlas-client. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-client v0.1.0
// - protoc             v5.26.1
// source: api/game/v1/player_service.proto

package gamev1opclient

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/game/v1"
	client "github.com/huangyuCN/atlas-sdk-go/client"
)

// PlayerService 是 PlayerService 的业务 op 客户端 stub（atlas.route.v1 注解生成）：
// 方法直接映射客户端可达 rpc，经会话通道发送；身份由会话携带（消息体不含 token/player_id）。
// 与 gRPC 生成的 PlayerServiceClient（连接级 client）不是一回事。
type PlayerService struct {
	cli client.Invoker
}

// NewPlayerService 以会话内核构造 client stub。
func NewPlayerService(cli client.Invoker) *PlayerService {
	return &PlayerService{cli: cli}
}

// Register 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) Register(ctx context.Context, req *v1.RegisterReq, opts ...client.InvokeOption) (*v1.RegisterReply, error) {
	var out v1.RegisterReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/Register`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetPlayerData 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) GetPlayerData(ctx context.Context, req *v1.GetPlayerDataReq, opts ...client.InvokeOption) (*v1.PlayerDataReply, error) {
	var out v1.PlayerDataReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/GetPlayerData`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetBackpack 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) GetBackpack(ctx context.Context, req *v1.GetBackpackReq, opts ...client.InvokeOption) (*v1.BackpackReply, error) {
	var out v1.BackpackReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/GetBackpack`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// EnterMatchQueue 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) EnterMatchQueue(ctx context.Context, req *v1.EnterMatchQueueReq, opts ...client.InvokeOption) (*v1.EnterMatchQueueReply, error) {
	var out v1.EnterMatchQueueReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/EnterMatchQueue`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelMatch 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) CancelMatch(ctx context.Context, req *v1.CancelMatchReq, opts ...client.InvokeOption) (*v1.CancelMatchReply, error) {
	var out v1.CancelMatchReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/CancelMatch`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMatchStatus 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) GetMatchStatus(ctx context.Context, req *v1.GetMatchStatusReq, opts ...client.InvokeOption) (*v1.MatchStatusReply, error) {
	var out v1.MatchStatusReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/GetMatchStatus`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateParty 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) CreateParty(ctx context.Context, req *v1.CreatePartyReq, opts ...client.InvokeOption) (*v1.PartyReply, error) {
	var out v1.PartyReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/CreateParty`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// JoinParty 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) JoinParty(ctx context.Context, req *v1.JoinPartyReq, opts ...client.InvokeOption) (*v1.PartyReply, error) {
	var out v1.PartyReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/JoinParty`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// LeaveParty 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) LeaveParty(ctx context.Context, req *v1.LeavePartyReq, opts ...client.InvokeOption) (*v1.PartyReply, error) {
	var out v1.PartyReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/LeaveParty`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// GetParty 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) GetParty(ctx context.Context, req *v1.GetPartyReq, opts ...client.InvokeOption) (*v1.PartyReply, error) {
	var out v1.PartyReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/GetParty`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// QueueParty 请求-响应调用；业务拒绝返回错误（Reason 为主键）。
func (c *PlayerService) QueueParty(ctx context.Context, req *v1.QueuePartyReq, opts ...client.InvokeOption) (*v1.PartyQueueReply, error) {
	var out v1.PartyQueueReply
	if err := c.cli.Invoke(ctx, `/game.v1.PlayerService/QueueParty`, req, &out, opts...); err != nil {
		return nil, err
	}
	return &out, nil
}

// PlayerServiceProtocolOps 是 PlayerService 的会话 op 名（按 rpc 名索引）。
var PlayerServiceProtocolOps = struct {
	Register        string
	GetPlayerData   string
	GetBackpack     string
	EnterMatchQueue string
	CancelMatch     string
	GetMatchStatus  string
	CreateParty     string
	JoinParty       string
	LeaveParty      string
	GetParty        string
	QueueParty      string
}{
	Register:        "/game.v1.PlayerService/Register",
	GetPlayerData:   "/game.v1.PlayerService/GetPlayerData",
	GetBackpack:     "/game.v1.PlayerService/GetBackpack",
	EnterMatchQueue: "/game.v1.PlayerService/EnterMatchQueue",
	CancelMatch:     "/game.v1.PlayerService/CancelMatch",
	GetMatchStatus:  "/game.v1.PlayerService/GetMatchStatus",
	CreateParty:     "/game.v1.PlayerService/CreateParty",
	JoinParty:       "/game.v1.PlayerService/JoinParty",
	LeaveParty:      "/game.v1.PlayerService/LeaveParty",
	GetParty:        "/game.v1.PlayerService/GetParty",
	QueueParty:      "/game.v1.PlayerService/QueueParty",
}

// PlayerServiceToken 从会话消息里取 Token（无该字段的消息返回零值）。
func PlayerServiceToken(msg any) string {
	return ""
}

// PlayerServicePlayerID 从会话消息里取 PlayerID（无该字段的消息返回零值）。
func PlayerServicePlayerID(msg any) string {
	switch m := msg.(type) {
	case *v1.RegisterReply:
		return m.PlayerId
	}
	return ""
}

// PlayerServiceExpiresAt 从会话消息里取 ExpiresAt（无该字段的消息返回零值）。
func PlayerServiceExpiresAt(msg any) int64 {
	return 0
}

// PlayerServicePushOps 是 api/game/v1/player_service.proto 声明的服务端推送 op（客户端按 op 分发）。
var PlayerServicePushOps = struct {
	MatchStartedNotify string
	MatchFailedNotify  string
	PartyRosterNotify  string
}{
	MatchStartedNotify: "/game.v1.MatchStartedNotify",
	MatchFailedNotify:  "/game.v1.MatchFailedNotify",
	PartyRosterNotify:  "/game.v1.PartyRosterNotify",
}
