// Code generated by protoc-gen-atlas-client (lang=ts). DO NOT EDIT.
// source: api/battle/v1/battle.proto
// 序列化语义（protojson）：字段名 lowerCamelCase、int64/uint64 与 bytes 为 string、
// 零值省略 → 全部字段可缺省；枚举以枚举名（字符串）下发。


export interface CreateBattleRequest {
  matchId?: string; // battle.v1.CreateBattleRequest.match_id
  playerIds?: string[]; // battle.v1.CreateBattleRequest.player_ids
}

export interface CreateBattleReply {
  battleId?: string; // battle.v1.CreateBattleReply.battle_id
}

export interface GetBattleRequest {
  battleId?: string; // battle.v1.GetBattleRequest.battle_id
}

export interface GetBattleReply {
  state?: string; // battle.v1.GetBattleReply.state
}

export interface PlayerResult {
  playerId?: string; // battle.v1.PlayerResult.player_id
  win?: boolean; // battle.v1.PlayerResult.win
  score?: number; // battle.v1.PlayerResult.score
}

export interface BattleSettledEvent {
  battleId?: string; // battle.v1.BattleSettledEvent.battle_id
  matchId?: string; // battle.v1.BattleSettledEvent.match_id
  players?: PlayerResult[]; // battle.v1.BattleSettledEvent.players
}

export interface GetStateReq {
}

export interface GetStateReply {
  state?: string; // battle.v1.GetStateReply.state
  currentFrame?: string // int64; // battle.v1.GetStateReply.current_frame
  playerCount?: number; // battle.v1.GetStateReply.player_count
}

