// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/game/v1/player_service.proto

package gamev1

import (
	context "context"
	fmt "fmt"
	core "github.com/huangyuCN/atlas/contrib/actor/core"
	types "github.com/huangyuCN/atlas/contrib/actor/types"
	errors "github.com/huangyuCN/atlas/errors"
	proto "google.golang.org/protobuf/proto"
)

// PlayerServiceActorServer 是业务 actor 实现的接口；签名由 service 块决定，
// returns 具体消息即 Ask，returns google.protobuf.Empty 即 Tell（单向）。
type PlayerServiceActorServer interface {
	Register(ctx core.ActorContext, req *RegisterReq) (*RegisterReply, error)
	GetPlayerData(ctx core.ActorContext, req *GetPlayerDataReq) (*PlayerDataReply, error)
	GetBackpack(ctx core.ActorContext, req *GetBackpackReq) (*BackpackReply, error)
	EnterMatchQueue(ctx core.ActorContext, req *EnterMatchQueueReq) (*EnterMatchQueueReply, error)
	CancelMatch(ctx core.ActorContext, req *CancelMatchReq) (*CancelMatchReply, error)
	GetMatchStatus(ctx core.ActorContext, req *GetMatchStatusReq) (*MatchStatusReply, error)
	CreateParty(ctx core.ActorContext, req *CreatePartyReq) (*PartyReply, error)
	JoinParty(ctx core.ActorContext, req *JoinPartyReq) (*PartyReply, error)
	LeaveParty(ctx core.ActorContext, req *LeavePartyReq) (*PartyReply, error)
	GetParty(ctx core.ActorContext, req *GetPartyReq) (*PartyReply, error)
	QueueParty(ctx core.ActorContext, req *QueuePartyReq) (*PartyQueueReply, error)
	Login(ctx core.ActorContext, req *LoginReq) (*LoginReply, error)
	Logout(ctx core.ActorContext, msg *LogoutMsg) error
	GrantItem(ctx core.ActorContext, req *GrantItemReq) (*GrantItemReply, error)
	GetPlayer(ctx core.ActorContext, req *GetPlayerReq) (*PlayerReply, error)
}

// UnimplementedPlayerServiceActorServer 是兜底基类；业务 actor embed 它获得接口演进安全。
type UnimplementedPlayerServiceActorServer struct{}

func (UnimplementedPlayerServiceActorServer) Register(core.ActorContext, *RegisterReq) (*RegisterReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.Register")
}
func (UnimplementedPlayerServiceActorServer) GetPlayerData(core.ActorContext, *GetPlayerDataReq) (*PlayerDataReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GetPlayerData")
}
func (UnimplementedPlayerServiceActorServer) GetBackpack(core.ActorContext, *GetBackpackReq) (*BackpackReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GetBackpack")
}
func (UnimplementedPlayerServiceActorServer) EnterMatchQueue(core.ActorContext, *EnterMatchQueueReq) (*EnterMatchQueueReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.EnterMatchQueue")
}
func (UnimplementedPlayerServiceActorServer) CancelMatch(core.ActorContext, *CancelMatchReq) (*CancelMatchReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.CancelMatch")
}
func (UnimplementedPlayerServiceActorServer) GetMatchStatus(core.ActorContext, *GetMatchStatusReq) (*MatchStatusReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GetMatchStatus")
}
func (UnimplementedPlayerServiceActorServer) CreateParty(core.ActorContext, *CreatePartyReq) (*PartyReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.CreateParty")
}
func (UnimplementedPlayerServiceActorServer) JoinParty(core.ActorContext, *JoinPartyReq) (*PartyReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.JoinParty")
}
func (UnimplementedPlayerServiceActorServer) LeaveParty(core.ActorContext, *LeavePartyReq) (*PartyReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.LeaveParty")
}
func (UnimplementedPlayerServiceActorServer) GetParty(core.ActorContext, *GetPartyReq) (*PartyReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GetParty")
}
func (UnimplementedPlayerServiceActorServer) QueueParty(core.ActorContext, *QueuePartyReq) (*PartyQueueReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.QueueParty")
}
func (UnimplementedPlayerServiceActorServer) Login(core.ActorContext, *LoginReq) (*LoginReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.Login")
}
func (UnimplementedPlayerServiceActorServer) Logout(core.ActorContext, *LogoutMsg) error {
	return errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.Logout")
}
func (UnimplementedPlayerServiceActorServer) GrantItem(core.ActorContext, *GrantItemReq) (*GrantItemReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GrantItem")
}
func (UnimplementedPlayerServiceActorServer) GetPlayer(core.ActorContext, *GetPlayerReq) (*PlayerReply, error) {
	return nil, errors.InternalServer("ACTOR_METHOD_UNIMPLEMENTED", "actor 方法未实现: PlayerService.GetPlayer")
}

// playerServiceDecodeTable 是 type_url → 类型化 Unmarshal 闭包的解码表（生成期静态绑定）。
var playerServiceDecodeTable = map[string]func([]byte) (proto.Message, error){
	"type.googleapis.com/game.v1.RegisterReq": func(b []byte) (proto.Message, error) {
		m := new(RegisterReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GetPlayerDataReq": func(b []byte) (proto.Message, error) {
		m := new(GetPlayerDataReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GetBackpackReq": func(b []byte) (proto.Message, error) {
		m := new(GetBackpackReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.EnterMatchQueueReq": func(b []byte) (proto.Message, error) {
		m := new(EnterMatchQueueReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.CancelMatchReq": func(b []byte) (proto.Message, error) {
		m := new(CancelMatchReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GetMatchStatusReq": func(b []byte) (proto.Message, error) {
		m := new(GetMatchStatusReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.CreatePartyReq": func(b []byte) (proto.Message, error) {
		m := new(CreatePartyReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.JoinPartyReq": func(b []byte) (proto.Message, error) {
		m := new(JoinPartyReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.LeavePartyReq": func(b []byte) (proto.Message, error) {
		m := new(LeavePartyReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GetPartyReq": func(b []byte) (proto.Message, error) {
		m := new(GetPartyReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.QueuePartyReq": func(b []byte) (proto.Message, error) {
		m := new(QueuePartyReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.LoginReq": func(b []byte) (proto.Message, error) {
		m := new(LoginReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.LogoutMsg": func(b []byte) (proto.Message, error) {
		m := new(LogoutMsg)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GrantItemReq": func(b []byte) (proto.Message, error) {
		m := new(GrantItemReq)
		return m, proto.Unmarshal(b, m)
	},
	"type.googleapis.com/game.v1.GetPlayerReq": func(b []byte) (proto.Message, error) {
		m := new(GetPlayerReq)
		return m, proto.Unmarshal(b, m)
	},
}

// NewPlayerServiceDecodeInbound 返回装配进 Props.DecodeInbound 的入站解码钩子：
// 集群入站 payload 在投递 handler 链前按 type_url 归一为具体消息对象。
func NewPlayerServiceDecodeInbound() func(typeURL string, payload []byte) (any, error) {
	return func(typeURL string, payload []byte) (any, error) {
		decode, ok := playerServiceDecodeTable[typeURL]
		if !ok {
			return nil, fmt.Errorf("actor: 未知消息类型 %q", typeURL)
		}
		return decode(payload)
	}
}

// playerServiceDispatch 组装业务实现与本地路由兜底；生命周期经 DispatchBase 断言转发。
type playerServiceDispatch struct {
	*core.DispatchBase
	impl PlayerServiceActorServer
}

// OnAsk 分发 Ask 消息：前置钩子（可选）→ 静态 type switch，未命中回落本地路由。
func (d *playerServiceDispatch) OnAsk(ctx core.ActorContext, req any) (any, error) {
	if err := d.BeforeAsk(ctx, req); err != nil {
		return nil, err
	}
	switch r := req.(type) {
	case *RegisterReq:
		return d.impl.Register(ctx, r)
	case *GetPlayerDataReq:
		return d.impl.GetPlayerData(ctx, r)
	case *GetBackpackReq:
		return d.impl.GetBackpack(ctx, r)
	case *EnterMatchQueueReq:
		return d.impl.EnterMatchQueue(ctx, r)
	case *CancelMatchReq:
		return d.impl.CancelMatch(ctx, r)
	case *GetMatchStatusReq:
		return d.impl.GetMatchStatus(ctx, r)
	case *CreatePartyReq:
		return d.impl.CreateParty(ctx, r)
	case *JoinPartyReq:
		return d.impl.JoinParty(ctx, r)
	case *LeavePartyReq:
		return d.impl.LeaveParty(ctx, r)
	case *GetPartyReq:
		return d.impl.GetParty(ctx, r)
	case *QueuePartyReq:
		return d.impl.QueueParty(ctx, r)
	case *LoginReq:
		return d.impl.Login(ctx, r)
	case *GrantItemReq:
		return d.impl.GrantItem(ctx, r)
	case *GetPlayerReq:
		return d.impl.GetPlayer(ctx, r)
	default:
		return d.FallbackAsk(ctx, req)
	}
}

// OnTell 分发 Tell 消息：前置钩子（可选）→ 静态 type switch，未命中回落本地路由。
func (d *playerServiceDispatch) OnTell(ctx core.ActorContext, msg any) error {
	if err := d.BeforeTell(ctx, msg); err != nil {
		return err
	}
	switch m := msg.(type) {
	case *LogoutMsg:
		return d.impl.Logout(ctx, m)
	default:
		return d.FallbackTell(ctx, msg)
	}
}

// NewPlayerServiceActorServer 把业务实现组装为 core.Handler（含本地路由与入站解码能力）。
func NewPlayerServiceActorServer(impl PlayerServiceActorServer, opts ...core.DispatchOption) core.Handler {
	return &playerServiceDispatch{
		DispatchBase: core.NewDispatchBase(impl, opts...),
		impl:         impl,
	}
}

// PlayerServiceClusterClient 是**集群内部互调专用**的 client stub：强类型返回，
// 跨节点 []byte 解码在内部完成。跨服务/跨集群调用请走 RPC 面（本 proto 生成的 PlayerServiceServer 接入层），也不要与客户端 SDK 的 PlayerServiceOpClient 混用。
type PlayerServiceClusterClient struct {
	inv core.ActorInvoker
}

// NewPlayerServiceClusterClient 以发送端运行时构造集群互调 client stub。
func NewPlayerServiceClusterClient(inv core.ActorInvoker) *PlayerServiceClusterClient {
	return &PlayerServiceClusterClient{inv: inv}
}

// Register 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) Register(ctx context.Context, pid types.PID, req *RegisterReq, opts ...core.SendOption) (*RegisterReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *RegisterReply:
		return v, nil
	case []byte:
		out := new(RegisterReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// GetPlayerData 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GetPlayerData(ctx context.Context, pid types.PID, req *GetPlayerDataReq, opts ...core.SendOption) (*PlayerDataReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PlayerDataReply:
		return v, nil
	case []byte:
		out := new(PlayerDataReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// GetBackpack 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GetBackpack(ctx context.Context, pid types.PID, req *GetBackpackReq, opts ...core.SendOption) (*BackpackReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *BackpackReply:
		return v, nil
	case []byte:
		out := new(BackpackReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// EnterMatchQueue 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) EnterMatchQueue(ctx context.Context, pid types.PID, req *EnterMatchQueueReq, opts ...core.SendOption) (*EnterMatchQueueReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *EnterMatchQueueReply:
		return v, nil
	case []byte:
		out := new(EnterMatchQueueReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// CancelMatch 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) CancelMatch(ctx context.Context, pid types.PID, req *CancelMatchReq, opts ...core.SendOption) (*CancelMatchReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *CancelMatchReply:
		return v, nil
	case []byte:
		out := new(CancelMatchReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// GetMatchStatus 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GetMatchStatus(ctx context.Context, pid types.PID, req *GetMatchStatusReq, opts ...core.SendOption) (*MatchStatusReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *MatchStatusReply:
		return v, nil
	case []byte:
		out := new(MatchStatusReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// CreateParty 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) CreateParty(ctx context.Context, pid types.PID, req *CreatePartyReq, opts ...core.SendOption) (*PartyReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PartyReply:
		return v, nil
	case []byte:
		out := new(PartyReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// JoinParty 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) JoinParty(ctx context.Context, pid types.PID, req *JoinPartyReq, opts ...core.SendOption) (*PartyReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PartyReply:
		return v, nil
	case []byte:
		out := new(PartyReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// LeaveParty 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) LeaveParty(ctx context.Context, pid types.PID, req *LeavePartyReq, opts ...core.SendOption) (*PartyReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PartyReply:
		return v, nil
	case []byte:
		out := new(PartyReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// GetParty 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GetParty(ctx context.Context, pid types.PID, req *GetPartyReq, opts ...core.SendOption) (*PartyReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PartyReply:
		return v, nil
	case []byte:
		out := new(PartyReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// QueueParty 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) QueueParty(ctx context.Context, pid types.PID, req *QueuePartyReq, opts ...core.SendOption) (*PartyQueueReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PartyQueueReply:
		return v, nil
	case []byte:
		out := new(PartyQueueReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// Login 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) Login(ctx context.Context, pid types.PID, req *LoginReq, opts ...core.SendOption) (*LoginReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *LoginReply:
		return v, nil
	case []byte:
		out := new(LoginReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// Logout 单向投递 Tell 消息（无回执；变参透传投递选项——sender/观测头等）。
func (c *PlayerServiceClusterClient) Logout(ctx context.Context, pid types.PID, msg *LogoutMsg, opts ...core.SendOption) error {
	return c.inv.Tell(ctx, pid, msg, opts...)
}

// GrantItem 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GrantItem(ctx context.Context, pid types.PID, req *GrantItemReq, opts ...core.SendOption) (*GrantItemReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *GrantItemReply:
		return v, nil
	case []byte:
		out := new(GrantItemReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}

// GetPlayer 同步请求 Ask；业务错误以 Go error 返回（code/reason 经集群往返保留；
// 变参透传投递选项——sender/观测头等由调用方按需注入）。
func (c *PlayerServiceClusterClient) GetPlayer(ctx context.Context, pid types.PID, req *GetPlayerReq, opts ...core.SendOption) (*PlayerReply, error) {
	rep, err := c.inv.Ask(ctx, pid, req, opts...)
	if err != nil {
		return nil, err
	}
	switch v := rep.(type) {
	case *PlayerReply:
		return v, nil
	case []byte:
		out := new(PlayerReply)
		if err := proto.Unmarshal(v, out); err != nil {
			return nil, fmt.Errorf("actor: 响应解码失败: %w", err)
		}
		return out, nil
	default:
		return nil, fmt.Errorf("actor: 不支持的响应类型 %T", rep)
	}
}
