// PlayerService 是玩家域的统一业务契约：客户端 op 与 actor 分发共用同一份
// service/消息（一份契约，不再有 gateway.v1 ↔ game.v1 镜像投影）。
//
// 身份语义（连接即会话，主体身份永不来自客户端 payload）：
//   - target PID = "player:{会话玩家}"（uid=UID_SOURCE_SESSION，Gateway 按登录
//     会话组装，客户端不可影响）——actor 只处理自己的数据由此保证；
//   - 发起者身份由 Gateway 注入投递 sender；JoinParty(party_id) 等字段是客体
//     参数（操作目标），不是身份字段；
//   - access=CLIENT 的方法是客户端 op（SDK 导出、Gateway 透传）；
//     INTERNAL 是服务端内部方法（如 Gateway 调 Login 校验密码、管理面转发），
//     客户端 op 不存在、SDK 不导出。
//
// 撮合/组队回执语义与 api/matcher/v1 的撮合契约对应：属性由聚合根权威填充
// （客户端不参与上报，反作弊前提）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/game/v1/player_service.proto

package gamev1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/common/v1"
	v11 "github.com/huangyuCN/atlas-game-layout/api/matcher/v1"
	_ "github.com/huangyuCN/atlas/api/atlas/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogoutReason 是登出/退出原因（PlayerService.Logout 的语义来源）。
type LogoutReason int32

const (
	LogoutReason_LOGOUT_REASON_UNSPECIFIED         LogoutReason = 0
	LogoutReason_LOGOUT_REASON_LOGOUT              LogoutReason = 1 // 玩家主动登出
	LogoutReason_LOGOUT_REASON_LOGGED_IN_ELSEWHERE LogoutReason = 2 // 被新登录挤下线
	LogoutReason_LOGOUT_REASON_SESSION_EXPIRED     LogoutReason = 3 // 会话过期（心跳超时清理联动，异常下线兜底）
)

// Enum value maps for LogoutReason.
var (
	LogoutReason_name = map[int32]string{
		0: "LOGOUT_REASON_UNSPECIFIED",
		1: "LOGOUT_REASON_LOGOUT",
		2: "LOGOUT_REASON_LOGGED_IN_ELSEWHERE",
		3: "LOGOUT_REASON_SESSION_EXPIRED",
	}
	LogoutReason_value = map[string]int32{
		"LOGOUT_REASON_UNSPECIFIED":         0,
		"LOGOUT_REASON_LOGOUT":              1,
		"LOGOUT_REASON_LOGGED_IN_ELSEWHERE": 2,
		"LOGOUT_REASON_SESSION_EXPIRED":     3,
	}
)

func (x LogoutReason) Enum() *LogoutReason {
	p := new(LogoutReason)
	*p = x
	return p
}

func (x LogoutReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogoutReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_game_v1_player_service_proto_enumTypes[0].Descriptor()
}

func (LogoutReason) Type() protoreflect.EnumType {
	return &file_api_game_v1_player_service_proto_enumTypes[0]
}

func (x LogoutReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogoutReason.Descriptor instead.
func (LogoutReason) EnumDescriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{0}
}

// RegisterReq 注册：玩家数据不存在则创建并回执（注册与登录两段式）。
type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RegisterReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// LoginReq 登录校验：密码校验与会话令牌落库由 PlayerActor 完成；
// gateway_instance 由 Gateway 注入（会话路由表写入用），客户端不感知。
type LoginReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token           string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Gateway 预签发的会话凭据（game 侧不再持有 token 副本，仅校验链路使用）
	GatewayInstance string                 `protobuf:"bytes,4,opt,name=gateway_instance,json=gatewayInstance,proto3" json:"gateway_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginReq) GetGatewayInstance() string {
	if x != nil {
		return x.GatewayInstance
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// LogoutMsg 登出/挤下线退出通知（Tell 载荷）：PlayerActor 收到后保存并停止自身。
type LogoutMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        LogoutReason           `protobuf:"varint,1,opt,name=reason,proto3,enum=game.v1.LogoutReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutMsg) Reset() {
	*x = LogoutMsg{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutMsg) ProtoMessage() {}

func (x *LogoutMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutMsg.ProtoReflect.Descriptor instead.
func (*LogoutMsg) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutMsg) GetReason() LogoutReason {
	if x != nil {
		return x.Reason
	}
	return LogoutReason_LOGOUT_REASON_UNSPECIFIED
}

// GetPlayerDataReq 玩家数据全量同步请求（登录成功后调用一次完成全量对齐）。
type GetPlayerDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerDataReq) Reset() {
	*x = GetPlayerDataReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerDataReq) ProtoMessage() {}

func (x *GetPlayerDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerDataReq.ProtoReflect.Descriptor instead.
func (*GetPlayerDataReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{5}
}

// GetBackpackReq 背包查询请求。
type GetBackpackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackReq) Reset() {
	*x = GetBackpackReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackReq) ProtoMessage() {}

func (x *GetBackpackReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackReq.ProtoReflect.Descriptor instead.
func (*GetBackpackReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{6}
}

// PlayerDataReply 玩家数据全量快照：摘要 + 背包（actor 内存聚合根快照）。
type PlayerDataReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Items         []*BackpackItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerDataReply) Reset() {
	*x = PlayerDataReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDataReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDataReply) ProtoMessage() {}

func (x *PlayerDataReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDataReply.ProtoReflect.Descriptor instead.
func (*PlayerDataReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerDataReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *PlayerDataReply) GetItems() []*BackpackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// BackpackReply 背包查询回执（BackpackItem 定义见 player.proto，域内共享）。
type BackpackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BackpackItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackpackReply) Reset() {
	*x = BackpackReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpackReply) ProtoMessage() {}

func (x *BackpackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpackReply.ProtoReflect.Descriptor instead.
func (*BackpackReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{8}
}

func (x *BackpackReply) GetItems() []*BackpackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GrantItemReq 背包发放（服务端内部：管理/活动/结算渠道经 grpc 管理面转发）。
type GrantItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"` // 发放原因（审计）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemReq) Reset() {
	*x = GrantItemReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemReq) ProtoMessage() {}

func (x *GrantItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemReq.ProtoReflect.Descriptor instead.
func (*GrantItemReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{9}
}

func (x *GrantItemReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GrantItemReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GrantItemReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GetPlayerReq 玩家摘要查询（服务端内部/管理面 grpc 转发；客户端面用 GetPlayerData）。
type GetPlayerReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerReq) Reset() {
	*x = GetPlayerReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReq) ProtoMessage() {}

func (x *GetPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReq.ProtoReflect.Descriptor instead.
func (*GetPlayerReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{10}
}

// PlayerReply 玩家摘要回执。
type PlayerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerReply) Reset() {
	*x = PlayerReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerReply) ProtoMessage() {}

func (x *PlayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerReply.ProtoReflect.Descriptor instead.
func (*PlayerReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// EnterMatchQueueReq 入队匹配：仅规则集名（空串取服务端默认）。
type EnterMatchQueueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ruleset       string                 `protobuf:"bytes,1,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterMatchQueueReq) Reset() {
	*x = EnterMatchQueueReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterMatchQueueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterMatchQueueReq) ProtoMessage() {}

func (x *EnterMatchQueueReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterMatchQueueReq.ProtoReflect.Descriptor instead.
func (*EnterMatchQueueReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{12}
}

func (x *EnterMatchQueueReq) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

type EnterMatchQueueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterMatchQueueReply) Reset() {
	*x = EnterMatchQueueReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterMatchQueueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterMatchQueueReply) ProtoMessage() {}

func (x *EnterMatchQueueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterMatchQueueReply.ProtoReflect.Descriptor instead.
func (*EnterMatchQueueReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{13}
}

type CancelMatchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchReq) Reset() {
	*x = CancelMatchReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReq) ProtoMessage() {}

func (x *CancelMatchReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReq.ProtoReflect.Descriptor instead.
func (*CancelMatchReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{14}
}

// CancelMatchReply 取消回执：canceled=false 表示本就未在队。
type CancelMatchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Canceled      bool                   `protobuf:"varint,1,opt,name=canceled,proto3" json:"canceled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchReply) Reset() {
	*x = CancelMatchReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchReply) ProtoMessage() {}

func (x *CancelMatchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchReply.ProtoReflect.Descriptor instead.
func (*CancelMatchReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{15}
}

func (x *CancelMatchReply) GetCanceled() bool {
	if x != nil {
		return x.Canceled
	}
	return false
}

// GetMatchStatusReq 匹配状态查询（轮询兜底用；成局/失败另有主动推送）。
type GetMatchStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchStatusReq) Reset() {
	*x = GetMatchStatusReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchStatusReq) ProtoMessage() {}

func (x *GetMatchStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchStatusReq.ProtoReflect.Descriptor instead.
func (*GetMatchStatusReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{16}
}

// MatchStatusReply 匹配状态（枚举语义见 matcher.v1.MatchState）。
// battle_id 供「成局推送丢失后重登恢复」：matched 态据此恢复加入对局。
type MatchStatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         v11.MatchState         `protobuf:"varint,1,opt,name=state,proto3,enum=matcher.v1.MatchState" json:"state,omitempty"`
	TicketId      string                 `protobuf:"bytes,2,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	MatchId       string                 `protobuf:"bytes,3,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	BattleId      string                 `protobuf:"bytes,4,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStatusReply) Reset() {
	*x = MatchStatusReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStatusReply) ProtoMessage() {}

func (x *MatchStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStatusReply.ProtoReflect.Descriptor instead.
func (*MatchStatusReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{17}
}

func (x *MatchStatusReply) GetState() v11.MatchState {
	if x != nil {
		return x.State
	}
	return v11.MatchState(0)
}

func (x *MatchStatusReply) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *MatchStatusReply) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchStatusReply) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

// CreatePartyReq 建队（本玩家为队长）。
type CreatePartyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartyReq) Reset() {
	*x = CreatePartyReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartyReq) ProtoMessage() {}

func (x *CreatePartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartyReq.ProtoReflect.Descriptor instead.
func (*CreatePartyReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{18}
}

// JoinPartyReq 入队：party_id 是客体参数（队伍标识，队长分享）。
type JoinPartyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinPartyReq) Reset() {
	*x = JoinPartyReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinPartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinPartyReq) ProtoMessage() {}

func (x *JoinPartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinPartyReq.ProtoReflect.Descriptor instead.
func (*JoinPartyReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{19}
}

func (x *JoinPartyReq) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

type LeavePartyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeavePartyReq) Reset() {
	*x = LeavePartyReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeavePartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeavePartyReq) ProtoMessage() {}

func (x *LeavePartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeavePartyReq.ProtoReflect.Descriptor instead.
func (*LeavePartyReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{20}
}

// GetPartyReq 名册快照查询（轮询兜底用；成员变更另有主动推送）。
type GetPartyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartyReq) Reset() {
	*x = GetPartyReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartyReq) ProtoMessage() {}

func (x *GetPartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartyReq.ProtoReflect.Descriptor instead.
func (*GetPartyReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{21}
}

// PartyReply 队伍名册快照（离开/未组队回执空快照）。
type PartyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Members       []*v1.PlayerSummary    `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyReply) Reset() {
	*x = PartyReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyReply) ProtoMessage() {}

func (x *PartyReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyReply.ProtoReflect.Descriptor instead.
func (*PartyReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{22}
}

func (x *PartyReply) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyReply) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *PartyReply) GetMembers() []*v1.PlayerSummary {
	if x != nil {
		return x.Members
	}
	return nil
}

// QueuePartyReq 队长发整队入队（1..N 人都可入队，等对面凑齐等量人数）。
type QueuePartyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ruleset       string                 `protobuf:"bytes,1,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuePartyReq) Reset() {
	*x = QueuePartyReq{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuePartyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePartyReq) ProtoMessage() {}

func (x *QueuePartyReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePartyReq.ProtoReflect.Descriptor instead.
func (*QueuePartyReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{23}
}

func (x *QueuePartyReq) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

type PartyQueueReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyQueueReply) Reset() {
	*x = PartyQueueReply{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyQueueReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyQueueReply) ProtoMessage() {}

func (x *PartyQueueReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyQueueReply.ProtoReflect.Descriptor instead.
func (*PartyQueueReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{24}
}

func (x *PartyQueueReply) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

// MatchStartedNotify 服务端推送：匹配成功开局通知（含 battle 实例地址）。
type MatchStartedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	BattleId      string                 `protobuf:"bytes,2,opt,name=battle_id,json=battleId,proto3" json:"battle_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,3,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartedNotify) Reset() {
	*x = MatchStartedNotify{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartedNotify) ProtoMessage() {}

func (x *MatchStartedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartedNotify.ProtoReflect.Descriptor instead.
func (*MatchStartedNotify) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{25}
}

func (x *MatchStartedNotify) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchStartedNotify) GetBattleId() string {
	if x != nil {
		return x.BattleId
	}
	return ""
}

func (x *MatchStartedNotify) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *MatchStartedNotify) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

// MatchFailedNotify 服务端推送：匹配失败/超时/取消通知。
type MatchFailedNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TicketId      string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	Reason        v11.MatchFailReason    `protobuf:"varint,2,opt,name=reason,proto3,enum=matcher.v1.MatchFailReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchFailedNotify) Reset() {
	*x = MatchFailedNotify{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchFailedNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchFailedNotify) ProtoMessage() {}

func (x *MatchFailedNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchFailedNotify.ProtoReflect.Descriptor instead.
func (*MatchFailedNotify) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{26}
}

func (x *MatchFailedNotify) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *MatchFailedNotify) GetReason() v11.MatchFailReason {
	if x != nil {
		return x.Reason
	}
	return v11.MatchFailReason(0)
}

// PartyRosterNotify 服务端推送：队伍名册变更（建队/加入/离开/解散，全队下发）。
type PartyRosterNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PlayerIds     []string               `protobuf:"bytes,3,rep,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Reason        v11.PartyRosterReason  `protobuf:"varint,4,opt,name=reason,proto3,enum=matcher.v1.PartyRosterReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyRosterNotify) Reset() {
	*x = PartyRosterNotify{}
	mi := &file_api_game_v1_player_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyRosterNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyRosterNotify) ProtoMessage() {}

func (x *PartyRosterNotify) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyRosterNotify.ProtoReflect.Descriptor instead.
func (*PartyRosterNotify) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_service_proto_rawDescGZIP(), []int{27}
}

func (x *PartyRosterNotify) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyRosterNotify) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *PartyRosterNotify) GetPlayerIds() []string {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *PartyRosterNotify) GetReason() v11.PartyRosterReason {
	if x != nil {
		return x.Reason
	}
	return v11.PartyRosterReason(0)
}

var File_api_game_v1_player_service_proto protoreflect.FileDescriptor

const file_api_game_v1_player_service_proto_rawDesc = "" +
	"\n" +
	" api/game/v1/player_service.proto\x12\agame.v1\x1a\x18api/atlas/v1/route.proto\x1a\x1aapi/common/v1/common.proto\x1a!api/matcher/v1/match_events.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x18api/game/v1/player.proto\x1a\x1capi/matcher/v1/matcher.proto\"_\n" +
	"\vRegisterReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"^\n" +
	"\rRegisterReply\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x120\n" +
	"\x06player\x18\x02 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"\x84\x01\n" +
	"\bLoginReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12)\n" +
	"\x10gateway_instance\x18\x04 \x01(\tR\x0fgatewayInstance\">\n" +
	"\n" +
	"LoginReply\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\":\n" +
	"\tLogoutMsg\x12-\n" +
	"\x06reason\x18\x01 \x01(\x0e2\x15.game.v1.LogoutReasonR\x06reason\"\x12\n" +
	"\x10GetPlayerDataReq\"\x10\n" +
	"\x0eGetBackpackReq\"p\n" +
	"\x0fPlayerDataReply\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.game.v1.BackpackItemR\x05items\"<\n" +
	"\rBackpackReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.game.v1.BackpackItemR\x05items\"U\n" +
	"\fGrantItemReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x0e\n" +
	"\fGetPlayerReq\"?\n" +
	"\vPlayerReply\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\".\n" +
	"\x12EnterMatchQueueReq\x12\x18\n" +
	"\aruleset\x18\x01 \x01(\tR\aruleset\"\x16\n" +
	"\x14EnterMatchQueueReply\"\x10\n" +
	"\x0eCancelMatchReq\".\n" +
	"\x10CancelMatchReply\x12\x1a\n" +
	"\bcanceled\x18\x01 \x01(\bR\bcanceled\"\x13\n" +
	"\x11GetMatchStatusReq\"\x95\x01\n" +
	"\x10MatchStatusReply\x12,\n" +
	"\x05state\x18\x01 \x01(\x0e2\x16.matcher.v1.MatchStateR\x05state\x12\x1b\n" +
	"\tticket_id\x18\x02 \x01(\tR\bticketId\x12\x19\n" +
	"\bmatch_id\x18\x03 \x01(\tR\amatchId\x12\x1b\n" +
	"\tbattle_id\x18\x04 \x01(\tR\bbattleId\"\x10\n" +
	"\x0eCreatePartyReq\")\n" +
	"\fJoinPartyReq\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\"\x0f\n" +
	"\rLeavePartyReq\"\r\n" +
	"\vGetPartyReq\"x\n" +
	"\n" +
	"PartyReply\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x122\n" +
	"\amembers\x18\x03 \x03(\v2\x18.common.v1.PlayerSummaryR\amembers\")\n" +
	"\rQueuePartyReq\x12\x18\n" +
	"\aruleset\x18\x01 \x01(\tR\aruleset\".\n" +
	"\x0fPartyQueueReply\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\"\x87\x01\n" +
	"\x12MatchStartedNotify\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12\x1b\n" +
	"\tbattle_id\x18\x02 \x01(\tR\bbattleId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\tR\tplayerIds\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\"e\n" +
	"\x11MatchFailedNotify\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x123\n" +
	"\x06reason\x18\x02 \x01(\x0e2\x1b.matcher.v1.MatchFailReasonR\x06reason\"\xa1\x01\n" +
	"\x11PartyRosterNotify\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\tR\tplayerIds\x125\n" +
	"\x06reason\x18\x04 \x01(\x0e2\x1d.matcher.v1.PartyRosterReasonR\x06reason*\x91\x01\n" +
	"\fLogoutReason\x12\x1d\n" +
	"\x19LOGOUT_REASON_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14LOGOUT_REASON_LOGOUT\x10\x01\x12%\n" +
	"!LOGOUT_REASON_LOGGED_IN_ELSEWHERE\x10\x02\x12!\n" +
	"\x1dLOGOUT_REASON_SESSION_EXPIRED\x10\x032\xe2\a\n" +
	"\rPlayerService\x128\n" +
	"\bRegister\x12\x14.game.v1.RegisterReq\x1a\x16.game.v1.RegisterReply\x12D\n" +
	"\rGetPlayerData\x12\x19.game.v1.GetPlayerDataReq\x1a\x18.game.v1.PlayerDataReply\x12>\n" +
	"\vGetBackpack\x12\x17.game.v1.GetBackpackReq\x1a\x16.game.v1.BackpackReply\x12M\n" +
	"\x0fEnterMatchQueue\x12\x1b.game.v1.EnterMatchQueueReq\x1a\x1d.game.v1.EnterMatchQueueReply\x12A\n" +
	"\vCancelMatch\x12\x17.game.v1.CancelMatchReq\x1a\x19.game.v1.CancelMatchReply\x12G\n" +
	"\x0eGetMatchStatus\x12\x1a.game.v1.GetMatchStatusReq\x1a\x19.game.v1.MatchStatusReply\x12;\n" +
	"\vCreateParty\x12\x17.game.v1.CreatePartyReq\x1a\x13.game.v1.PartyReply\x127\n" +
	"\tJoinParty\x12\x15.game.v1.JoinPartyReq\x1a\x13.game.v1.PartyReply\x129\n" +
	"\n" +
	"LeaveParty\x12\x16.game.v1.LeavePartyReq\x1a\x13.game.v1.PartyReply\x125\n" +
	"\bGetParty\x12\x14.game.v1.GetPartyReq\x1a\x13.game.v1.PartyReply\x12>\n" +
	"\n" +
	"QueueParty\x12\x16.game.v1.QueuePartyReq\x1a\x18.game.v1.PartyQueueReply\x127\n" +
	"\x05Login\x12\x11.game.v1.LoginReq\x1a\x13.game.v1.LoginReply\"\x06\xd2\xd5\"\x02\b\x02\x12<\n" +
	"\x06Logout\x12\x12.game.v1.LogoutMsg\x1a\x16.google.protobuf.Empty\"\x06\xd2\xd5\"\x02\b\x02\x12C\n" +
	"\tGrantItem\x12\x15.game.v1.GrantItemReq\x1a\x17.game.v1.GrantItemReply\"\x06\xd2\xd5\"\x02\b\x02\x12@\n" +
	"\tGetPlayer\x12\x15.game.v1.GetPlayerReq\x1a\x14.game.v1.PlayerReply\"\x06\xd2\xd5\"\x02\b\x02\x1a\x10\xca\xd5\"\f\n" +
	"\x06player\x10\x01\x18\x01B;Z9github.com/huangyuCN/atlas-game-layout/api/game/v1;gamev1b\x06proto3"

var (
	file_api_game_v1_player_service_proto_rawDescOnce sync.Once
	file_api_game_v1_player_service_proto_rawDescData []byte
)

func file_api_game_v1_player_service_proto_rawDescGZIP() []byte {
	file_api_game_v1_player_service_proto_rawDescOnce.Do(func() {
		file_api_game_v1_player_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_v1_player_service_proto_rawDesc), len(file_api_game_v1_player_service_proto_rawDesc)))
	})
	return file_api_game_v1_player_service_proto_rawDescData
}

var file_api_game_v1_player_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_game_v1_player_service_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_game_v1_player_service_proto_goTypes = []any{
	(LogoutReason)(0),            // 0: game.v1.LogoutReason
	(*RegisterReq)(nil),          // 1: game.v1.RegisterReq
	(*RegisterReply)(nil),        // 2: game.v1.RegisterReply
	(*LoginReq)(nil),             // 3: game.v1.LoginReq
	(*LoginReply)(nil),           // 4: game.v1.LoginReply
	(*LogoutMsg)(nil),            // 5: game.v1.LogoutMsg
	(*GetPlayerDataReq)(nil),     // 6: game.v1.GetPlayerDataReq
	(*GetBackpackReq)(nil),       // 7: game.v1.GetBackpackReq
	(*PlayerDataReply)(nil),      // 8: game.v1.PlayerDataReply
	(*BackpackReply)(nil),        // 9: game.v1.BackpackReply
	(*GrantItemReq)(nil),         // 10: game.v1.GrantItemReq
	(*GetPlayerReq)(nil),         // 11: game.v1.GetPlayerReq
	(*PlayerReply)(nil),          // 12: game.v1.PlayerReply
	(*EnterMatchQueueReq)(nil),   // 13: game.v1.EnterMatchQueueReq
	(*EnterMatchQueueReply)(nil), // 14: game.v1.EnterMatchQueueReply
	(*CancelMatchReq)(nil),       // 15: game.v1.CancelMatchReq
	(*CancelMatchReply)(nil),     // 16: game.v1.CancelMatchReply
	(*GetMatchStatusReq)(nil),    // 17: game.v1.GetMatchStatusReq
	(*MatchStatusReply)(nil),     // 18: game.v1.MatchStatusReply
	(*CreatePartyReq)(nil),       // 19: game.v1.CreatePartyReq
	(*JoinPartyReq)(nil),         // 20: game.v1.JoinPartyReq
	(*LeavePartyReq)(nil),        // 21: game.v1.LeavePartyReq
	(*GetPartyReq)(nil),          // 22: game.v1.GetPartyReq
	(*PartyReply)(nil),           // 23: game.v1.PartyReply
	(*QueuePartyReq)(nil),        // 24: game.v1.QueuePartyReq
	(*PartyQueueReply)(nil),      // 25: game.v1.PartyQueueReply
	(*MatchStartedNotify)(nil),   // 26: game.v1.MatchStartedNotify
	(*MatchFailedNotify)(nil),    // 27: game.v1.MatchFailedNotify
	(*PartyRosterNotify)(nil),    // 28: game.v1.PartyRosterNotify
	(*v1.PlayerSummary)(nil),     // 29: common.v1.PlayerSummary
	(*BackpackItem)(nil),         // 30: game.v1.BackpackItem
	(v11.MatchState)(0),          // 31: matcher.v1.MatchState
	(v11.MatchFailReason)(0),     // 32: matcher.v1.MatchFailReason
	(v11.PartyRosterReason)(0),   // 33: matcher.v1.PartyRosterReason
	(*emptypb.Empty)(nil),        // 34: google.protobuf.Empty
	(*GrantItemReply)(nil),       // 35: game.v1.GrantItemReply
}
var file_api_game_v1_player_service_proto_depIdxs = []int32{
	29, // 0: game.v1.RegisterReply.player:type_name -> common.v1.PlayerSummary
	29, // 1: game.v1.LoginReply.player:type_name -> common.v1.PlayerSummary
	0,  // 2: game.v1.LogoutMsg.reason:type_name -> game.v1.LogoutReason
	29, // 3: game.v1.PlayerDataReply.player:type_name -> common.v1.PlayerSummary
	30, // 4: game.v1.PlayerDataReply.items:type_name -> game.v1.BackpackItem
	30, // 5: game.v1.BackpackReply.items:type_name -> game.v1.BackpackItem
	29, // 6: game.v1.PlayerReply.player:type_name -> common.v1.PlayerSummary
	31, // 7: game.v1.MatchStatusReply.state:type_name -> matcher.v1.MatchState
	29, // 8: game.v1.PartyReply.members:type_name -> common.v1.PlayerSummary
	32, // 9: game.v1.MatchFailedNotify.reason:type_name -> matcher.v1.MatchFailReason
	33, // 10: game.v1.PartyRosterNotify.reason:type_name -> matcher.v1.PartyRosterReason
	1,  // 11: game.v1.PlayerService.Register:input_type -> game.v1.RegisterReq
	6,  // 12: game.v1.PlayerService.GetPlayerData:input_type -> game.v1.GetPlayerDataReq
	7,  // 13: game.v1.PlayerService.GetBackpack:input_type -> game.v1.GetBackpackReq
	13, // 14: game.v1.PlayerService.EnterMatchQueue:input_type -> game.v1.EnterMatchQueueReq
	15, // 15: game.v1.PlayerService.CancelMatch:input_type -> game.v1.CancelMatchReq
	17, // 16: game.v1.PlayerService.GetMatchStatus:input_type -> game.v1.GetMatchStatusReq
	19, // 17: game.v1.PlayerService.CreateParty:input_type -> game.v1.CreatePartyReq
	20, // 18: game.v1.PlayerService.JoinParty:input_type -> game.v1.JoinPartyReq
	21, // 19: game.v1.PlayerService.LeaveParty:input_type -> game.v1.LeavePartyReq
	22, // 20: game.v1.PlayerService.GetParty:input_type -> game.v1.GetPartyReq
	24, // 21: game.v1.PlayerService.QueueParty:input_type -> game.v1.QueuePartyReq
	3,  // 22: game.v1.PlayerService.Login:input_type -> game.v1.LoginReq
	5,  // 23: game.v1.PlayerService.Logout:input_type -> game.v1.LogoutMsg
	10, // 24: game.v1.PlayerService.GrantItem:input_type -> game.v1.GrantItemReq
	11, // 25: game.v1.PlayerService.GetPlayer:input_type -> game.v1.GetPlayerReq
	2,  // 26: game.v1.PlayerService.Register:output_type -> game.v1.RegisterReply
	8,  // 27: game.v1.PlayerService.GetPlayerData:output_type -> game.v1.PlayerDataReply
	9,  // 28: game.v1.PlayerService.GetBackpack:output_type -> game.v1.BackpackReply
	14, // 29: game.v1.PlayerService.EnterMatchQueue:output_type -> game.v1.EnterMatchQueueReply
	16, // 30: game.v1.PlayerService.CancelMatch:output_type -> game.v1.CancelMatchReply
	18, // 31: game.v1.PlayerService.GetMatchStatus:output_type -> game.v1.MatchStatusReply
	23, // 32: game.v1.PlayerService.CreateParty:output_type -> game.v1.PartyReply
	23, // 33: game.v1.PlayerService.JoinParty:output_type -> game.v1.PartyReply
	23, // 34: game.v1.PlayerService.LeaveParty:output_type -> game.v1.PartyReply
	23, // 35: game.v1.PlayerService.GetParty:output_type -> game.v1.PartyReply
	25, // 36: game.v1.PlayerService.QueueParty:output_type -> game.v1.PartyQueueReply
	4,  // 37: game.v1.PlayerService.Login:output_type -> game.v1.LoginReply
	34, // 38: game.v1.PlayerService.Logout:output_type -> google.protobuf.Empty
	35, // 39: game.v1.PlayerService.GrantItem:output_type -> game.v1.GrantItemReply
	12, // 40: game.v1.PlayerService.GetPlayer:output_type -> game.v1.PlayerReply
	26, // [26:41] is the sub-list for method output_type
	11, // [11:26] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_game_v1_player_service_proto_init() }
func file_api_game_v1_player_service_proto_init() {
	if File_api_game_v1_player_service_proto != nil {
		return
	}
	file_api_game_v1_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_v1_player_service_proto_rawDesc), len(file_api_game_v1_player_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_game_v1_player_service_proto_goTypes,
		DependencyIndexes: file_api_game_v1_player_service_proto_depIdxs,
		EnumInfos:         file_api_game_v1_player_service_proto_enumTypes,
		MessageInfos:      file_api_game_v1_player_service_proto_msgTypes,
	}.Build()
	File_api_game_v1_player_service_proto = out.File
	file_api_game_v1_player_service_proto_goTypes = nil
	file_api_game_v1_player_service_proto_depIdxs = nil
}
