// game 服务协议：grpc 服务（gateway/管理调用）与 actor 消息载体
// （注册/登录经 actor 远程路由 + 懒激活投递到 PlayerActor）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/game/v1/player.proto

package gamev1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginActorReq 是 PlayerActor 的登录/注册消息（actor Ask 载荷）。
type LoginActorReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Account         string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	GatewayInstance string                 `protobuf:"bytes,3,opt,name=gateway_instance,json=gatewayInstance,proto3" json:"gateway_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginActorReq) Reset() {
	*x = LoginActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginActorReq) ProtoMessage() {}

func (x *LoginActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginActorReq.ProtoReflect.Descriptor instead.
func (*LoginActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *LoginActorReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginActorReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginActorReq) GetGatewayInstance() string {
	if x != nil {
		return x.GatewayInstance
	}
	return ""
}

type LoginActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginActorReply) Reset() {
	*x = LoginActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginActorReply) ProtoMessage() {}

func (x *LoginActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginActorReply.ProtoReflect.Descriptor instead.
func (*LoginActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *LoginActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginActorReply) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *LoginActorReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// GetPlayerRequest/Reply 玩家信息查询。
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerReply) Reset() {
	*x = GetPlayerReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReply) ProtoMessage() {}

func (x *GetPlayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReply.ProtoReflect.Descriptor instead.
func (*GetPlayerReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *GetPlayerReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// BackpackItem 背包条目（示例业务：M5 背包 handler 使用）。
type BackpackItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackpackItem) Reset() {
	*x = BackpackItem{}
	mi := &file_api_game_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpackItem) ProtoMessage() {}

func (x *BackpackItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpackItem.ProtoReflect.Descriptor instead.
func (*BackpackItem) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *BackpackItem) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BackpackItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetBackpackRequest/Reply 背包查询。
type GetBackpackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackRequest) Reset() {
	*x = GetBackpackRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackRequest) ProtoMessage() {}

func (x *GetBackpackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackRequest.ProtoReflect.Descriptor instead.
func (*GetBackpackRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{5}
}

func (x *GetBackpackRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetBackpackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BackpackItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackReply) Reset() {
	*x = GetBackpackReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackReply) ProtoMessage() {}

func (x *GetBackpackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackReply.ProtoReflect.Descriptor instead.
func (*GetBackpackReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{6}
}

func (x *GetBackpackReply) GetItems() []*BackpackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GrantItemRequest/Reply 发道具（管理/活动渠道）。
type GrantItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // 发放原因（审计）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemRequest) Reset() {
	*x = GrantItemRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemRequest) ProtoMessage() {}

func (x *GrantItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemRequest.ProtoReflect.Descriptor instead.
func (*GrantItemRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{7}
}

func (x *GrantItemRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GrantItemRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GrantItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GrantItemRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GrantItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemReply) Reset() {
	*x = GrantItemReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemReply) ProtoMessage() {}

func (x *GrantItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemReply.ProtoReflect.Descriptor instead.
func (*GrantItemReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{8}
}

var File_api_game_v1_player_proto protoreflect.FileDescriptor

const file_api_game_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x18api/game/v1/player.proto\x12\agame.v1\x1a\x1aapi/common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"j\n" +
	"\rLoginActorReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12)\n" +
	"\x10gateway_instance\x18\x03 \x01(\tR\x0fgatewayInstance\"v\n" +
	"\x0fLoginActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\x120\n" +
	"\x06player\x18\x03 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"/\n" +
	"\x10GetPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"B\n" +
	"\x0eGetPlayerReply\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"=\n" +
	"\fBackpackItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"1\n" +
	"\x12GetBackpackRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"?\n" +
	"\x10GetBackpackReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.game.v1.BackpackItemR\x05items\"v\n" +
	"\x10GrantItemRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x10\n" +
	"\x0eGrantItemReply2\xc6\x02\n" +
	"\x06Player\x12`\n" +
	"\tGetPlayer\x12\x19.game.v1.GetPlayerRequest\x1a\x17.game.v1.GetPlayerReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/players/{player_id}\x12o\n" +
	"\vGetBackpack\x12\x1b.game.v1.GetBackpackRequest\x1a\x19.game.v1.GetBackpackReply\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/players/{player_id}/backpack\x12i\n" +
	"\tGrantItem\x12\x19.game.v1.GrantItemRequest\x1a\x17.game.v1.GrantItemReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/players/{player_id}/itemsB;Z9github.com/huangyuCN/atlas-game-layout/api/game/v1;gamev1b\x06proto3"

var (
	file_api_game_v1_player_proto_rawDescOnce sync.Once
	file_api_game_v1_player_proto_rawDescData []byte
)

func file_api_game_v1_player_proto_rawDescGZIP() []byte {
	file_api_game_v1_player_proto_rawDescOnce.Do(func() {
		file_api_game_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_v1_player_proto_rawDesc), len(file_api_game_v1_player_proto_rawDesc)))
	})
	return file_api_game_v1_player_proto_rawDescData
}

var file_api_game_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_game_v1_player_proto_goTypes = []any{
	(*LoginActorReq)(nil),      // 0: game.v1.LoginActorReq
	(*LoginActorReply)(nil),    // 1: game.v1.LoginActorReply
	(*GetPlayerRequest)(nil),   // 2: game.v1.GetPlayerRequest
	(*GetPlayerReply)(nil),     // 3: game.v1.GetPlayerReply
	(*BackpackItem)(nil),       // 4: game.v1.BackpackItem
	(*GetBackpackRequest)(nil), // 5: game.v1.GetBackpackRequest
	(*GetBackpackReply)(nil),   // 6: game.v1.GetBackpackReply
	(*GrantItemRequest)(nil),   // 7: game.v1.GrantItemRequest
	(*GrantItemReply)(nil),     // 8: game.v1.GrantItemReply
	(*v1.PlayerSummary)(nil),   // 9: common.v1.PlayerSummary
}
var file_api_game_v1_player_proto_depIdxs = []int32{
	9, // 0: game.v1.LoginActorReply.player:type_name -> common.v1.PlayerSummary
	9, // 1: game.v1.GetPlayerReply.player:type_name -> common.v1.PlayerSummary
	4, // 2: game.v1.GetBackpackReply.items:type_name -> game.v1.BackpackItem
	2, // 3: game.v1.Player.GetPlayer:input_type -> game.v1.GetPlayerRequest
	5, // 4: game.v1.Player.GetBackpack:input_type -> game.v1.GetBackpackRequest
	7, // 5: game.v1.Player.GrantItem:input_type -> game.v1.GrantItemRequest
	3, // 6: game.v1.Player.GetPlayer:output_type -> game.v1.GetPlayerReply
	6, // 7: game.v1.Player.GetBackpack:output_type -> game.v1.GetBackpackReply
	8, // 8: game.v1.Player.GrantItem:output_type -> game.v1.GrantItemReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_game_v1_player_proto_init() }
func file_api_game_v1_player_proto_init() {
	if File_api_game_v1_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_v1_player_proto_rawDesc), len(file_api_game_v1_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_game_v1_player_proto_goTypes,
		DependencyIndexes: file_api_game_v1_player_proto_depIdxs,
		MessageInfos:      file_api_game_v1_player_proto_msgTypes,
	}.Build()
	File_api_game_v1_player_proto = out.File
	file_api_game_v1_player_proto_goTypes = nil
	file_api_game_v1_player_proto_depIdxs = nil
}
