// game 服务协议：grpc 服务（gateway/管理调用）与 actor 消息载体
// （注册/登录经 actor 远程路由 + 懒激活投递到 PlayerActor）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.26.1
// source: api/game/v1/player.proto

package gamev1

import (
	v1 "github.com/huangyuCN/atlas-game-layout/api/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterActorReq 是 PlayerActor 的注册消息（注册与登录两段式，D8/D9）：
// 玩家数据不存在则创建并回执，客户端仍需 Login 建立会话。
type RegisterActorReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Account         string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname        string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	GatewayInstance string                 `protobuf:"bytes,4,opt,name=gateway_instance,json=gatewayInstance,proto3" json:"gateway_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterActorReq) Reset() {
	*x = RegisterActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActorReq) ProtoMessage() {}

func (x *RegisterActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActorReq.ProtoReflect.Descriptor instead.
func (*RegisterActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterActorReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *RegisterActorReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterActorReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterActorReq) GetGatewayInstance() string {
	if x != nil {
		return x.GatewayInstance
	}
	return ""
}

type RegisterActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	PlayerId      string                 `protobuf:"bytes,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,4,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterActorReply) Reset() {
	*x = RegisterActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterActorReply) ProtoMessage() {}

func (x *RegisterActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterActorReply.ProtoReflect.Descriptor instead.
func (*RegisterActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterActorReply) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *RegisterActorReply) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RegisterActorReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// LoginActorReq 是 PlayerActor 的登录消息（actor Ask 载荷）。
// 玩家 ID 由注册回执获得（注册与登录两段式，D8）；token 由 gateway 预签发；
// PlayerActor 校验玩家数据并做会话令牌裁决（D10 兜底）。
type LoginActorReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PlayerId        string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Token           string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	GatewayInstance string                 `protobuf:"bytes,4,opt,name=gateway_instance,json=gatewayInstance,proto3" json:"gateway_instance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LoginActorReq) Reset() {
	*x = LoginActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginActorReq) ProtoMessage() {}

func (x *LoginActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginActorReq.ProtoReflect.Descriptor instead.
func (*LoginActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *LoginActorReq) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LoginActorReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginActorReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginActorReq) GetGatewayInstance() string {
	if x != nil {
		return x.GatewayInstance
	}
	return ""
}

type LoginActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginActorReply) Reset() {
	*x = LoginActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginActorReply) ProtoMessage() {}

func (x *LoginActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginActorReply.ProtoReflect.Descriptor instead.
func (*LoginActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{3}
}

func (x *LoginActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginActorReply) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *LoginActorReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// LogoutActorMsg 是 PlayerActor 的登出/挤下线退出消息（Tell 载荷）：
// PlayerActor 校验令牌后停止自身（Locator 移除，D10 联动）。
type LogoutActorMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutActorMsg) Reset() {
	*x = LogoutActorMsg{}
	mi := &file_api_game_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutActorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutActorMsg) ProtoMessage() {}

func (x *LogoutActorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutActorMsg.ProtoReflect.Descriptor instead.
func (*LogoutActorMsg) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutActorMsg) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LogoutActorMsg) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// GrantItemActorReq 背包发放（经 PlayerActor 聚合根 undo 写，grpc 转发）。
type GrantItemActorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemActorReq) Reset() {
	*x = GrantItemActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemActorReq) ProtoMessage() {}

func (x *GrantItemActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemActorReq.ProtoReflect.Descriptor instead.
func (*GrantItemActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{5}
}

func (x *GrantItemActorReq) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GrantItemActorReq) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GrantItemActorReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GrantItemActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemActorReply) Reset() {
	*x = GrantItemActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemActorReply) ProtoMessage() {}

func (x *GrantItemActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemActorReply.ProtoReflect.Descriptor instead.
func (*GrantItemActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{6}
}

func (x *GrantItemActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GrantItemActorReply) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

// GetBackpackActorReq/Reply 背包查询（聚合根内存快照，grpc 转发）。
type GetBackpackActorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackActorReq) Reset() {
	*x = GetBackpackActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackActorReq) ProtoMessage() {}

func (x *GetBackpackActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackActorReq.ProtoReflect.Descriptor instead.
func (*GetBackpackActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{7}
}

type GetBackpackActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Items         []*BackpackItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackActorReply) Reset() {
	*x = GetBackpackActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackActorReply) ProtoMessage() {}

func (x *GetBackpackActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackActorReply.ProtoReflect.Descriptor instead.
func (*GetBackpackActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{8}
}

func (x *GetBackpackActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetBackpackActorReply) GetItems() []*BackpackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GetPlayerActorReq/Reply 玩家摘要查询（聚合根内存快照，grpc 转发）。
type GetPlayerActorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerActorReq) Reset() {
	*x = GetPlayerActorReq{}
	mi := &file_api_game_v1_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerActorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerActorReq) ProtoMessage() {}

func (x *GetPlayerActorReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerActorReq.ProtoReflect.Descriptor instead.
func (*GetPlayerActorReq) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{9}
}

type GetPlayerActorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerActorReply) Reset() {
	*x = GetPlayerActorReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerActorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerActorReply) ProtoMessage() {}

func (x *GetPlayerActorReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerActorReply.ProtoReflect.Descriptor instead.
func (*GetPlayerActorReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerActorReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetPlayerActorReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// PlayerActorMsg 是 PlayerActor 的消息信封：跨节点传输的 payload 为
// 序列化字节（集群约定），oneof 区分具体消息类型。
type PlayerActorMsg struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*PlayerActorMsg_Register
	//	*PlayerActorMsg_Login
	//	*PlayerActorMsg_Logout
	//	*PlayerActorMsg_GrantItem
	//	*PlayerActorMsg_GetBackpack
	//	*PlayerActorMsg_GetPlayer
	Kind          isPlayerActorMsg_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerActorMsg) Reset() {
	*x = PlayerActorMsg{}
	mi := &file_api_game_v1_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerActorMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerActorMsg) ProtoMessage() {}

func (x *PlayerActorMsg) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerActorMsg.ProtoReflect.Descriptor instead.
func (*PlayerActorMsg) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerActorMsg) GetKind() isPlayerActorMsg_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *PlayerActorMsg) GetRegister() *RegisterActorReq {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *PlayerActorMsg) GetLogin() *LoginActorReq {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_Login); ok {
			return x.Login
		}
	}
	return nil
}

func (x *PlayerActorMsg) GetLogout() *LogoutActorMsg {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_Logout); ok {
			return x.Logout
		}
	}
	return nil
}

func (x *PlayerActorMsg) GetGrantItem() *GrantItemActorReq {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_GrantItem); ok {
			return x.GrantItem
		}
	}
	return nil
}

func (x *PlayerActorMsg) GetGetBackpack() *GetBackpackActorReq {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_GetBackpack); ok {
			return x.GetBackpack
		}
	}
	return nil
}

func (x *PlayerActorMsg) GetGetPlayer() *GetPlayerActorReq {
	if x != nil {
		if x, ok := x.Kind.(*PlayerActorMsg_GetPlayer); ok {
			return x.GetPlayer
		}
	}
	return nil
}

type isPlayerActorMsg_Kind interface {
	isPlayerActorMsg_Kind()
}

type PlayerActorMsg_Register struct {
	Register *RegisterActorReq `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type PlayerActorMsg_Login struct {
	Login *LoginActorReq `protobuf:"bytes,2,opt,name=login,proto3,oneof"`
}

type PlayerActorMsg_Logout struct {
	Logout *LogoutActorMsg `protobuf:"bytes,3,opt,name=logout,proto3,oneof"`
}

type PlayerActorMsg_GrantItem struct {
	GrantItem *GrantItemActorReq `protobuf:"bytes,4,opt,name=grant_item,json=grantItem,proto3,oneof"`
}

type PlayerActorMsg_GetBackpack struct {
	GetBackpack *GetBackpackActorReq `protobuf:"bytes,5,opt,name=get_backpack,json=getBackpack,proto3,oneof"`
}

type PlayerActorMsg_GetPlayer struct {
	GetPlayer *GetPlayerActorReq `protobuf:"bytes,6,opt,name=get_player,json=getPlayer,proto3,oneof"`
}

func (*PlayerActorMsg_Register) isPlayerActorMsg_Kind() {}

func (*PlayerActorMsg_Login) isPlayerActorMsg_Kind() {}

func (*PlayerActorMsg_Logout) isPlayerActorMsg_Kind() {}

func (*PlayerActorMsg_GrantItem) isPlayerActorMsg_Kind() {}

func (*PlayerActorMsg_GetBackpack) isPlayerActorMsg_Kind() {}

func (*PlayerActorMsg_GetPlayer) isPlayerActorMsg_Kind() {}

// GetPlayerRequest/Reply 玩家信息查询。
type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{12}
}

func (x *GetPlayerRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *v1.PlayerSummary      `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerReply) Reset() {
	*x = GetPlayerReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerReply) ProtoMessage() {}

func (x *GetPlayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerReply.ProtoReflect.Descriptor instead.
func (*GetPlayerReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{13}
}

func (x *GetPlayerReply) GetPlayer() *v1.PlayerSummary {
	if x != nil {
		return x.Player
	}
	return nil
}

// BackpackItem 背包条目（示例业务：M5 背包 handler 使用）。
type BackpackItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackpackItem) Reset() {
	*x = BackpackItem{}
	mi := &file_api_game_v1_player_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpackItem) ProtoMessage() {}

func (x *BackpackItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpackItem.ProtoReflect.Descriptor instead.
func (*BackpackItem) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{14}
}

func (x *BackpackItem) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BackpackItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetBackpackRequest/Reply 背包查询。
type GetBackpackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackRequest) Reset() {
	*x = GetBackpackRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackRequest) ProtoMessage() {}

func (x *GetBackpackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackRequest.ProtoReflect.Descriptor instead.
func (*GetBackpackRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{15}
}

func (x *GetBackpackRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetBackpackReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BackpackItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBackpackReply) Reset() {
	*x = GetBackpackReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBackpackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackpackReply) ProtoMessage() {}

func (x *GetBackpackReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackpackReply.ProtoReflect.Descriptor instead.
func (*GetBackpackReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{16}
}

func (x *GetBackpackReply) GetItems() []*BackpackItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// GrantItemRequest/Reply 发道具（管理/活动渠道）。
type GrantItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Count         uint32                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"` // 发放原因（审计）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemRequest) Reset() {
	*x = GrantItemRequest{}
	mi := &file_api_game_v1_player_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemRequest) ProtoMessage() {}

func (x *GrantItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemRequest.ProtoReflect.Descriptor instead.
func (*GrantItemRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{17}
}

func (x *GrantItemRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GrantItemRequest) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GrantItemRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GrantItemRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GrantItemReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrantItemReply) Reset() {
	*x = GrantItemReply{}
	mi := &file_api_game_v1_player_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantItemReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantItemReply) ProtoMessage() {}

func (x *GrantItemReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_player_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantItemReply.ProtoReflect.Descriptor instead.
func (*GrantItemReply) Descriptor() ([]byte, []int) {
	return file_api_game_v1_player_proto_rawDescGZIP(), []int{18}
}

var File_api_game_v1_player_proto protoreflect.FileDescriptor

const file_api_game_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x18api/game/v1/player.proto\x12\agame.v1\x1a\x1aapi/common/v1/common.proto\x1a\x1cgoogle/api/annotations.proto\"\x8f\x01\n" +
	"\x10RegisterActorReq\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12)\n" +
	"\x10gateway_instance\x18\x04 \x01(\tR\x0fgatewayInstance\"\x96\x01\n" +
	"\x12RegisterActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\tR\bplayerId\x120\n" +
	"\x06player\x18\x04 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"\x89\x01\n" +
	"\rLoginActorReq\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12)\n" +
	"\x10gateway_instance\x18\x04 \x01(\tR\x0fgatewayInstance\"v\n" +
	"\x0fLoginActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\x120\n" +
	"\x06player\x18\x03 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\">\n" +
	"\x0eLogoutActorMsg\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Z\n" +
	"\x11GrantItemActorReq\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"H\n" +
	"\x13GrantItemActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\"\x15\n" +
	"\x13GetBackpackActorReq\"T\n" +
	"\x15GetBackpackActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12+\n" +
	"\x05items\x18\x02 \x03(\v2\x15.game.v1.BackpackItemR\x05items\"\x13\n" +
	"\x11GetPlayerActorReq\"W\n" +
	"\x13GetPlayerActorReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x120\n" +
	"\x06player\x18\x02 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"\xf1\x02\n" +
	"\x0ePlayerActorMsg\x127\n" +
	"\bregister\x18\x01 \x01(\v2\x19.game.v1.RegisterActorReqH\x00R\bregister\x12.\n" +
	"\x05login\x18\x02 \x01(\v2\x16.game.v1.LoginActorReqH\x00R\x05login\x121\n" +
	"\x06logout\x18\x03 \x01(\v2\x17.game.v1.LogoutActorMsgH\x00R\x06logout\x12;\n" +
	"\n" +
	"grant_item\x18\x04 \x01(\v2\x1a.game.v1.GrantItemActorReqH\x00R\tgrantItem\x12A\n" +
	"\fget_backpack\x18\x05 \x01(\v2\x1c.game.v1.GetBackpackActorReqH\x00R\vgetBackpack\x12;\n" +
	"\n" +
	"get_player\x18\x06 \x01(\v2\x1a.game.v1.GetPlayerActorReqH\x00R\tgetPlayerB\x06\n" +
	"\x04kind\"/\n" +
	"\x10GetPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"B\n" +
	"\x0eGetPlayerReply\x120\n" +
	"\x06player\x18\x01 \x01(\v2\x18.common.v1.PlayerSummaryR\x06player\"=\n" +
	"\fBackpackItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"1\n" +
	"\x12GetBackpackRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"?\n" +
	"\x10GetBackpackReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.game.v1.BackpackItemR\x05items\"v\n" +
	"\x10GrantItemRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\rR\x06itemId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\rR\x05count\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x10\n" +
	"\x0eGrantItemReply2\xc6\x02\n" +
	"\x06Player\x12`\n" +
	"\tGetPlayer\x12\x19.game.v1.GetPlayerRequest\x1a\x17.game.v1.GetPlayerReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/players/{player_id}\x12o\n" +
	"\vGetBackpack\x12\x1b.game.v1.GetBackpackRequest\x1a\x19.game.v1.GetBackpackReply\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/players/{player_id}/backpack\x12i\n" +
	"\tGrantItem\x12\x19.game.v1.GrantItemRequest\x1a\x17.game.v1.GrantItemReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/players/{player_id}/itemsB;Z9github.com/huangyuCN/atlas-game-layout/api/game/v1;gamev1b\x06proto3"

var (
	file_api_game_v1_player_proto_rawDescOnce sync.Once
	file_api_game_v1_player_proto_rawDescData []byte
)

func file_api_game_v1_player_proto_rawDescGZIP() []byte {
	file_api_game_v1_player_proto_rawDescOnce.Do(func() {
		file_api_game_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_v1_player_proto_rawDesc), len(file_api_game_v1_player_proto_rawDesc)))
	})
	return file_api_game_v1_player_proto_rawDescData
}

var file_api_game_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_api_game_v1_player_proto_goTypes = []any{
	(*RegisterActorReq)(nil),      // 0: game.v1.RegisterActorReq
	(*RegisterActorReply)(nil),    // 1: game.v1.RegisterActorReply
	(*LoginActorReq)(nil),         // 2: game.v1.LoginActorReq
	(*LoginActorReply)(nil),       // 3: game.v1.LoginActorReply
	(*LogoutActorMsg)(nil),        // 4: game.v1.LogoutActorMsg
	(*GrantItemActorReq)(nil),     // 5: game.v1.GrantItemActorReq
	(*GrantItemActorReply)(nil),   // 6: game.v1.GrantItemActorReply
	(*GetBackpackActorReq)(nil),   // 7: game.v1.GetBackpackActorReq
	(*GetBackpackActorReply)(nil), // 8: game.v1.GetBackpackActorReply
	(*GetPlayerActorReq)(nil),     // 9: game.v1.GetPlayerActorReq
	(*GetPlayerActorReply)(nil),   // 10: game.v1.GetPlayerActorReply
	(*PlayerActorMsg)(nil),        // 11: game.v1.PlayerActorMsg
	(*GetPlayerRequest)(nil),      // 12: game.v1.GetPlayerRequest
	(*GetPlayerReply)(nil),        // 13: game.v1.GetPlayerReply
	(*BackpackItem)(nil),          // 14: game.v1.BackpackItem
	(*GetBackpackRequest)(nil),    // 15: game.v1.GetBackpackRequest
	(*GetBackpackReply)(nil),      // 16: game.v1.GetBackpackReply
	(*GrantItemRequest)(nil),      // 17: game.v1.GrantItemRequest
	(*GrantItemReply)(nil),        // 18: game.v1.GrantItemReply
	(*v1.PlayerSummary)(nil),      // 19: common.v1.PlayerSummary
}
var file_api_game_v1_player_proto_depIdxs = []int32{
	19, // 0: game.v1.RegisterActorReply.player:type_name -> common.v1.PlayerSummary
	19, // 1: game.v1.LoginActorReply.player:type_name -> common.v1.PlayerSummary
	14, // 2: game.v1.GetBackpackActorReply.items:type_name -> game.v1.BackpackItem
	19, // 3: game.v1.GetPlayerActorReply.player:type_name -> common.v1.PlayerSummary
	0,  // 4: game.v1.PlayerActorMsg.register:type_name -> game.v1.RegisterActorReq
	2,  // 5: game.v1.PlayerActorMsg.login:type_name -> game.v1.LoginActorReq
	4,  // 6: game.v1.PlayerActorMsg.logout:type_name -> game.v1.LogoutActorMsg
	5,  // 7: game.v1.PlayerActorMsg.grant_item:type_name -> game.v1.GrantItemActorReq
	7,  // 8: game.v1.PlayerActorMsg.get_backpack:type_name -> game.v1.GetBackpackActorReq
	9,  // 9: game.v1.PlayerActorMsg.get_player:type_name -> game.v1.GetPlayerActorReq
	19, // 10: game.v1.GetPlayerReply.player:type_name -> common.v1.PlayerSummary
	14, // 11: game.v1.GetBackpackReply.items:type_name -> game.v1.BackpackItem
	12, // 12: game.v1.Player.GetPlayer:input_type -> game.v1.GetPlayerRequest
	15, // 13: game.v1.Player.GetBackpack:input_type -> game.v1.GetBackpackRequest
	17, // 14: game.v1.Player.GrantItem:input_type -> game.v1.GrantItemRequest
	13, // 15: game.v1.Player.GetPlayer:output_type -> game.v1.GetPlayerReply
	16, // 16: game.v1.Player.GetBackpack:output_type -> game.v1.GetBackpackReply
	18, // 17: game.v1.Player.GrantItem:output_type -> game.v1.GrantItemReply
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_game_v1_player_proto_init() }
func file_api_game_v1_player_proto_init() {
	if File_api_game_v1_player_proto != nil {
		return
	}
	file_api_game_v1_player_proto_msgTypes[11].OneofWrappers = []any{
		(*PlayerActorMsg_Register)(nil),
		(*PlayerActorMsg_Login)(nil),
		(*PlayerActorMsg_Logout)(nil),
		(*PlayerActorMsg_GrantItem)(nil),
		(*PlayerActorMsg_GetBackpack)(nil),
		(*PlayerActorMsg_GetPlayer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_v1_player_proto_rawDesc), len(file_api_game_v1_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_game_v1_player_proto_goTypes,
		DependencyIndexes: file_api_game_v1_player_proto_depIdxs,
		MessageInfos:      file_api_game_v1_player_proto_msgTypes,
	}.Build()
	File_api_game_v1_player_proto = out.File
	file_api_game_v1_player_proto_goTypes = nil
	file_api_game_v1_player_proto_depIdxs = nil
}
