// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/game/v1/player_service.proto

package gamev1rpc

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/game/v1"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// PlayerServiceClient 是 PlayerService 服务面的类型化 gRPC 客户端（跨服务调用）。
type PlayerServiceClient interface {
	Register(ctx context.Context, req *v1.RegisterReq) (*v1.RegisterReply, error)
	Login(ctx context.Context, req *v1.LoginReq) (*v1.LoginReply, error)
	Logout(ctx context.Context, req *v1.LogoutMsg) (*emptypb.Empty, error)
	GrantItem(ctx context.Context, req *v1.GrantItemReq) (*v1.GrantItemReply, error)
	GetPlayer(ctx context.Context, req *v1.GetPlayerReq) (*v1.PlayerReply, error)
}

// playerServiceClient 是客户端实现。
type playerServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewPlayerServiceClient 基于连接创建类型化客户端。
func NewPlayerServiceClient(cc grpc.ClientConnInterface) PlayerServiceClient {
	return &playerServiceClient{cc: cc}
}

// Register 发起一次一元调用。
func (c *playerServiceClient) Register(ctx context.Context, req *v1.RegisterReq) (*v1.RegisterReply, error) {
	out := new(v1.RegisterReply)
	if err := c.cc.Invoke(ctx, "/game.v1.PlayerService/Register", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Login 发起一次一元调用。
func (c *playerServiceClient) Login(ctx context.Context, req *v1.LoginReq) (*v1.LoginReply, error) {
	out := new(v1.LoginReply)
	if err := c.cc.Invoke(ctx, "/game.v1.PlayerService/Login", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// Logout 发起一次一元调用。
func (c *playerServiceClient) Logout(ctx context.Context, req *v1.LogoutMsg) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	if err := c.cc.Invoke(ctx, "/game.v1.PlayerService/Logout", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// GrantItem 发起一次一元调用。
func (c *playerServiceClient) GrantItem(ctx context.Context, req *v1.GrantItemReq) (*v1.GrantItemReply, error) {
	out := new(v1.GrantItemReply)
	if err := c.cc.Invoke(ctx, "/game.v1.PlayerService/GrantItem", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetPlayer 发起一次一元调用。
func (c *playerServiceClient) GetPlayer(ctx context.Context, req *v1.GetPlayerReq) (*v1.PlayerReply, error) {
	out := new(v1.PlayerReply)
	if err := c.cc.Invoke(ctx, "/game.v1.PlayerService/GetPlayer", req, out); err != nil {
		return nil, err
	}
	return out, nil
}
