// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/game/v1/player_service.proto

package gamev1rpc

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/game/v1"
	core "github.com/huangyuCN/atlas/contrib/actor/core"
	opcall "github.com/huangyuCN/atlas/contrib/actor/opcall"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// PlayerServiceInternal 是 PlayerService 的服务面（access=INTERNAL，服务间经 gRPC 调用）。
type PlayerServiceInternal interface {
	Login(ctx context.Context, req *v1.LoginReq) (*v1.LoginReply, error)
	Logout(ctx context.Context, req *v1.LogoutMsg) (*emptypb.Empty, error)
	GrantItem(ctx context.Context, req *v1.GrantItemReq) (*v1.GrantItemReply, error)
	GetPlayer(ctx context.Context, req *v1.GetPlayerReq) (*v1.PlayerReply, error)
}

// RegisterPlayerServiceInternal 把服务面（access=INTERNAL，服务间经 gRPC 调用）注册到 gRPC server。
// 形参类型即本面接口：把另一个面的实现注册进来在编译期即失败（类型级隔离）。
func RegisterPlayerServiceInternal(s grpc.ServiceRegistrar, impl PlayerServiceInternal) {
	s.RegisterService(&playerServiceInternalDesc, impl)
}

// playerServiceInternalDesc 是 PlayerServiceInternal 的 gRPC 服务描述（Methods 取自本面方法集）。
var playerServiceInternalDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.PlayerService",
	HandlerType: (*PlayerServiceInternal)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Login", Handler: handlePlayerServiceInternalLogin},
		{MethodName: "Logout", Handler: handlePlayerServiceInternalLogout},
		{MethodName: "GrantItem", Handler: handlePlayerServiceInternalGrantItem},
		{MethodName: "GetPlayer", Handler: handlePlayerServiceInternalGetPlayer},
	},
	Metadata: "api/game/v1/player_service.proto",
}

// handlePlayerServiceInternalLogin 解包请求并经拦截器调用本面实现。
func handlePlayerServiceInternalLogin(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.LoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceInternal).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/Login"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceInternal).Login(ctx, req.(*v1.LoginReq))
	})
}

// handlePlayerServiceInternalLogout 解包请求并经拦截器调用本面实现。
func handlePlayerServiceInternalLogout(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.LogoutMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceInternal).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/Logout"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceInternal).Logout(ctx, req.(*v1.LogoutMsg))
	})
}

// handlePlayerServiceInternalGrantItem 解包请求并经拦截器调用本面实现。
func handlePlayerServiceInternalGrantItem(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GrantItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceInternal).GrantItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GrantItem"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceInternal).GrantItem(ctx, req.(*v1.GrantItemReq))
	})
}

// handlePlayerServiceInternalGetPlayer 解包请求并经拦截器调用本面实现。
func handlePlayerServiceInternalGetPlayer(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetPlayerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceInternal).GetPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GetPlayer"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceInternal).GetPlayer(ctx, req.(*v1.GetPlayerReq))
	})
}

// NewPlayerServiceInternal 返回 actor 支撑的服务面（access=INTERNAL，服务间经 gRPC 调用）默认实现：
// 按路由条目解析目标 PID（会话寻址取 ctx 身份、字段寻址取请求字段）并投递。
// opts 是装配期注入的投递选项（观测头、追踪注入等），每次调用随消息附加。
func NewPlayerServiceInternal(rt core.ActorInvoker, opts opcall.AdapterOptions) PlayerServiceInternal {
	return &playerServiceInternal{rt: rt, opts: opts}
}

// playerServiceInternal 是默认实现。
type playerServiceInternal struct {
	rt   core.ActorInvoker
	opts opcall.AdapterOptions
}

// Login 投递到目标 actor 并归一化回执。
func (a *playerServiceInternal) Login(ctx context.Context, req *v1.LoginReq) (*v1.LoginReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/Login"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.LoginReply](entry, rep)
}

// Logout 投递到目标 actor 并归一化回执。
func (a *playerServiceInternal) Logout(ctx context.Context, req *v1.LogoutMsg) (*emptypb.Empty, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/Logout"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*emptypb.Empty](entry, rep)
}

// GrantItem 投递到目标 actor 并归一化回执。
func (a *playerServiceInternal) GrantItem(ctx context.Context, req *v1.GrantItemReq) (*v1.GrantItemReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GrantItem"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.GrantItemReply](entry, rep)
}

// GetPlayer 投递到目标 actor 并归一化回执。
func (a *playerServiceInternal) GetPlayer(ctx context.Context, req *v1.GetPlayerReq) (*v1.PlayerReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GetPlayer"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PlayerReply](entry, rep)
}
