// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/game/v1/player_service.proto

package gamev1rpc

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/game/v1"
	core "github.com/huangyuCN/atlas/contrib/actor/core"
	opcall "github.com/huangyuCN/atlas/contrib/actor/opcall"
	grpc "google.golang.org/grpc"
)

// PlayerServiceEdge 是 PlayerService 的客户端面（access=CLIENT，经网关/帧通道调用）。
type PlayerServiceEdge interface {
	GetPlayerData(ctx context.Context, req *v1.GetPlayerDataReq) (*v1.PlayerDataReply, error)
	GetBackpack(ctx context.Context, req *v1.GetBackpackReq) (*v1.BackpackReply, error)
	EnterMatchQueue(ctx context.Context, req *v1.EnterMatchQueueReq) (*v1.EnterMatchQueueReply, error)
	CancelMatch(ctx context.Context, req *v1.CancelMatchReq) (*v1.CancelMatchReply, error)
	GetMatchStatus(ctx context.Context, req *v1.GetMatchStatusReq) (*v1.MatchStatusReply, error)
	CreateParty(ctx context.Context, req *v1.CreatePartyReq) (*v1.PartyReply, error)
	JoinParty(ctx context.Context, req *v1.JoinPartyReq) (*v1.PartyReply, error)
	LeaveParty(ctx context.Context, req *v1.LeavePartyReq) (*v1.PartyReply, error)
	GetParty(ctx context.Context, req *v1.GetPartyReq) (*v1.PartyReply, error)
	QueueParty(ctx context.Context, req *v1.QueuePartyReq) (*v1.PartyQueueReply, error)
}

// RegisterPlayerServiceEdge 把客户端面（access=CLIENT，经网关/帧通道调用）注册到 gRPC server。
// 形参类型即本面接口：把另一个面的实现注册进来在编译期即失败（类型级隔离）。
func RegisterPlayerServiceEdge(s grpc.ServiceRegistrar, impl PlayerServiceEdge) {
	s.RegisterService(&playerServiceEdgeDesc, impl)
}

// playerServiceEdgeDesc 是 PlayerServiceEdge 的 gRPC 服务描述（Methods 取自本面方法集）。
var playerServiceEdgeDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.PlayerService",
	HandlerType: (*PlayerServiceEdge)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetPlayerData", Handler: handlePlayerServiceEdgeGetPlayerData},
		{MethodName: "GetBackpack", Handler: handlePlayerServiceEdgeGetBackpack},
		{MethodName: "EnterMatchQueue", Handler: handlePlayerServiceEdgeEnterMatchQueue},
		{MethodName: "CancelMatch", Handler: handlePlayerServiceEdgeCancelMatch},
		{MethodName: "GetMatchStatus", Handler: handlePlayerServiceEdgeGetMatchStatus},
		{MethodName: "CreateParty", Handler: handlePlayerServiceEdgeCreateParty},
		{MethodName: "JoinParty", Handler: handlePlayerServiceEdgeJoinParty},
		{MethodName: "LeaveParty", Handler: handlePlayerServiceEdgeLeaveParty},
		{MethodName: "GetParty", Handler: handlePlayerServiceEdgeGetParty},
		{MethodName: "QueueParty", Handler: handlePlayerServiceEdgeQueueParty},
	},
	Metadata: "api/game/v1/player_service.proto",
}

// handlePlayerServiceEdgeGetPlayerData 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeGetPlayerData(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetPlayerDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).GetPlayerData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GetPlayerData"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).GetPlayerData(ctx, req.(*v1.GetPlayerDataReq))
	})
}

// handlePlayerServiceEdgeGetBackpack 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeGetBackpack(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetBackpackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).GetBackpack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GetBackpack"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).GetBackpack(ctx, req.(*v1.GetBackpackReq))
	})
}

// handlePlayerServiceEdgeEnterMatchQueue 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeEnterMatchQueue(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.EnterMatchQueueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).EnterMatchQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/EnterMatchQueue"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).EnterMatchQueue(ctx, req.(*v1.EnterMatchQueueReq))
	})
}

// handlePlayerServiceEdgeCancelMatch 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeCancelMatch(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.CancelMatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/CancelMatch"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).CancelMatch(ctx, req.(*v1.CancelMatchReq))
	})
}

// handlePlayerServiceEdgeGetMatchStatus 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeGetMatchStatus(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetMatchStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).GetMatchStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GetMatchStatus"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).GetMatchStatus(ctx, req.(*v1.GetMatchStatusReq))
	})
}

// handlePlayerServiceEdgeCreateParty 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeCreateParty(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.CreatePartyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).CreateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/CreateParty"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).CreateParty(ctx, req.(*v1.CreatePartyReq))
	})
}

// handlePlayerServiceEdgeJoinParty 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeJoinParty(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.JoinPartyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).JoinParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/JoinParty"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).JoinParty(ctx, req.(*v1.JoinPartyReq))
	})
}

// handlePlayerServiceEdgeLeaveParty 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeLeaveParty(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.LeavePartyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).LeaveParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/LeaveParty"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).LeaveParty(ctx, req.(*v1.LeavePartyReq))
	})
}

// handlePlayerServiceEdgeGetParty 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeGetParty(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetPartyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).GetParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/GetParty"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).GetParty(ctx, req.(*v1.GetPartyReq))
	})
}

// handlePlayerServiceEdgeQueueParty 解包请求并经拦截器调用本面实现。
func handlePlayerServiceEdgeQueueParty(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.QueuePartyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceEdge).QueueParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/game.v1.PlayerService/QueueParty"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(PlayerServiceEdge).QueueParty(ctx, req.(*v1.QueuePartyReq))
	})
}

// NewPlayerServiceEdge 返回 actor 支撑的客户端面（access=CLIENT，经网关/帧通道调用）默认实现：
// 按路由条目解析目标 PID（会话寻址取 ctx 身份、字段寻址取请求字段）并投递。
// opts 是装配期注入的投递选项（观测头、追踪注入等），每次调用随消息附加。
func NewPlayerServiceEdge(rt core.ActorInvoker, opts opcall.AdapterOptions) PlayerServiceEdge {
	return &playerServiceEdge{rt: rt, opts: opts}
}

// playerServiceEdge 是默认实现。
type playerServiceEdge struct {
	rt   core.ActorInvoker
	opts opcall.AdapterOptions
}

// GetPlayerData 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) GetPlayerData(ctx context.Context, req *v1.GetPlayerDataReq) (*v1.PlayerDataReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GetPlayerData"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PlayerDataReply](entry, rep)
}

// GetBackpack 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) GetBackpack(ctx context.Context, req *v1.GetBackpackReq) (*v1.BackpackReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GetBackpack"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.BackpackReply](entry, rep)
}

// EnterMatchQueue 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) EnterMatchQueue(ctx context.Context, req *v1.EnterMatchQueueReq) (*v1.EnterMatchQueueReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/EnterMatchQueue"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.EnterMatchQueueReply](entry, rep)
}

// CancelMatch 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) CancelMatch(ctx context.Context, req *v1.CancelMatchReq) (*v1.CancelMatchReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/CancelMatch"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.CancelMatchReply](entry, rep)
}

// GetMatchStatus 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) GetMatchStatus(ctx context.Context, req *v1.GetMatchStatusReq) (*v1.MatchStatusReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GetMatchStatus"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.MatchStatusReply](entry, rep)
}

// CreateParty 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) CreateParty(ctx context.Context, req *v1.CreatePartyReq) (*v1.PartyReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/CreateParty"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PartyReply](entry, rep)
}

// JoinParty 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) JoinParty(ctx context.Context, req *v1.JoinPartyReq) (*v1.PartyReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/JoinParty"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PartyReply](entry, rep)
}

// LeaveParty 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) LeaveParty(ctx context.Context, req *v1.LeavePartyReq) (*v1.PartyReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/LeaveParty"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PartyReply](entry, rep)
}

// GetParty 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) GetParty(ctx context.Context, req *v1.GetPartyReq) (*v1.PartyReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/GetParty"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PartyReply](entry, rep)
}

// QueueParty 投递到目标 actor 并归一化回执。
func (a *playerServiceEdge) QueueParty(ctx context.Context, req *v1.QueuePartyReq) (*v1.PartyQueueReply, error) {
	entry := v1.PlayerServiceRouteTable["/game.v1.PlayerService/QueueParty"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.PartyQueueReply](entry, rep)
}
