// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1rpc

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/battle/v1"
	core "github.com/huangyuCN/atlas/contrib/actor/core"
	opcall "github.com/huangyuCN/atlas/contrib/actor/opcall"
	grpc "google.golang.org/grpc"
)

// BattleServiceInternal 是 BattleService 的服务面（access=INTERNAL，服务间经 gRPC 调用）。
type BattleServiceInternal interface {
	Create(ctx context.Context, req *v1.CreateBattleRequest) (*v1.CreateBattleReply, error)
	GetState(ctx context.Context, req *v1.GetStateReq) (*v1.GetStateReply, error)
	IssueEntryTicket(ctx context.Context, req *v1.IssueEntryTicketReq) (*v1.IssueEntryTicketReply, error)
}

// RegisterBattleServiceInternal 把服务面（access=INTERNAL，服务间经 gRPC 调用）注册到 gRPC server。
// 形参类型即本面接口：把另一个面的实现注册进来在编译期即失败（类型级隔离）。
func RegisterBattleServiceInternal(s grpc.ServiceRegistrar, impl BattleServiceInternal) {
	s.RegisterService(&battleServiceInternalDesc, impl)
}

// battleServiceInternalDesc 是 BattleServiceInternal 的 gRPC 服务描述（Methods 取自本面方法集）。
var battleServiceInternalDesc = grpc.ServiceDesc{
	ServiceName: "battle.v1.BattleService",
	HandlerType: (*BattleServiceInternal)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Create", Handler: handleBattleServiceInternalCreate},
		{MethodName: "GetState", Handler: handleBattleServiceInternalGetState},
		{MethodName: "IssueEntryTicket", Handler: handleBattleServiceInternalIssueEntryTicket},
	},
	Metadata: "api/battle/v1/battle_service.proto",
}

// handleBattleServiceInternalCreate 解包请求并经拦截器调用本面实现。
func handleBattleServiceInternalCreate(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.CreateBattleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceInternal).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/battle.v1.BattleService/Create"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BattleServiceInternal).Create(ctx, req.(*v1.CreateBattleRequest))
	})
}

// handleBattleServiceInternalGetState 解包请求并经拦截器调用本面实现。
func handleBattleServiceInternalGetState(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.GetStateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceInternal).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/battle.v1.BattleService/GetState"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BattleServiceInternal).GetState(ctx, req.(*v1.GetStateReq))
	})
}

// handleBattleServiceInternalIssueEntryTicket 解包请求并经拦截器调用本面实现。
func handleBattleServiceInternalIssueEntryTicket(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(v1.IssueEntryTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BattleServiceInternal).IssueEntryTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/battle.v1.BattleService/IssueEntryTicket"}
	return interceptor(ctx, in, info, func(ctx context.Context, req any) (any, error) {
		return srv.(BattleServiceInternal).IssueEntryTicket(ctx, req.(*v1.IssueEntryTicketReq))
	})
}

// NewBattleServiceInternal 返回 actor 支撑的服务面（access=INTERNAL，服务间经 gRPC 调用）默认实现：
// 按路由条目解析目标 PID（会话寻址取 ctx 身份、字段寻址取请求字段）并投递。
// opts 是装配期注入的投递选项（观测头、追踪注入等），每次调用随消息附加。
func NewBattleServiceInternal(rt core.ActorInvoker, opts opcall.AdapterOptions) BattleServiceInternal {
	return &battleServiceInternal{rt: rt, opts: opts}
}

// battleServiceInternal 是默认实现。
type battleServiceInternal struct {
	rt   core.ActorInvoker
	opts opcall.AdapterOptions
}

// Create 投递到目标 actor 并归一化回执。
func (a *battleServiceInternal) Create(ctx context.Context, req *v1.CreateBattleRequest) (*v1.CreateBattleReply, error) {
	entry := v1.BattleServiceRouteTable["/battle.v1.BattleService/Create"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.CreateBattleReply](entry, rep)
}

// GetState 投递到目标 actor 并归一化回执。
func (a *battleServiceInternal) GetState(ctx context.Context, req *v1.GetStateReq) (*v1.GetStateReply, error) {
	entry := v1.BattleServiceRouteTable["/battle.v1.BattleService/GetState"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.GetStateReply](entry, rep)
}

// IssueEntryTicket 投递到目标 actor 并归一化回执。
func (a *battleServiceInternal) IssueEntryTicket(ctx context.Context, req *v1.IssueEntryTicketReq) (*v1.IssueEntryTicketReply, error) {
	entry := v1.BattleServiceRouteTable["/battle.v1.BattleService/IssueEntryTicket"]
	rep, err := opcall.CallFromContext(ctx, a.rt, entry, req, a.opts.SendOptions...)
	if err != nil {
		return nil, err
	}
	return opcall.Reply[*v1.IssueEntryTicketReply](entry, rep)
}
