// Code generated by protoc-gen-atlas-actor. DO NOT EDIT.
// versions:
// - protoc-gen-atlas-actor v0.1.0
// - protoc             v5.26.1
// source: api/battle/v1/battle_service.proto

package battlev1rpc

import (
	context "context"
	v1 "github.com/huangyuCN/atlas-game-layout/api/battle/v1"
	grpc "google.golang.org/grpc"
)

// BattleServiceClient 是 BattleService 服务面的类型化 gRPC 客户端（跨服务调用）。
type BattleServiceClient interface {
	Create(ctx context.Context, req *v1.CreateBattleRequest) (*v1.CreateBattleReply, error)
	GetState(ctx context.Context, req *v1.GetStateReq) (*v1.GetStateReply, error)
	IssueEntryTicket(ctx context.Context, req *v1.IssueEntryTicketReq) (*v1.IssueEntryTicketReply, error)
}

// battleServiceClient 是客户端实现。
type battleServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewBattleServiceClient 基于连接创建类型化客户端。
func NewBattleServiceClient(cc grpc.ClientConnInterface) BattleServiceClient {
	return &battleServiceClient{cc: cc}
}

// Create 发起一次一元调用。
func (c *battleServiceClient) Create(ctx context.Context, req *v1.CreateBattleRequest) (*v1.CreateBattleReply, error) {
	out := new(v1.CreateBattleReply)
	if err := c.cc.Invoke(ctx, "/battle.v1.BattleService/Create", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// GetState 发起一次一元调用。
func (c *battleServiceClient) GetState(ctx context.Context, req *v1.GetStateReq) (*v1.GetStateReply, error) {
	out := new(v1.GetStateReply)
	if err := c.cc.Invoke(ctx, "/battle.v1.BattleService/GetState", req, out); err != nil {
		return nil, err
	}
	return out, nil
}

// IssueEntryTicket 发起一次一元调用。
func (c *battleServiceClient) IssueEntryTicket(ctx context.Context, req *v1.IssueEntryTicketReq) (*v1.IssueEntryTicketReply, error) {
	out := new(v1.IssueEntryTicketReply)
	if err := c.cc.Invoke(ctx, "/battle.v1.BattleService/IssueEntryTicket", req, out); err != nil {
		return nil, err
	}
	return out, nil
}
