// <auto-generated>
// Code generated by protoc-gen-atlas-client (lang=csharp). DO NOT EDIT.
// source: api/battle/v1/battle_service.proto
// </auto-generated>
#nullable enable
// 序列化语义（protojson）：camelCase 字段名、int64/uint64 读字符串、bytes 为 base64、
// 枚举以枚举名（字符串）下发（未知名前向兼容）。

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Atlas.Client;
using Atlas.Game.Lockstep;
using Atlas.Google.Protobuf;

namespace Atlas.Battle.V1;

/// <summary>JoinBattleReq DTO（protojson JSON 语义）。</summary>
public sealed class JoinBattleReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>JoinBattleReply DTO（protojson JSON 语义）。</summary>
public sealed class JoinBattleReply
{
    [JsonPropertyName("meta")]
    public SessionMeta? Meta { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("currentFrame")]
    public ulong? CurrentFrame { get; set; }

    [JsonPropertyName("snapshot")]
    public SnapshotMeta? Snapshot { get; set; }

}

/// <summary>FrameInputReq DTO（protojson JSON 语义）。</summary>
public sealed class FrameInputReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("input")]
    public LockstepInput? Input { get; set; }

}

/// <summary>FrameInputReply DTO（protojson JSON 语义）。</summary>
public sealed class FrameInputReply
{
}

/// <summary>SyncFramesReq DTO（protojson JSON 语义）。</summary>
public sealed class SyncFramesReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("lastSeenFrame")]
    public ulong? LastSeenFrame { get; set; }

}

/// <summary>SyncFramesReply DTO（protojson JSON 语义）。</summary>
public sealed class SyncFramesReply
{
    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("currentFrame")]
    public ulong? CurrentFrame { get; set; }

    [JsonPropertyName("snapshot")]
    public SnapshotMeta? Snapshot { get; set; }

    [JsonPropertyName("missed")]
    public List<FrameInputs>? Missed { get; set; }

}

/// <summary>FrameBroadcast DTO（protojson JSON 语义）。</summary>
public sealed class FrameBroadcast
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("frame")]
    public LockstepFrame? Frame { get; set; }

}

/// <summary>BattleEndNotify DTO（protojson JSON 语义）。</summary>
public sealed class BattleEndNotify
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("winnerPlayerId")]
    public string? WinnerPlayerId { get; set; }

}

/// <summary>BattleService 的业务 op 客户端 stub：身份由会话承载，消息零身份字段；
/// 与 gRPC 生成的 BattleServiceClient（连接级 client）错开命名。</summary>
public sealed class BattleServiceOpClient
{
    private static readonly JsonSerializerOptions JsonOpts = new();
    private readonly IAtlasInvoker _inv;

    public BattleServiceOpClient(IAtlasInvoker inv) => _inv = inv;

    /// <summary>/battle.v1.BattleService/JoinBattle：请求-响应；业务拒绝返回业务错误（Reason 为主键）。</summary>
    public async Task<JoinBattleReply?> JoinBattleAsync(JoinBattleReq? req, CancellationToken cancellationToken = default)
    {
        var payload = JsonSerializer.SerializeToUtf8Bytes(req ?? new JoinBattleReq(), JsonOpts);
        var data = await _inv.InvokeRawAsync("/battle.v1.BattleService/JoinBattle", payload, cancellationToken);
        return data.Length == 0 ? null : JsonSerializer.Deserialize<JoinBattleReply>(data, JsonOpts);
    }
    /// <summary>/battle.v1.BattleService/SendFrameInput：单向调用（returns Empty，无回执）。</summary>
    public async Task SendFrameInputAsync(FrameInputReq? req, CancellationToken cancellationToken = default)
    {
        var payload = JsonSerializer.SerializeToUtf8Bytes(req ?? new FrameInputReq(), JsonOpts);
        await _inv.InvokeRawAsync("/battle.v1.BattleService/SendFrameInput", payload, cancellationToken);
    }
    /// <summary>/battle.v1.BattleService/SyncFrames：请求-响应；业务拒绝返回业务错误（Reason 为主键）。</summary>
    public async Task<SyncFramesReply?> SyncFramesAsync(SyncFramesReq? req, CancellationToken cancellationToken = default)
    {
        var payload = JsonSerializer.SerializeToUtf8Bytes(req ?? new SyncFramesReq(), JsonOpts);
        var data = await _inv.InvokeRawAsync("/battle.v1.BattleService/SyncFrames", payload, cancellationToken);
        return data.Length == 0 ? null : JsonSerializer.Deserialize<SyncFramesReply>(data, JsonOpts);
    }
}

