// <auto-generated>
// Code generated by protoc-gen-atlas-client (lang=csharp). DO NOT EDIT.
// source: api/battle/v1/battle.proto
// </auto-generated>
#nullable enable
// 序列化语义（protojson）：camelCase 字段名、int64/uint64 读字符串、bytes 为 base64、
// 枚举以枚举名（字符串）下发（未知名前向兼容）。

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Atlas.Client;

namespace Atlas.Battle.V1;

/// <summary>CreateBattleRequest DTO（protojson JSON 语义）。</summary>
public sealed class CreateBattleRequest
{
    [JsonPropertyName("matchId")]
    public string? MatchId { get; set; }

    [JsonPropertyName("playerIds")]
    public List<string>? PlayerIds { get; set; }

    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>CreateBattleReply DTO（protojson JSON 语义）。</summary>
public sealed class CreateBattleReply
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>GetBattleRequest DTO（protojson JSON 语义）。</summary>
public sealed class GetBattleRequest
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>GetBattleReply DTO（protojson JSON 语义）。</summary>
public sealed class GetBattleReply
{
    [JsonPropertyName("state")]
    public string? State { get; set; }

}

/// <summary>PlayerResult DTO（protojson JSON 语义）。</summary>
public sealed class PlayerResult
{
    [JsonPropertyName("playerId")]
    public string? PlayerId { get; set; }

    [JsonPropertyName("win")]
    public bool? Win { get; set; }

    [JsonPropertyName("score")]
    public int? Score { get; set; }

}

/// <summary>BattleSettledEvent DTO（protojson JSON 语义）。</summary>
public sealed class BattleSettledEvent
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

    [JsonPropertyName("matchId")]
    public string? MatchId { get; set; }

    [JsonPropertyName("players")]
    public List<PlayerResult>? Players { get; set; }

}

/// <summary>GetStateReq DTO（protojson JSON 语义）。</summary>
public sealed class GetStateReq
{
    [JsonPropertyName("battleId")]
    public string? BattleId { get; set; }

}

/// <summary>GetStateReply DTO（protojson JSON 语义）。</summary>
public sealed class GetStateReply
{
    [JsonPropertyName("state")]
    public string? State { get; set; }

    [JsonNumberHandling(JsonNumberHandling.AllowReadingFromString)][JsonPropertyName("currentFrame")]
    public ulong? CurrentFrame { get; set; }

    [JsonPropertyName("playerCount")]
    public uint? PlayerCount { get; set; }

}

